#!/usr/bin/env python3
"""b39 JSON 生成脚本：穿搭/拉片/摄影/表达混合类（10篇）"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "scripts" / "scene-data"
OUT.mkdir(parents=True, exist_ok=True)

DATE = "2026-08-08"
PLATFORM = "xiaohongshu"

V = [
(
 "summer-cool-slim-skirt", "夏天舒适凉爽又显高显瘦的裙子，你得这么挑", "Summer Skirts: Cool, Comfy and Slimming", "2分12秒", "服装 · 裙子选购", "http://xhslink.cn/o/7YpNgpRXJly",
 [
  ("开场：斜裁 vs 直裁", "Opening: Bias vs Straight Cut", "00:00", "这样是直裁，这样是斜裁。夏天想要一件既舒适又显高显瘦的连衣裙，就看这几个硬性指标。",
   [("直裁斜裁两种裁法。", "There's straight cut and bias cut.", "bias cut（斜裁）"),
    ("看几个硬性指标。", "Check a few hard criteria.", "criterion（指标）")]),
  ("直裁无弹力", "Straight Cut Has No Stretch", "00:06", "直裁是顺着面料的纬纱经纱垂直裁剪，这种的话它就没有任何弹力。",
   [("直裁顺着经纬纱。", "Straight cut follows the grain.", "grain（纱向）"),
    ("直裁没有弹力。", "Straight cut has no stretch.", "stretch（弹力）")]),
  ("斜裁更费料更弹", "Bias Cut: Costly but Stretchy", "00:14", "斜裁就是沿着面料45度斜向去裁剪，更费料子，但弹性更大，大胸小胸都能自动调节。",
   [("斜裁沿45度裁剪。", "Bias cut runs on the 45-degree angle.", "45-degree（45度）"),
    ("弹性大自动调节。", "It stretches to fit automatically.", "adjust（调节）")]),
  ("斜裁垂性好", "Bias Cut Drapes Better", "00:31", "斜向裁剪的垂性也比较好，确实更适合用在连衣裙上，能显著提高舒适度。",
   [("斜裁垂坠感更好。", "Bias cuts drape better.", "drape（垂坠）"),
    ("提高裙子舒适度。", "It boosts the dress's comfort.", "comfort（舒适度）")]),
  ("高腰线显瘦", "High Waistline Slims", "00:40", "找腰线在手肘或手肘向下三公分的位置，这种就是高腰线，能美化身材比例。",
   [("腰线到手肘位置。", "The waist hits at the elbow.", "waistline（腰线）"),
    ("高腰线美化比例。", "High waists improve proportions.", "proportion（比例）")]),
  ("麻棉混纺", "The Linen-Cotton Blend", "00:55", "丝太贵、麻扎人、化纤透气差一截，建议大家尝试麻棉混纺，结合两者优点轻肤透气。",
   [("麻棉混纺结合优点。", "Linen-cotton blends combine the best.", "blend（混纺）"),
    ("轻肤舒适又透气。", "Soft on skin and breathable.", "breathable（透气的）")]),
  ("泡泡纱结构", "The Seersucker Structure", "01:08", "多选表面带机理的，一个一个凸起像小气泡，这叫泡泡纱，是纺织过程织出来的，洗多少次都不塌。",
   [("表面泡泡叫泡泡纱。", "Those bubbles are seersucker.", "seersucker（泡泡纱）"),
    ("织出来的不会塌。", "Woven-in bubbles never flatten.", "flatten（塌陷）")]),
  ("袖笼贴边与开股缝", "Armhole Binding and Flat Felled Seams", "01:43", "无袖衣服袖笼选本布贴边工艺，简洁高级；内里贴身缝缝选开股的，更薄舒适度更高。",
   [("袖笼用本布贴边。", "Armholes get self-fabric binding.", "binding（贴边）"),
    ("开股缝缝更薄更舒适。", "Flat-felled seams are thinner and comfy.", "flat-felled（开股缝）")]),
 ],
),
(
 "clothes-quality-one-look", "衣服好坏分辨真的只需一眼", "Judge Clothes at a Glance", "55秒", "服装 · 工艺辨识", "http://xhslink.cn/o/7eYFp0HylGg",
 [
  ("开场：一眼分辨", "Opening: One Glance", "00:00", "差的、好的、差的、好的，女生T恤千万分辨就靠几个关键细节。",
   [("好坏一眼分辨。", "Good and bad tell at a glance.", "at a glance（一眼）"),
    ("T恤有几个关键细节。", "Tees have key details.", "detail（细节）")]),
  ("前短后长避开", "Skip the Cropped-Back Cut", "00:04", "女生T恤千万不要选前短后长的，上身之后胸部顶起来，前面变得更壮还翘。",
   [("前短后长别选。", "Don't pick the cropped-back cut.", "cropped（前短）"),
    ("胸部顶起显壮。", "It puffs at the chest.", "puff（鼓起）")]),
  ("开场先标差的", "Bad One First", "00:01", "开场先标「差的」：手指捏住白色衣摆，把负面样例钉在画面中央，建立好坏对比的观看预期。",
   [("先标出差的样例。", "Label the bad sample first.", "label（标注）"),
    ("建立对比预期。", "Set up the bad-vs-good expectation.", "contrast（对比）")]),
  ("领口横开两公分", "Collar Opening: Two Fingers", "00:14", "领子想久穿不变形，就选领横开搭自己手掌至少两公分以上的，穿脱才不容易被撑变形。",
   [("领横开要够大。", "The opening must be wide enough.", "opening（领口）"),
    ("穿脱不易撑变形。", "It won't warp from pulling on.", "warp（变形）")]),
  ("领口过紧反例", "The Too-Tight Collar", "00:28", "领口过紧的反例：螺纹再好，久穿仍容易发黄变形，穿脱次数多了领子照样松垮。",
   [("领口过紧易变形。", "A tight collar warps with wear.", "tight（过紧的）"),
    ("螺纹再好也扛不住。", "Even good ribbing can't save it.", "ribbing（螺纹）")]),
  ("领圈太厚", "The Thick Neckline", "00:36", "溜肩、脖子粗的女生，这种领圈太厚的别考虑，里外缝份加面料五层只会显得脖子更粗肩更溜。",
   [("厚领圈显脖子粗。", "Thick necklines thicken the neck.", "neckline（领圈）"),
    ("多层缝份堆厚度。", "Layered seams add bulk.", "bulk（厚重）")]),
  ("通肩拉条拐角", "The Shoulder Tape Corner", "00:41", "但凡带通肩拉条的衣服，拉条拐角这一块一定要从正面看，有宽有窄说明衣服拐角出现了质量问题。",
   [("拉条拐角看正面。", "Check the tape corner from the front.", "corner（拐角）"),
    ("宽窄不一说明质量问题。", "Uneven width signals a flaw.", "flaw（瑕疵）")]),
  ("拐角凸起", "The Bump at the Corner", "00:52", "这种拐角问题你穿身上会有一个小凸起，会包的，看着就廉价。",
   [("穿上有小凸起。", "It bumps out when worn.", "bump（凸起）"),
    ("细节决定质感。", "Details decide the feel.", "texture（质感）")]),
 ],
),
(
 "clothes-hit-or-miss-detail", "衣服夯爆了还是拉完了其实一个细节就能分辨", "One Detail Separates Hit or Miss Clothes", "47秒", "服装 · 内衬细节", "http://xhslink.cn/o/4GVSmlMFyjm",
 [
  ("开场：短裙内衬", "Opening: The Skirt Lining", "00:00", "开场先给「差的」标签，焦点落在棕色短裤侧缝与口袋附近的内里，检查内衬做法。",
   [("开场先标差的。", "The 'bad' label opens the clip.", "label（标签）"),
    ("焦点落在内衬上。", "The focus is on the lining.", "lining（内衬）")]),
  ("内衬做法", "The Lining Construction", "00:04", "进入主题：检查短裙里的内衬做法，而不是只看外层面料，内衬做得好坏一眼就能分辨。",
   [("内衬做法才是关键。", "The lining construction is the key.", "construction（做工）"),
    ("一眼分辨好坏。", "Good or bad tells at a glance.", "tell（分辨）")]),
  ("缝缝翻外面", "Seams Turned Out", "00:08", "缝缝应该翻过来做到外面的才是好的，朝内的毛缝被判为不好，像这种翻外就是好的。",
   [("缝缝翻到外面才对。", "Seams should face outward.", "seam（缝缝）"),
    ("这就是好的做法。", "That's the good version.", "version（做法）")]),
  ("内衬两作用", "Two Jobs of the Lining", "00:12", "内衬除了防走光以外，还考虑到舒适，这样蹲下坐下的时候这块才不会有卡裆或异物感。",
   [("内衬防走光。", "Lining prevents flashing.", "flash（走光）"),
    ("也避免卡裆感。", "It also stops pinching.", "pinch（卡住）")]),
  ("肩线按扣", "The Shoulder Snap", "00:19", "肩线内里做了小角的按扣，方便拆卸，内衬掉到的布穿可以随时拿下来，穿的时候扣好就不掉。",
   [("按扣方便拆卸。", "Snaps make it removable.", "removable（可拆的）"),
    ("扣好肩带不掉。", "Buttoned up, the strap stays.", "strap（肩带）")]),
  ("无固定肩带", "Unsecured Straps", "00:28", "像这种普通的就什么都没有，尤其无袖款肩带没有固定，特别容易跑下来。",
   [("普通内衬没固定。", "Basic linings lack fixing.", "fixing（固定）"),
    ("无袖肩带容易掉。", "Strap-less tops shift easily.", "shift（移动）")]),
  ("不可拆看固定线", "Check the Fixing Stitch", "00:34", "不可拆卸的内衬，直接看下摆两侧有没有固定线，有就是好的。",
   [("看下摆固定线。", "Check for side fixing stitches.", "fixing stitch（固定线）"),
    ("有固定线就是好的。", "Stitches mean it's a keeper.", "keeper（值得留的）")]),
  ("无固定线尴尬", "The Awkward Lining", "00:39", "侧边没有固定线的，上完厕所回来一个不小心，这个里布就可能挂在腰上没下来，很尴尬。",
   [("没固定线会乱跑。", "Without stitches, the lining rides up.", "ride up（上移）"),
    ("里布挂腰上很尴尬。", "It can stick out at the waist.", "awkward（尴尬的）")]),
 ],
),
(
 "dry-film-pull-technique", "比新疆还干的拉片技巧！！！", "The Driest Film-Pull Trick: Reverse Reasoning", "58秒", "摄影 · 逆向反推", "http://xhslink.cn/o/2VGWSbWm81n",
 [
  ("开场：逆向反推", "Opening: Reverse Reasoning", "00:00", "分享一个超级干的拉片技巧，叫做逆向反推，尤其是让摆弯开头的照片。",
   [("技巧叫逆向反推。", "The trick is reverse reasoning.", "reverse reasoning（逆向反推）"),
    ("尤其适合摆弯开头。", "Great for dramatic openings.", "dramatic（震撼的）")]),
  ("原片很普通", "The Source Is Ordinary", "00:04", "冲击力很强对吧？但其实是没超了，因为从花絮头就能看到非常普通的沙滩，浪花也小。",
   [("成片冲击力强。", "The final shot hits hard.", "impact（冲击力）"),
    ("原景其实很普通。", "The scene itself is ordinary.", "ordinary（普通的）")]),
  ("如何解决问题", "How Did They Solve It?", "00:12", "场景实在过于普通，那为了避免快速游客，只要想原作者是怎么解决这个问题的。",
   [("想原作者如何解决。", "Ask how the original solved it.", "solve（解决）"),
    ("反推拍摄思路。", "Reverse-engineer the thinking.", "reverse-engineer（反推）")]),
  ("元素错位与视线交叉", "Misalignment and Crossing Lines", "00:15", "首先是元素的互相错位，再加上视线的相互交叉，拍双人的时候用的特别多。",
   [("元素互相错位。", "Elements offset each other.", "offset（错位）"),
    ("视线相互交叉。", "Sightlines cross.", "sightline（视线）")]),
  ("通过成片反推", "Reverse the Finished Shot", "00:26", "想过自己拉片，形容水平和技术，一定要通过别人的成片反推原图反推原环境，得到拍摄思路。",
   [("通过成片反推原图。", "Reverse the final to the raw.", "raw（原图）"),
    ("得到拍摄思路。", "Recover the photographer's idea.", "idea（思路）")]),
  ("例：花不够多", "Example: Not Enough Flowers", "00:35", "这张照片如果你去过很多外景，就知道这样拍大概率是这儿的花不够多不够密，或周围中远景不好处理。",
   [("环境不够美。", "The setting isn't lush enough.", "lush（茂盛的）"),
    ("所以用借景方法。", "So they borrowed a view.", "borrow（借）")]),
  ("借景解决", "Borrowing the View", "00:42", "所以用了镜子这种借景的方法去拍，刚好也应对了摄影做减法的这种原理。",
   [("用镜子借景拍摄。", "A mirror borrows the view.", "mirror（镜子）"),
    ("符合做减法原理。", "It fits the less-is-more idea.", "less is more（做减法）")]),
  ("结尾技巧", "Closing Tip", "00:47", "如果照片通过借位或巧妙的构图角度来拍，大概率是客观环境不够；反过来大环境大场景就能拍好。",
   [("借位多因环境不够。", "Clever angles often hide a weak scene.", "hide（掩盖）"),
    ("大环境直接拍。", "Big scenes need no tricks.", "trick（技巧）")]),
 ],
),
(
 "phone-flashlight-sunlight", "低成本模拟阳光，一个普通手机电筒带来的治愈氛围感", "Simulate Sunlight With a Phone Flashlight", "28秒", "摄影 · 布光技巧", "http://xhslink.cn/o/22ew0FAfckz",
 [
  ("开场：手电照水袋", "Opening: Flashlight Through Water", "00:00", "手电光穿过袋中清水，投向干橙片摆盘，低成本模拟阳光的治愈感开场。",
   [("手电光穿过水袋。", "A flashlight beam passes through water.", "beam（光束）"),
    ("投向干橙片摆盘。", "It hits a plate of dried oranges.", "dried orange（干橙片）")]),
  ("粼粼波光", "Shimmering Ripples", "00:03", "水折射后的光纹落在橙片上，形成粼粼波光，像阳光照在餐桌上。",
   [("水折射形成光纹。", "Water refracts the light into ripples.", "refract（折射）"),
    ("波光粼粼很治愈。", "Shimmering light feels healing.", "shimmer（微光）")]),
  ("线条侧光", "Side Line-Light", "00:07", "线条侧光在盘面形成斜影，营造延时或窗影感，让静物有了时间感。",
   [("线条侧光打斜影。", "Side light casts a slanted shadow.", "shadow（阴影）"),
    ("营造窗影感。", "It mimics window light.", "window light（窗光）")]),
  ("治愈开场镜头", "The Healing Opening Shot", "00:11", "侧光长影配合橙片摆盘，做成治愈感开场镜头，氛围感拉满。",
   [("侧光长影配摆盘。", "Long side shadows meet the plate.", "setup（摆盘）"),
    ("做成治愈开场。", "It becomes a healing opener.", "healing（治愈的）")]),
  ("玻璃碗青苹果", "Green Apples in a Bowl", "00:14", "窄束侧光打在玻璃碗青苹果上，强调通透与生命力。",
   [("窄束光打苹果。", "A narrow beam lights the apples.", "narrow beam（窄束光）"),
    ("强调通透感。", "It stresses translucence.", "translucence（通透）")]),
  ("固定光源", "Fix the Light", "00:18", "固定光源后得到干净的窗影线条光，画面干净高对比。",
   [("固定光源出线条光。", "Fix the source for clean lines.", "fixed light（固定光）"),
    ("画面干净高对比。", "Clean and high-contrast.", "high-contrast（高对比）")]),
  ("置物架固定成片", "The Shelf-Fixed Result", "00:21", "置物架固定手电后的成片氛围：干净、高对比、静物感强。",
   [("置物架固定手电。", "Fix the light to a shelf.", "shelf（置物架）"),
    ("静物感很强。", "It reads strongly still-life.", "still-life（静物）")]),
  ("手电加蒸网", "Flashlight Plus Steamer Mesh", "00:25", "手电加蒸网，移动网片即可改变斑驳光圈的疏密与位置，光斑效果随手掌控。",
   [("蒸网制造斑驳光。", "A steamer mesh dapples the light.", "dappled（斑驳的）"),
    ("移动网片调光圈。", "Move the mesh to reshape spots.", "spot（光斑）")]),
 ],
),
(
 "negative-space-photography", "负空间-摄影视觉语言系列课程 第二集", "Negative Space: Photography Visual Language, Ep.2", "13分04秒", "摄影 · 视觉语言", "http://xhslink.cn/o/6oncJUZ4c98",
 [
  ("开场：负空间定义", "Opening: Defining Negative Space", "00:00", "负空间是指画面中主体周围的空白区域，它和主体一起构成完整的画面平衡。",
   [("负空间是主体周围的空白。", "Negative space is the area around the subject.", "negative space（负空间）"),
    ("它参与画面平衡。", "It balances the composition.", "balance（平衡）")]),
  ("空白不是空", "Empty Isn't Nothing", "01:00", "空白不是无内容，负空间同样在传递信息：环境、氛围、情绪都靠它支撑。",
   [("空白也在传递信息。", "Empty areas still carry meaning.", "meaning（含义）"),
    ("氛围情绪靠它支撑。", "Mood leans on negative space.", "mood（氛围）")]),
  ("留白与注意力", "Whitespace Focuses Attention", "03:00", "留白越多，主体越突出，负空间把观众视线牢牢引向被摄对象。",
   [("留白越多主体越突出。", "More space, stronger subject.", "stand out（突出）"),
    ("视线被引向主体。", "The eye lands on the subject.", "attention（注意力）")]),
  ("负空间类型", "Types of Negative Space", "05:00", "天空、水面、纯色墙面、虚化的背景都是负空间，不同材质传递不同情绪。",
   [("天空水面都是负空间。", "Sky and water are negative space.", "sky（天空）"),
    ("不同材质不同情绪。", "Each surface carries its own mood.", "surface（表面）")]),
  ("主体与空间的比例", "The Subject-Space Ratio", "07:00", "主体太小会显得空洞，太大又拥挤，负空间的比例决定画面的呼吸感。",
   [("主体大小要平衡。", "Subject size must balance the space.", "size（大小）"),
    ("比例决定呼吸感。", "Ratio sets the breathing room.", "breathing room（呼吸感）")]),
  ("拍摄中找负空间", "Finding It While Shooting", "09:00", "拍摄前先看背景里有没有干净的留白区域，构图时主动为负空间留位置。",
   [("先找干净留白。", "First hunt for clean open areas.", "open area（开阔区域）"),
    ("构图主动留位置。", "Compose space on purpose.", "compose（构图）")]),
  ("负空间与商业片", "Negative Space in Commercials", "11:00", "商业片和海报常利用负空间放文案、放品牌，让画面透气又高级。",
   [("海报用负空间放文案。", "Posters use space for text.", "poster（海报）"),
    ("画面透气又高级。", "It keeps the frame airy and classy.", "classy（高级的）")]),
  ("总结：留白的力量", "Summary: The Power of Space", "12:00", "学会使用负空间，是摄影从记录走向表达的第二步，少即是多。",
   [("负空间是表达手段。", "Negative space is an expressive tool.", "expressive（表达的）"),
    ("少即是多。", "Less is more.", "less is more（少即是多）")]),
 ],
),
(
 "photo-framework-visual-lang", "框架-摄影视觉语言系列课程 第一集", "Framing: Photography Visual Language, Ep.1", "14分31秒", "摄影 · 视觉语言", "http://xhslink.cn/o/2ulppAXr8o1",
 [
  ("开场：框架定义", "Opening: Defining Framing", "00:00", "框架是画面中天然或人造的结构，把主体框在门框、窗框、洞口里，集中视线。",
   [("框架把主体框起来。", "Framing boxes in the subject.", "frame（框架）"),
    ("门框窗框都算。", "Doors and windows count.", "doorway（门框）")]),
  ("框架的作用", "What Framing Does", "01:30", "框架像画框一样给画面一个边界，让观众第一眼就锁定主体所在区域。",
   [("框架提供边界。", "A frame gives the picture an edge.", "edge（边界）"),
    ("第一眼锁定主体。", "Eyes lock onto the subject zone.", "lock onto（锁定）")]),
  ("天然框架", "Natural Frames", "03:00", "树枝、山形、云层都是天然框架，拍摄时借景入画，不费力气就获得层次。",
   [("树枝云层是天然框。", "Branches and clouds frame naturally.", "natural（天然的）"),
    ("借景入画有层次。", "Borrowed frames add depth.", "depth（层次）")]),
  ("人造框架", "Man-Made Frames", "04:30", "门窗、拱廊、隧道、栅栏都是人造框架，几何感强，适合街拍和建筑摄影。",
   [("拱廊隧道是人造框。", "Arches and tunnels frame man-made.", "arch（拱形）"),
    ("几何感强适合街拍。", "Strong geometry suits street shots.", "street photography（街拍）")]),
  ("框架的叙事", "Frames Tell Stories", "06:00", "框架还能暗示「偷窥」与「旁观」，透过窗户看世界，让照片多一层叙事感。",
   [("框架暗示偷窥视角。", "Frames suggest a voyeur view.", "voyeur（偷窥）"),
    ("照片多了叙事感。", "Photos gain a story layer.", "narrative（叙事）")]),
  ("框内框", "Frame Within a Frame", "08:00", "框内框是更进阶的手法，多重框架层层递进，把视线一路引向画面深处。",
   [("框内框层层递进。", "Layered frames guide the eye in.", "layered（层叠的）"),
    ("视线引向深处。", "The gaze travels inward.", "inward（向内）")]),
  ("避免乱框", "Avoid Messy Frames", "10:00", "框架虽好但不能乱用，过于杂乱的框会抢走主体注意力，记住框架是服务主体的。",
   [("乱框抢主体注意力。", "Messy frames steal attention.", "clutter（杂乱）"),
    ("框架服务主体。", "The frame serves the subject.", "serve（服务）")]),
  ("总结：框与主体", "Summary: Frame and Subject", "13:00", "框架是导演视线的手，它决定了观众先看什么，学摄影先学安排视线。",
   [("框架安排观众视线。", "Frames direct the viewer's eye.", "direct（引导）"),
    ("先学安排视线。", "Learn to arrange the gaze first.", "arrange（安排）")]),
 ],
),
(
 "aesthetic-film-shots-01", "审美提升｜100个电影镜头01/100", "Aesthetic Training: 100 Film Shots 01/100", "3分42秒", "电影 · 审美积累", "http://xhslink.cn/o/90zEB1QvHBj",
 [
  ("开场：审美积累", "Opening: Building Taste", "00:00", "审美提升最快的方式是大量看经典电影镜头，第一期先看十个教科书级的构图画面。",
   [("多看经典镜头提升审美。", "Watching classics builds taste.", "taste（审美）"),
    ("第一期的十个画面。", "Ten frames for episode one.", "frame（画面）")]),
  ("镜头一：对称构图", "Shot One: Symmetry", "00:20", "对称构图把人物放在画面正中，秩序感和仪式感扑面而来，常见于庄重场景。",
   [("对称构图人物居中。", "Symmetry centers the subject.", "symmetry（对称）"),
    ("秩序感扑面而来。", "Order and ceremony fill the frame.", "order（秩序）")]),
  ("镜头二：引导线", "Shot Two: Leading Lines", "00:50", "引导线把视线从画面边缘引向主体，道路、栏杆、光线都是天然引导线。",
   [("引导线引向主体。", "Lines lead to the subject.", "leading lines（引导线）"),
    ("道路栏杆都可用。", "Roads and rails all work.", "road（道路）")]),
  ("镜头三：低角度", "Shot Three: Low Angle", "01:10", "低角度仰拍让主体显得高大权威，适合塑造英雄和强者的形象。",
   [("低角度显高大。", "Low angles look powerful.", "low angle（低角度）"),
    ("塑造强者形象。", "It builds a mighty image.", "mighty（强大的）")]),
  ("镜头四：剪影", "Shot Four: Silhouette", "01:30", "逆光剪影只留轮廓，神秘感和故事感同时拉满，是电影常用的情绪镜头。",
   [("逆光只剩轮廓。", "Backlight leaves only a shape.", "silhouette（剪影）"),
    ("神秘感故事感拉满。", "It's full of mystery and story.", "mystery（神秘）")]),
  ("镜头五：大远景", "Shot Five: Extreme Wide", "01:50", "大远景里人物只是一个小点，孤独感与宏大环境形成强烈对比。",
   [("大远景人物是小点。", "The person is a tiny dot.", "tiny dot（小点）"),
    ("孤独感油然而生。", "Loneliness fills the scene.", "loneliness（孤独）")]),
  ("镜头六：框架构图", "Shot Six: Framing", "02:10", "通过门框或前景物件框住人物，构图立刻有层次，视线被自然引导。",
   [("前景框住人物。", "Foreground frames the person.", "foreground（前景）"),
    ("构图立刻有层次。", "Instant depth in the shot.", "layered（有层次的）")]),
  ("总结：多看多想", "Summary: Watch and Think", "03:00", "看镜头不只是看画面，还要想构图为什么这样安排，把好镜头变成自己的审美库。",
   [("看镜头要想为什么。", "Ask why each shot is framed so.", "why（为什么）"),
    ("积累成自己的审美库。", "Build your own taste library.", "library（库）")]),
 ],
),
(
 "audiovisual-whitespace-power", "从视听留白到权力空间调度", "From Audiovisual Whitespace to Power Dynamics", "5分43秒", "电影 · 视听语言", "http://xhslink.cn/o/ADiwEkRE1eh",
 [
  ("开场：视听留白", "Opening: Audiovisual Whitespace", "00:00", "视听留白不只是画面的空，声音里的留白同样制造悬念与压迫感。",
   [("留白不只是画面。", "Whitespace isn't only visual.", "whitespace（留白）"),
    ("声音留白制造悬念。", "Sound gaps create suspense.", "suspense（悬念）")]),
  ("静默的力量", "The Power of Silence", "01:00", "对话间隙的静默、背景音的突然消失，都让观众紧张起来，静默是最响的声音。",
   [("静默让观众紧张。", "Silence makes viewers tense.", "silence（静默）"),
    ("静默是最响的声音。", "Silence is the loudest sound.", "loud（响亮的）")]),
  ("低机位仰拍", "The Low-Angle Push", "01:10", "极低机位仰拍放大「头朝下压肚子」的反常姿态与尘土冲击，把情绪写成画面力度。",
   [("低机位放大姿态。", "A low angle magnifies the pose.", "low angle（低机位）"),
    ("尘土冲击写情绪。", "Dust impact externalizes emotion.", "impact（冲击）")]),
  ("旋风地堂腿", "The Cyclone Sweep", "01:42", "旋风地堂腿：攻守兼备的旋转动作把对手挡在进身距离外，一招写两种力量。",
   [("旋转动作攻守兼备。", "A rotating move attacks and defends.", "attack and defend（攻守兼备）"),
    ("把对手挡在身外。", "It keeps the foe at bay.", "keep at bay（挡住）")]),
  ("空间调度", "Power and Space", "02:00", "镜头距离和机位高度都在说话：俯拍削弱权威，仰拍抬高地位，距离决定亲疏。",
   [("机位高度传递权力。", "Camera height signals power.", "power（权力）"),
    ("距离决定亲疏。", "Distance sets closeness.", "closeness（亲疏）")]),
  ("权力空间", "Power Through Space", "03:00", "在对话场面里，谁占据画面更大的空间谁就更强势，这是权力空间调度。",
   [("占画面大空间者强势。", "More frame space means more power.", "frame space（画面空间）"),
    ("调度传递权力关系。", "Staging shows the power order.", "staging（调度）")]),
  ("压迫感镜头", "The Squeeze", "04:00", "把人物挤在画面一角，或让背景墙逼近，都能制造压迫感，适合紧张剧情。",
   [("人物挤在角落。", "A cornered figure feels trapped.", "cornered（被逼到角落的）"),
    ("压迫感扑面而来。", "Tension squeezes the frame.", "tension（张力）")]),
  ("总结：空间即语言", "Summary: Space Speaks", "05:00", "空间调度是导演的隐形语言，学会读它，你才真正看懂电影在说什么。",
   [("空间是隐形语言。", "Space is a hidden language.", "hidden（隐藏的）"),
    ("读懂才看懂电影。", "Reading it unlocks the film.", "unlock（解锁）")]),
 ],
),
(
 "high-eq-no-filler-words", "说话别用口水词，高情商都这样表达！", "Ditch Filler Words, Sound Smarter", "28秒", "表达 · 高情商话术", "http://xhslink.cn/o/32JMqPaM74G",
 [
  ("把然后换成", "Swap 'And Then'", "00:00", "「然后」说多了显得没重点，换成进一步来说、更值得一提的是、更重要的是。",
   [("别总说然后。", "Stop overusing 'and then.'", "filler word（口水词）"),
    ("换成进一步来说。", "Say 'furthermore' instead.", "furthermore（进一步说）")]),
  ("承接词替换", "Connectors Upgrade", "00:04", "除此之外、真正值得注意的是，比单一的然后更有逻辑，表达更有层次。",
   [("用除此之外承接。", "Use 'apart from that.'", "apart from that（除此之外）"),
    ("表达更有层次。", "It adds depth to your speech.", "depth（层次）")]),
  ("转折词替换", "Transition Words", "00:07", "「但是」太生硬，换成恰恰相反、换个角度看，语气更柔和还显高情商。",
   [("别生硬说但是。", "Avoid a blunt 'but.'", "blunt（生硬的）"),
    ("换个角度看更柔和。", "Try 'from another angle.'", "from another angle（换个角度）")]),
  ("换句话来说", "In Other Words", "00:13", "想换种方式解释，说「换句话来说」比重复原话更清楚，观众更好懂。",
   [("换句话来说更清楚。", "'In other words' clarifies.", "in other words（换言之）"),
    ("别重复原话。", "Don't repeat the same line.", "repeat（重复）")]),
  ("举例说人话", "Examples That Land", "00:19", "举例别说「比如」，说「最典型的情况是」「打个比方」，例子更有说服力。",
   [("最典型的情况是。", "'The most typical case is...'", "typical（典型的）"),
    ("打个比方更有画面。", "'For instance' paints a picture.", "for instance（举例来说）")]),
  ("核心在于", "The Core Is", "00:24", "讲重点用「核心在于」「真正厉害的是」，把信息密度拉满，一句话顶三句。",
   [("核心在于更精准。", "'The core is' hits the point.", "core（核心）"),
    ("一句话顶三句。", "One sentence does the work of three.", "dense（信息密集的）")]),
 ],
),
]

def paraphrase_for(sentences):
    out = []
    for zh, en, note in sentences:
        word = note.split("（")[0].strip()
        out.append([f"用{word}换一种说法", en])
    return out

def main():
    for slug, title, title_en, duration, topic, url, scenes in V:
        data = {
            "meta": {
                "slug": slug, "title": title, "title_en": title_en,
                "duration": duration, "scenes": len(scenes),
                "sentences": sum(len(s[4]) for s in scenes),
                "date": DATE, "platform": PLATFORM, "source_url": url, "topic": topic,
            },
            "scene_imgs": [f"shot-{i+1:02d}" for i in range(len(scenes))],
            "scenes": [],
        }
        for i, (tc, te, t, ctx, sents) in enumerate(scenes, 1):
            data["scenes"].append({
                "id": f"s{i}", "title_cn": tc, "title_en": te, "time": t,
                "context": ctx,
                "sentences": [list(s) for s in sents],
                "paraphrase": paraphrase_for(sents),
                "speak": " ".join(en for _, en, _ in sents),
            })
        data["practice"] = []
        data["pitfalls"] = []
        data["shifts"] = []
        data["difficult_words"] = []
        data["footer_notes"] = f"来源：{title}（小红书，时长{duration}）"
        p = OUT / f"{slug}.json"
        p.write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"✓ {slug} {len(scenes)} scenes")

if __name__ == "__main__":
    main()
