#!/usr/bin/env python3
"""b35 JSON 生成脚本：摄影/相机/脸型混合类（10篇）"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "scripts" / "scene-data"
OUT.mkdir(parents=True, exist_ok=True)

DATE = "2026-08-08"
PLATFORM = "xiaohongshu"

V = [
(
 "sony-rx1riii-hands-on", "顶配画质的口袋机：索尼RX1RIII上手测试！", "Sony RX1R III: Top-Tier Image Quality in a Pocket", "3分22秒", "摄影 · 相机评测", "http://xhslink.cn/o/6BT5M55iPgW",
 [
  ("开场：小钢炮登场", "Opening: A Tiny Powerhouse", "00:00", "小小的机身里塞进一块超强处理器，索尼把相机做小是一生的执念。",
   [("小小的机身塞进超强处理器。", "A tiny body packs a mighty processor.", "mighty（强大的）"),
    ("索尼对把相机做小有执念。", "Sony is obsessed with making cameras small.", "obsessed（执着的）")]),
  ("RX1 系列历史", "The RX1 Legacy", "00:16", "2012年发布第一代大黑卡RX1之后备受好评，第二年追加高像素版RX1R，这一等就是十多年。",
   [("第一代黑卡备受好评。", "The first RX1 was well received.", "well received（备受好评）"),
    ("这一等就是十多年。", "Then we waited over a decade.", "decade（十年）")]),
  ("6100万像素顶配", "61MP of Resolution", "00:42", "6100万像素顶配不可更换镜头相机，塞进和A7R5同款顶流CMOS，却焊死卡口配蔡司35F2。",
   [("这是6100万像素的顶配。", "It packs a top-tier 61-megapixel sensor.", "megapixel（百万像素）"),
    ("搭配蔡司35F2定焦镜头。", "It pairs with a fixed Zeiss 35mm f/2 lens.", "fixed lens（固定镜头）")]),
  ("三点结论：画质", "Conclusion 1: Image Quality", "01:14", "35毫米焦段拥有目前最顶级全画幅画质，裁切到70mm仍有1500万像素可用画质。",
   [("35mm焦段画质顶级。", "At 35mm, the quality is class-leading.", "class-leading（顶级的）"),
    ("裁切到70mm依然可用。", "Cropped to 70mm, it still holds up.", "crop（裁切）")]),
  ("三点结论：性能", "Conclusion 2: Performance", "01:57", "搭载BIONZ XR处理器和AI芯片，运行速度、自动对焦、视频规格都是顶流。",
   [("搭载BIONZ XR处理器。", "It runs on the BIONZ XR processor.", "processor（处理器）"),
    ("自动对焦和视频规格顶流。", "Autofocus and video specs are top-tier.", "autofocus（自动对焦）")]),
  ("三点结论：特定化", "Conclusion 3: A Specialized Tool", "02:28", "更像是全画幅规格下最好的特定化产品：微距焦段、UHS-II卡槽、PD快充、FL系列色彩。",
   [("这是一台特定化产品。", "It's a highly specialized tool.", "specialized（特定的）"),
    ("支持UHS-II和PD快充。", "It supports UHS-II cards and PD charging.", "PD charging（PD充电）")]),
  ("续航短板", "The Battery Catch", "02:49", "极端高画质模式下续航顶不住，出门要带三块电池才安心。",
   [("高画质模式续航顶不住。", "Battery life struggles in high-quality mode.", "battery life（续航）"),
    ("出门要带三块电池。", "You need three batteries to feel safe.", "spare batteries（备用电池）")]),
  ("总结：取舍鲜明", "Summary: Clear Trade-offs", "03:03", "498克机身里拥有顶级画质，但要接受不可换镜头的现实，选择它的都不是寻常之辈。",
   [("498克机身拥有顶级画质。", "Top-tier quality in a 498-gram body.", "gram（克）"),
    ("选择它的都不是泛泛之辈。", "Those who pick it know exactly what they want.", "know what they want（目标明确）")]),
 ],
),
(
 "desk-product-filming", "短视频带货、代拍素材、拍摄技巧、桌拍", "Short-Video Product Filming: Desk Shoot Skills", "43秒", "摄影 · 带货拍摄", "http://xhslink.cn/o/6eYZ6H0NpwI",
 [
  ("开场：镜头方向", "Opening: Camera Direction", "00:00", "不要这样拿相机，要学会有活动感地转动，避免画面死板。",
   [("不要这样拿相机。", "Don't hold the camera like this.", "hold the camera（持机）"),
    ("要学会有活动感地转动。", "Learn to move with a lively feel.", "lively（生动的）")]),
  ("避免撞头", "Avoid a Jerky Swing", "00:05", "拿的时候不要这样，会撞到头、晃动镜头，要让动作顺滑。",
   [("这样拿会撞到头。", "Holding it like this makes it swing.", "swing（晃动）"),
    ("要让动作更顺滑。", "Make the motion smoother.", "smooth（顺滑的）")]),
  ("上手展示拉高手机", "Raise the Phone", "00:12", "拍上手展示时不要把产品拍得粗大，要拉高手机找画面的延伸。",
   [("上手展示别拍得粗大。", "Don't make the product look huge.", "huge（巨大的）"),
    ("拉高手机找画面延伸。", "Raise the phone to extend the composition.", "composition（构图）")]),
  ("转动手腕", "Turn, Don't Pan", "00:21", "转动的时候不要用手机画圈，很生硬；要先放再后推，动作有节奏。",
   [("不要用手机画圈。", "Don't circle the phone around.", "circle（绕圈）"),
    ("先放再后推更有节奏。", "Pull back slowly for better rhythm.", "rhythm（节奏）")]),
  ("翻转产品", "Flip the Product", "00:27", "拍平平挂挂的产品时不要干拍，要学会把产品翻转过来看，展示不同面。",
   [("学会翻转产品来拍。", "Learn to flip the product over.", "flip（翻转）"),
    ("展示不同的面。", "Show every side of it.", "every side（每一面）")]),
  ("指点有节奏", "Point with Rhythm", "00:34", "指点的时候不要没节奏地乱点，可以转、可以停，配合画面重心。",
   [("指点要有节奏。", "Point with rhythm, not randomly.", "randomly（随意地）"),
    ("配合画面的重心。", "Match the visual center of the frame.", "visual center（视觉重心）")]),
 ],
),
(
 "cotton-25l-photo-backpack", "一体快挂+悬浮背负 COTTON 25L 摄影双肩包", "COTTON 25L Photo Backpack: Quick-Draw + Floating Back", "8分56秒", "摄影 · 装备评测", "http://xhslink.cn/o/3I4MfVW3UFV",
 [
  ("开场：快装开箱", "Opening: Quick-Draw Unboxing", "00:00", "把相机转过来放进快装底座，手机轻松放进去，这是一个上锁状态。",
   [("相机转过来快速放入。", "Turn the camera and drop it in.", "quick-draw（快装）"),
    ("装入后自动上锁。", "It locks into place automatically.", "lock（上锁）")]),
  ("25升的尺寸", "The 25-Liter Size", "00:13", "外包装扁平，25升不是特别大的尺寸，但自家快装系统非常好用。",
   [("25升不是特别大。", "25 liters isn't a huge size.", "liter（升）"),
    ("自家快装系统好用。", "Its own quick-draw system shines.", "system（系统）")]),
  ("软壳与腰带", "Soft Shell and Hip Belt", "00:28", "原生的原型快装底座，腰带比较软、没有硬型框架塑形，这个位置预留了快装位。",
   [("腰带比较柔软。", "The hip belt is quite soft.", "hip belt（腰带）"),
    ("预留了快装位。", "A quick-draw slot is reserved here.", "reserved（预留的）")]),
  ("两侧袋与材质", "Side Pockets", "00:41", "一边是防雨袋且内部是硬的，另一边是收缩的水袋或太阳眼镜袋，上标网格材质内里泡棉。",
   [("一侧是硬质防雨袋。", "One side holds a stiff rain cover.", "rain cover（防雨罩）"),
    ("另一侧是网格水袋。", "The other side is a mesh bottle pocket.", "mesh（网格）")]),
  ("悬浮背板", "Floating Back Panel", "01:05", "背板是悬浮型的、里侧镂空，肩带可做背长调节，多个挡位适应不同背长。",
   [("背板是悬浮型的。", "The back panel floats off the pack.", "floating（悬浮的）"),
    ("肩带可调节背长。", "Straps adjust to different torso lengths.", "torso length（背长）")]),
  ("金属框架", "Metal Frame", "01:29", "内部有金属框架支撑，底部也有金属框架，下面还配有防雨罩。",
   [("内部有金属框架。", "There's a metal frame inside.", "metal frame（金属框架）"),
    ("底部同样有支撑。", "The bottom has support too.", "support（支撑）")]),
  ("正面挂点", "Front Attachment Points", "01:46", "正面带鼠舱和网袋拓展，两边有挂点，可以挂登山杖或DIY头盔网练。",
   [("正面有网袋拓展。", "The front has mesh expansion.", "expansion（扩展）"),
    ("两边挂点很灵活。", "Side lash points are versatile.", "versatile（多用途的）")]),
  ("背负与散热", "Carry and Ventilation", "02:18", "悬浮背框让包体微微拗起，背负感和散热更好，缺点是网内侵占包体空间。",
   [("悬浮背框散热更好。", "The floating frame ventilates better.", "ventilate（通风）"),
    ("缺点占一点包内空间。", "The downside: it eats into inner space.", "downside（缺点）")]),
 ],
),
(
 "lighting-texture-layers", "轻风格质感，灯光质感的三个层次和两个细节", "Lighting Texture: Three Layers and Two Details", "2分13秒", "设计 · 灯光设计", "http://xhslink.cn/o/4MPY6lPURHa",
 [
  ("开场：灯光决定质感", "Opening: Light Defines Texture", "00:00", "同样的房子，差的只是灯光：一开灯全亮，但没有强弱冷暖重点，质感全被均匀白光盖过去。",
   [("同样房子差的只是灯光。", "Same room, the only difference is light.", "difference（差别）"),
    ("均匀白光盖过一切质感。", "Even white light washes out all texture.", "wash out（盖过）")]),
  ("照明方式的转变", "A Change of Lighting", "00:09", "同样的空间，照明方式一变，立刻变得高级有质感。",
   [("照明方式一变就高级。", "Change the lighting, and it turns upscale.", "upscale（高级的）"),
    ("灯光是空间的灵魂。", "Light is the soul of a space.", "soul（灵魂）")]),
  ("层次一：基础照明", "Layer 1: Base Lighting", "00:34", "基础照明只是空间的底色，能看清地面和家具就行，作用是让你自由走动。",
   [("基础照明是空间底色。", "Base lighting is the room's backdrop.", "backdrop（底色）"),
    ("能看清地面和家具就行。", "Just enough to see the floor and furniture.", "furniture（家具）")]),
  ("层次二：功能照明", "Layer 2: Task Lighting", "00:50", "沙发旁看书光线不够、厨房切菜被影子挡住，都是缺了功能照明，哪里需要就照哪里。",
   [("功能照明精准解决需求。", "Task lighting solves specific needs.", "task lighting（功能照明）"),
    ("哪里需要就照哪里。", "Light exactly where you need it.", "precisely（精准地）")]),
  ("层次三：氛围照明", "Layer 3: Ambience", "01:11", "氛围照明才是轻风格高级感的核心，墙角落地灯、床头台灯、柜体内嵌灯，点位越低越柔和。",
   [("氛围光是高级感的核心。", "Ambient light is the heart of that high-end feel.", "ambient light（氛围光）"),
    ("点位越低光线越柔和。", "Lower light points feel softer.", "softer（更柔和的）")]),
  ("细节一：色温", "Detail 1: Color Temperature", "01:37", "不同色温带来不同情绪状态，像一天中太阳的色温变化，有条件一定要选可调色温的。",
   [("色温决定情绪状态。", "Color temperature sets the mood.", "color temperature（色温）"),
    ("选可调色温的款式。", "Pick fixtures with adjustable temperature.", "adjustable（可调节的）")]),
  ("细节二：显色性", "Detail 2: Color Rendering", "01:50", "太阳光显色性Ra100，高显色光源通常Ra约等于95，能更好还原事物本来的颜色。",
   [("显色指数接近太阳光。", "A high CRI brings colors to life.", "CRI（显色指数）"),
    ("还原事物本来的颜色。", "It renders true-to-life colors.", "render（还原）")]),
  ("总结：花钱在细节", "Summary: Invest in the Invisible", "02:01", "基础光打亮空间、功能光解决问题、氛围光调出情绪，把钱花在看不见的细节上。",
   [("基础光功能光氛围光。", "Base light, task light, and mood light.", "mood（情绪）"),
    ("把钱花在细节上。", "Spend on the details you can't see.", "invisible（看不见的）")]),
 ],
),
(
 "face-type-midline", "你属于哪种脸型", "Which Face Type Are You", "24秒", "审美 · 脸型分析", "http://xhslink.cn/o/9jGam2G5oqg",
 [
  ("开场：幼态脸", "Opening: The Youthful Face", "00:00", "这是幼态脸：上庭大于中庭，三停比例约1:1:0.8，可爱又无害，少女感直接拉满。",
   [("上庭大于中庭。", "The forehead is larger than the mid-face.", "forehead（额头）"),
    ("可爱又无害。", "Cute and harmless.", "harmless（无害的）")]),
  ("幼态脸的比例", "Youthful Proportions", "00:02", "三停比例约1:1:0.8，可爱又无害，少女感直接拉满。",
   [("三停比例约1比1比0.8。", "The third-proportion is about 1:1:0.8.", "proportion（比例）"),
    ("少女感直接拉满。", "Girlish charm is off the charts.", "girlish（少女的）")]),
  ("标准脸", "The Balanced Face", "00:07", "这是标准脸，三停比例1:1:1，不算一眼惊艳，但耐看又不出错。",
   [("三停比例一比一比一。", "The thirds are an even 1:1:1.", "even（均匀的）"),
    ("耐看又不出错。", "Pleasant to look at and never off.", "pleasant（令人愉悦的）")]),
  ("成熟脸", "The Mature Face", "00:12", "这是成熟脸，中庭偏长，三停比例1:1.2:1，典型的御姐范。",
   [("中庭偏长。", "The mid-face is longer.", "mid-face（中庭）"),
    ("典型的御姐范。", "A classic sultry style.", "sultry（御姐气质的）")]),
  ("长脸庭脸", "The Long-Triangle Face", "00:17", "这是长脸庭脸，三停比例1:1.2，稳重有力量，还带着知性魅力。",
   [("三停比例约1比1.2。", "The ratio is about 1:1.2.", "ratio（比例）"),
    ("稳重有知性魅力。", "Steady, with intellectual charm.", "intellectual（知性的）")]),
  ("测测你的脸型", "Find Your Own Type", "00:22", "快来测测你属于哪种：对着镜子看三停比例，就知道自己的脸型类型。",
   [("快来测测你属于哪种。", "Find out which type you are.", "find out（找出）"),
    ("看三停比例就能判断。", "Your thirds reveal your face type.", "reveal（揭示）")]),
 ],
),
(
 "lumix-l10-vs-x100", "相机测试Lumix L10 对比 Fujifilm X100", "Lumix L10 vs Fujifilm X100: A Real-World Test", "8分46秒", "摄影 · 相机对比", "http://xhslink.cn/o/AePuCaKbXNu",
 [
  ("开场：两台相机", "Opening: Two Cameras", "00:00", "摄影师朱利亚将Fujifilm X100与Lumix L10进行实际对比拍摄测试，两者都是轻便日常旅行相机。",
   [("对两台相机进行实测。", "Put two cameras to a real-world test.", "real-world（真实的）"),
    ("两者定位都是轻便旅行机。", "Both are light travel companions.", "companion（伴侣）")]),
  ("传感器规格", "Sensor Specs", "00:07", "富士是APS-C画幅约4000万像素配35mmF2定焦，Lumix是M4/3约2000万像素配24-75mm变焦。",
   [("富士APS-C四千万像素。", "Fuji: APS-C with about 40MP.", "APS-C（半画幅）"),
    ("Lumix M4/3配变焦镜头。", "Lumix: M4/3 with a zoom lens.", "zoom lens（变焦镜头）")]),
  ("画幅与进光量", "Sensor Size and Light", "00:39", "传感器越大进光量越多，低光下画面更干净、背景虚化更好、整体画质更高。",
   [("传感器越大进光越多。", "Bigger sensors gather more light.", "gather light（进光）"),
    ("低光下画质更干净。", "Cleaner shots in low light.", "low light（低光）")]),
  ("定焦vs变焦", "Prime vs Zoom", "01:13", "富士固定35mm无法光学变焦，Lumix从24mm广角延伸到75mm中长焦，构图灵活性明显更高。",
   [("富士是固定焦段。", "The Fuji is fixed at 35mm.", "fixed（固定的）"),
    ("Lumix有24到75变焦。", "The Lumix zooms from 24 to 75mm.", "zoom（变焦）")]),
  ("高像素裁切", "Crop Flexibility", "01:43", "富士凭4000万像素可裁切模拟35/50/70mm焦段，但本质是数字裁切会让文件变小。",
   [("高像素可裁切换焦段。", "High resolution allows cropping to other focal lengths.", "crop（裁切）"),
    ("数字裁切文件变小。", "Digital crops shrink the file.", "digital（数字的）")]),
  ("变焦体验与创作", "Zoom Feel and Creativity", "02:23", "Lumix变焦波杆更顺手不晃动，但定焦迫使摄影师移动身体构图，拍摄更有意识。",
   [("变焦波杆操作更顺手。", "The zoom lever feels more natural.", "lever（波杆）"),
    ("定焦强迫你移动构图。", "A prime forces you to move and compose.", "compose（构图）")]),
  ("对焦表现", "Autofocus Performance", "03:47", "Lumix对焦反应更快更稳、人物识别几乎持续开启，富士偶尔错焦甚至随机失焦。",
   [("Lumix对焦又快又稳。", "The Lumix autofocus is fast and steady.", "steady（稳定的）"),
    ("富士偶尔会错焦。", "The Fuji occasionally misses focus.", "miss focus（失焦）")]),
  ("色彩系统", "Color Systems", "04:46", "富士以胶片模拟著称，Lumix提供实时LUT且可叠加，色彩自由度上Lumix更灵活。",
   [("富士有胶片模拟。", "Fuji is famous for film simulations.", "film simulation（胶片模拟）"),
    ("Lumix可导入自定义LUT。", "Lumix imports custom LUTs.", "LUT（色彩查找表）")]),
  ("视频与总结", "Video and Verdict", "07:18", "富士最高6.2K、Lumix最高5.6K无裁切；富士偏向高像素定焦创作，Lumix偏向变焦灵活与视频。",
   [("两台相机视频能力都强。", "Both cameras are strong in video.", "video capability（视频能力）"),
    ("选择取决于你的风格。", "The choice depends on your style.", "depend on（取决于）")]),
 ],
),
(
 "feel-not-pretty-reason", "为什么你总觉得自己不好看的原因找到了！", "Why You Think You Look Bad: The Real Reasons", "13秒", "审美 · 面部分析", "http://xhslink.cn/o/5dnupv1kYAA",
 [
  ("抿嘴测法令纹", "Press Your Lips: Nasolabial Fold Test", "00:00", "开场动作指令：把嘴抿上，如果法令纹消失了，可能是鼻基底凹陷。",
   [("把嘴抿上。", "Press your lips together.", "press（按压）"),
    ("法令纹消失可能是鼻基底凹陷。", "Folds gone? It may be a sunken nose base.", "nasolabial fold（法令纹）")]),
  ("眼睛上看的测试", "Look Up: Eye Muscle Test", "00:03", "第二组动作：眼睛睁大往上看，如果眉毛看起来飞起，可能是眼肌无力。",
   [("眼睛睁大往上看。", "Open the eyes wide and look up.", "look up（往上看）"),
    ("眉毛飞起可能是眼肌无力。", "Brows flying up may mean weak eye muscles.", "weak eye muscles（眼肌无力）")]),
  ("戴眼镜测山根", "Glasses: The Nasal Bridge Test", "00:05", "戴眼镜如果不太好看，说明山根塌，眼镜承托不住。",
   [("戴眼镜不太好看。", "You don't look great in glasses.", "glasses（眼镜）"),
    ("说明山根塌。", "It shows a low nasal bridge.", "nasal bridge（山根）")]),
  ("近看测脸型", "Close-Up: Flat-Face Test", "00:08", "近看比远看好看，属于扁平脸，立体度不足。",
   [("近看比远看好看。", "You look better up close than far away.", "up close（近看）"),
    ("属于扁平脸。", "That means a flat face.", "flat face（扁平脸）")]),
  ("侧脸测比例", "Profile: Proportion Test", "00:10", "侧脸比正脸好看，是面部比例有问题，正侧面对比最明显。",
   [("侧脸比正脸好看。", "You look better in profile than head-on.", "profile（侧脸）"),
    ("是面部比例的问题。", "It's a facial-proportion issue.", "proportion（比例）")]),
 ],
),
(
 "photo-smile-looks-good", "拍照❌“笑纹”尴尬，其实笑好看很简单", "Smiling in Photos: It's Easy to Look Good", "1分58秒", "审美 · 笑容练习", "http://xhslink.cn/o/94LzStJPMEm",
 [
  ("开场：法令纹与笑", "Opening: Folds and Smiles", "00:00", "如果拍照是法令纹最简单的解决方式，那也一定是打光，但不可能时刻带着灯，那就让法令纹变得合理——笑起来。",
   [("拍照是最简单的解决方式。", "Photography is the simplest fix.", "simplest（最简单的）"),
    ("让法令纹变得合理。", "Make the folds look intentional.", "intentional（合理的）")]),
  ("笑让法令纹合理", "Smiling Justifies the Folds", "00:16", "不笑的时候法令纹很凸显，一旦笑它的存在就变得合理，比一味抹平法令纹更耐看好看。",
   [("不笑时法令纹凸显。", "The folds stand out when you don't smile.", "stand out（凸显）"),
    ("笑起来反而更耐看。", "Smiling makes them more attractive.", "attractive（有吸引力的）")]),
  ("镜框练习法", "The Frame Trick", "00:29", "教大家一个方法：戴一个镜框去笑，找到苹果肌顶到镜框下面的感觉。",
   [("戴一个镜框去练习。", "Practice with a pair of glasses frames.", "frames（镜框）"),
    ("苹果肌顶到镜框下面。", "Feel the apples push against the frame.", "cheek apples（苹果肌）")]),
  ("嘴角发力顶苹果肌", "Lift the Cheek Apples", "00:40", "通过嘴角的发力把苹果肌顶出来，脸显垮源于内沟和法令纹，而它们又源于苹果肌下垂。",
   [("用嘴角把苹果肌顶出来。", "Push the cheek apples up with the mouth corners.", "mouth corners（嘴角）"),
    ("苹果肌下垂导致显垮。", "Drooping cheek apples cause the sag.", "sag（下垂）")]),
  ("牙齿不咬合", "Keep Teeth Apart", "01:03", "方圆脸多半嘴身不合，嘴巴千万不能咬合着笑，无论是否露齿牙齿都不能咬紧，要分开。",
   [("方圆脸嘴身多半不合。", "Round faces often have tense mouths.", "tense（紧绷的）"),
    ("牙齿不能咬紧要分开。", "Keep your teeth apart, not clenched.", "clench（咬紧）")]),
  ("完整动作流程", "The Full Sequence", "01:14", "先用嘴角顶起苹果肌靠近镜框，牙齿不咬合，下颌找到发力的感觉并伸出来。",
   [("用嘴角顶起苹果肌。", "Lift the cheek apples with the mouth corners.", "lift（上提）"),
    ("下颌要伸出来发力。", "Extend the jaw and engage.", "jaw（下颌）")]),
  ("眼睛展开", "Open the Eyes", "01:37", "如果还是觉得笑得很尴尬，先把嘴巴笑起来，再把眼睛展开，就会得到完美笑容。",
   [("先笑嘴巴再展眼睛。", "Smile first, then open the eyes.", "open the eyes（睁眼）"),
    ("你就得到完美笑容。", "You get a perfect smile.", "perfect（完美的）")]),
 ],
),
(
 "fangyuan-23-face-angle", "方圆脸出片角度？“2/3脸”太权威了！", "Round-Face Angles: The Two-Thirds Profile", "2分42秒", "审美 · 拍照角度", "http://xhslink.cn/o/3C3whhGPlky",
 [
  ("开场：方圆脸不难拍", "Opening: Round Faces Are Easy", "00:00", "其实方圆脸拍照一点都不难，只要你找到正确的角度，而且不需要搭子很会拍，自己会找角度就行。",
   [("方圆脸拍照不难。", "Round faces are not hard to shoot.", "round face（方圆脸）"),
    ("关键是自己会找角度。", "The key is finding your own angle.", "angle（角度）")]),
  ("为什么侧脸不好看", "Why Profile Shots Flop", "00:14", "你听过很多博主说方圆脸要拍侧脸，但你拍的侧脸就是不好看，因为你没找到自己真正好看的角度。",
   [("侧脸不一定适合你。", "Profiles may not suit you.", "profile（侧脸）"),
    ("要找自己真正好看的角度。", "Find the angle that truly flatters you.", "flatter（衬托）")]),
  ("镜子录视频自测", "Self-Test in the Mirror", "00:26", "用手机对着镜子录一段视频，这相当于别人给你拍照后置的真实效果。",
   [("对镜子录一段视频。", "Record a video into the mirror.", "mirror（镜子）"),
    ("这就是别人眼里的你。", "That's how others actually see you.", "how others see you（别人的视角）")]),
  ("左脸抬头更好看", "Left Side: Look Up", "00:51", "录完后发现左脸不适合三分之二侧脸（这块会很大），但左脸抬头就会好看很多。",
   [("左脸不适合2/3侧脸。", "My left side doesn't suit the 2/3 profile.", "two-thirds profile（三分之二侧脸）"),
    ("左脸抬头更好看。", "Looking up flatters my left side.", "look up（抬头）")]),
  ("右脸适合2/3侧脸", "Right Side: The Sweet Spot", "01:04", "右脸更小一点，比较适合三分之二侧脸，无论抬头低头都好看，侧脸也OK。",
   [("右脸适合2/3侧脸。", "My right side suits the 2/3 profile.", "sweet spot（最佳位置）"),
    ("抬头低头都好看。", "Looks good tilted up or down.", "tilt（倾斜）")]),
  ("鼻子不高的选2/3", "Flat Noses: Go Two-Thirds", "01:12", "鼻子高度不够的话纯侧脸会整个脸内凹，多去尝试三分之二侧脸，鼻子不会显得很矮。",
   [("鼻梁不高别拍纯侧脸。", "A low nose flattens in a pure profile.", "pure profile（纯侧脸）"),
    ("2/3侧脸更修饰鼻子。", "The 2/3 profile flatters the nose.", "flatter（修饰）")]),
  ("手机垂直地面", "Keep the Phone Vertical", "01:53", "让朋友的手机尽量垂直于地面，镜头高度跟下巴一样高，这个角度不容易形成畸变。",
   [("手机垂直于地面。", "Keep the phone perpendicular to the ground.", "perpendicular（垂直的）"),
    ("镜头与下巴同高。", "Lens height matches your chin.", "chin（下巴）")]),
  ("俯仰角度的应对", "Handle High and Low Angles", "02:08", "镜头前倾就手抬高蹲低拍俯视角度，镜头上仰就侧脸抬头不看镜头，90%出片。",
   [("俯拍显脸小。", "Shooting from above slims the face.", "from above（俯拍）"),
    ("镜头仰就侧脸抬头。", "If the lens tilts up, tilt your face up too.", "tilt up（上仰）")]),
 ],
),
(
 "ai-photo-real-3-tips", "AI太假？3招去掉“塑料感”秒变真实照片", "Make AI Photos Look Real: 3 Prompt Tricks", "1分27秒", "摄影 · AI 图像", "http://xhslink.cn/o/5rME68lDOe8",
 [
  ("开场：提示词太干净", "Opening: Prompts Too Clean", "00:00", "为什么AI做的图总能看出是AI？其实不是模型不行，很多时候是你的提示词太干净了。",
   [("AI图一眼就能看出来。", "AI images are easy to spot.", "spot（识破）"),
    ("提示词太干净是主因。", "Overly clean prompts are the culprit.", "culprit（元凶）")]),
  ("技巧一：加光源", "Tip 1: Add a Light Source", "00:16", "很多AI人物假，是因为整张脸被光照得太均匀，现实里的光一定有方向、明暗、高光和阴影。",
   [("整张脸被光照得太均匀。", "The face is lit too evenly.", "evenly（均匀地）"),
    ("现实光有方向和明暗。", "Real light has direction, highlights, and shadows.", "highlights and shadows（明暗）")]),
  ("给人物明确光源", "Give the Subject Direction", "00:30", "提示词里加上对光影的描述，人物一旦有了明确光源，就不会像贴在背景上一样。",
   [("提示词加光影描述。", "Add light-and-shadow words to the prompt.", "prompt（提示词）"),
    ("人物不再像贴在背景上。", "The subject no longer looks pasted on.", "pasted on（贴上去的）")]),
  ("技巧二：加皮肤细节", "Tip 2: Add Skin Detail", "00:34", "AI脸最容易假的地方是五官和皮肤太完美、有塑料感，提示词里可以加轻微瑕疵。",
   [("皮肤太完美有塑料感。", "Too-perfect skin looks plastic.", "plastic look（塑料感）"),
    ("加轻微瑕疵更真实。", "Minor imperfections add realism.", "imperfections（瑕疵）")]),
  ("技巧三：加前景", "Tip 3: Add Foreground", "00:46", "真实照片是镜头在真实空间里捕捉人物，加上前景遮挡和中景清晰、前景虚化更真实。",
   [("真实照片有前景遮挡。", "Real photos have foreground occlusion.", "occlusion（遮挡）"),
    ("前景虚化更有层次。", "Blurred foreground adds depth.", "depth（层次）")]),
  ("遮挡关系与总结", "Occlusion and Summary", "01:00", "书架边缘、玻璃反光这些遮挡关系让画面更像真实街拍，而不是AI生成的图片。",
   [("书架和玻璃反光更真实。", "Bookshelves and glass reflections read as real.", "reflection（反光）"),
    ("记这三类提示词让AI不像AI。", "Use these prompts to make AI undetectable.", "undetectable（难以分辨的）")]),
 ],
),
]

def paraphrase_for(sentences):
    out = []
    for zh, en, note in sentences:
        word = note.split("（")[0].strip()
        out.append([f"用{word}换一种说法", en])
    return out

def main():
    for slug, title, title_en, duration, topic, url, scenes in V:
        data = {
            "meta": {
                "slug": slug, "title": title, "title_en": title_en,
                "duration": duration, "scenes": len(scenes),
                "sentences": sum(len(s[4]) for s in scenes),
                "date": DATE, "platform": PLATFORM, "source_url": url, "topic": topic,
            },
            "scene_imgs": [f"shot-{i+1:02d}" for i in range(len(scenes))],
            "scenes": [],
        }
        for i, (tc, te, t, ctx, sents) in enumerate(scenes, 1):
            data["scenes"].append({
                "id": f"s{i}", "title_cn": tc, "title_en": te, "time": t,
                "context": ctx,
                "sentences": [list(s) for s in sents],
                "paraphrase": paraphrase_for(sents),
                "speak": " ".join(en for _, en, _ in sents),
            })
        data["practice"] = []
        data["pitfalls"] = []
        data["shifts"] = []
        data["difficult_words"] = []
        data["footer_notes"] = f"来源：{title}（小红书，时长{duration}）"
        p = OUT / f"{slug}.json"
        p.write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"✓ {slug} {len(scenes)} scenes")

if __name__ == "__main__":
    main()
