#!/usr/bin/env python3
"""b34 JSON 生成脚本：服装穿搭/选购知识类（10篇）"""
import json, os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "scripts" / "scene-data"
OUT.mkdir(parents=True, exist_ok=True)

DATE = "2026-08-08"
PLATFORM = "xiaohongshu"

# (title, title_en, duration, topic, url, scenes=[(title_cn, title_en, time, context, sentences=[(zh, en, note)])])
V = [
(
 "original-vs-retouch", "原图VS精修：小姐姐底子很好，稍稍修一点更精致", "From Original to Retouch: a Little Goes a Long Way", "1分44秒", "摄影 · 人像精修", "http://xhslink.cn/o/370KoiLi0Fn",
 [
  ("开场：锚点贴下颌线", "Opening: Anchor Along the Jaw", "00:01", "蓝色锚点路径贴着下颌线移动，为轮廓选择或修整做准备。修图第一步是锁定需要调整的区域。",
   [("蓝色锚点路径贴着下颌线。", "A blue anchor path hugs the jawline.", "anchor path（锚点路径）"),
    ("准备做轮廓相关选择或修整。", "Ready for contour-related selection or retouching.", "retouching（精修）")]),
  ("3D 模式总览", "The 3D-Mode Overview", "00:05", "红底、白蕾丝裙与头纱、俯视表情一并入镜，先从整体看画面再动手。",
   [("3D 模式里整体审视画面。", "The 3D mode gives an overall view.", "overall view（整体视角）"),
    ("红底白裙头纱一起入镜。", "Red backdrop, white dress and veil in one shot.", "in one shot（同框）")]),
  ("颈部横纹清理", "Cleaning Up Neck Lines", "00:10", "颈部横纹被圈选，扩散=5，准备做局部清理或生成式修补。细碎瑕疵要局部处理。",
   [("颈部横纹被圈选出来。", "The neck's horizontal lines are selected.", "select（圈选）"),
    ("用局部清理或生成式修补。", "Use local cleanup or generative healing.", "generative healing（生成式修补）")]),
  ("液化与变形网格", "The Liquify Grid", "00:15", "液化/变形网格压在颊颌上，微调脸型轮廓。「颜值修图」水印可见。",
   [("液化网格压在脸颊上。", "A liquify grid presses over the cheek and jaw.", "liquify（液化）"),
    ("微调脸型轮廓线条。", "Gently refine the face contour.", "contour（轮廓）")]),
  ("钢笔路径精准选择", "Pen Path Precise Selection", "00:30", "钢笔路径落在蕾丝与捧花附近，继续做精准选择。复杂边缘靠钢笔抠图。",
   [("钢笔路径落在蕾丝附近。", "The pen path lands near the lace and bouquet.", "pen path（钢笔路径）"),
    ("继续做精准的选择。", "Continue the precise selection.", "precise（精准的）")]),
  ("肤质修复笔刷", "Skin-Texture Repair Brush", "00:50", "左侧工具条齐全，圆形笔刷落在颈部，做肤质修复。笔刷修复让皮肤更均匀。",
   [("圆形笔刷落在颈部。", "A round brush works on the neck.", "brush（笔刷）"),
    ("做肤质修复处理。", "Repairing the skin texture.", "skin texture（肤质）")]),
  ("选择并遮住视图", "Select and Mask", "01:10", "「选择并遮住」视图：检查全身轮廓与边缘是否干净。这一步决定抠图边缘质量。",
   [("选择并遮住视图。", "The Select and Mask view.", "Select and Mask（选择并遮住）"),
    ("检查轮廓边缘是否干净。", "Check if the outline edges are clean.", "outline（轮廓）")]),
  ("额头碎发清理", "Stray Forehead Hairs", "01:30", "额头散落发丝被圈选，扩散=5，继续做细碎清理。碎发清理让画面更干净。",
   [("额头碎发被圈选。", "Stray forehead hairs are selected.", "stray hairs（碎发）"),
    ("继续做细碎的清理。", "Continuing the fine cleanup.", "fine cleanup（细碎清理）")]),
 ],
),
(
 "uniqlo-airism-sweat-tips", "夏天衣服这么挑，轻松摆脱汗湿汗臭的社交尴尬", "How to Pick Summer Clothes and Avoid Sweat Embarrassment", "2分59秒", "穿搭 · 面料科普", "http://xhslink.cn/o/1M8RfLOavJJ",
 [
  ("开场：出汗尴尬", "Opening: Sweat Embarrassment", "00:00", "夏天太热，一出汗衣服直接贴身上，腋下后背汗湿一片甚至出汗味。选对面料才能避免这些尴尬。",
   [("一出汗衣服就贴在身上。", "Clothes stick to your skin the moment you sweat.", "stick to（贴住）"),
    ("如何避免汗湿汗臭的尴尬。", "How to avoid the awkwardness of sweat stains and odor.", "sweat stains（汗渍）")]),
  ("铜氨纤维的原理", "The Cupro Fiber", "00:09", "真丝太贵，粘胶排汗性能差一点，推荐铜氨纤维：原料是优质棉籽绒，制成纺丝液再凝固纺丝。",
   [("铜氨纤维又叫铜氨丝。", "Cupro fiber is also called ammonia silk.", "cupro（铜氨纤维）"),
    ("它既有粘胶的吸湿性又有丝的排汗性。", "It combines the absorbency of rayon with the breathability of silk.", "absorbency（吸湿性）")]),
  ("面料手感", "The Fabric Feel", "00:26", "整体摸上去冰冰凉凉、非常丝滑，加上有一定紧致感，能起到速干效果。",
   [("摸上去冰冰凉凉很丝滑。", "It feels cool and silky to the touch.", "silky（丝滑的）"),
    ("有一定紧致感能速干。", "A bit of firmness helps it dry fast.", "dry fast（速干）")]),
  ("轻薄通透", "Thin and Breathable", "00:45", "这种面料轻薄通透，运动穿、当内搭、甚至当睡衣穿都很合适。",
   [("它轻薄又通透。", "It is thin and breathable.", "breathable（透气的）"),
    ("运动、内搭、睡衣都合适。", "Great for workouts, layering, or pajamas.", "layering（叠穿内搭）")]),
  ("经典款与速干", "The Classic Quick-Dry Tee", "01:01", "经典款的纤维系统只有头发丝的十分之一，能快速把汗液导到面料上层蒸发掉。",
   [("纤维只有头发丝的十分之一细。", "The fiber is a tenth the width of a human hair.", "fiber（纤维）"),
    ("快速导汗并蒸发掉。", "Wicks sweat quickly and lets it evaporate.", "wick（导汗）")]),
  ("消臭网眼款", "The Deodorizing Mesh", "01:33", "纤维自带消臭功能，能快速消解汗臭味，久洗久穿依然保持效果。",
   [("纤维自带消臭功能。", "The fiber has built-in deodorizing.", "deodorizing（消臭）"),
    ("久洗久穿依然有效。", "It stays effective wash after wash.", "effective（有效的）")]),
  ("棉混纺挺阔款", "The Cotton-Blend Option", "01:48", "想要挺阔一些就选棉混纺款，加了61%的棉，厚度刚刚好，可直接穿出门。",
   [("加了61%的棉更挺阔。", "61% cotton makes it a bit more structured.", "structured（挺阔的）"),
    ("可以直接穿出门。", "You can wear it out on its own.", "on its own（单穿）")]),
  ("压胶工艺与总结", "Seamless Finish and Summary", "02:06", "内裤全是压胶工艺、没有走线，弹性大不勒、不夹屁股不卷边；AIRism 主打吸汗速干消臭凉感顺滑。",
   [("压胶工艺没有任何走线。", "The bonded seams mean no visible stitching.", "bonded seams（压胶接缝）"),
    ("主打吸汗速干消臭凉感。", "It focuses on wicking, quick-dry, deodorizing, and coolness.", "quick-dry（速干）")]),
 ],
),
(
 "tight-vs-loose-slim", "抠抠搜搜又热又显胖，大大方方自在又显瘦", "Tight and Stuffy, or Loose and Slim", "49秒", "穿搭 · 版型选择", "http://xhslink.cn/o/8bz12b7UZI7",
 [
  ("开场：松紧对比", "Opening: Tight vs Loose", "00:00", "抠抠搜搜（紧身）显胖，大大方方（宽松）显瘦。同一个身材，版型不同效果完全不同。",
   [("紧身显胖，宽松显瘦。", "Tight looks bigger; loose looks slimmer.", "tight / loose（紧身 / 宽松）"),
    ("同一身材版型不同效果不同。", "The same body reads differently in different cuts.", "cut（版型）")]),
  ("小圆领的问题", "The Small Round Neck", "00:05", "抠抠搜搜的小圆领，露肤度低、又热，还显得脖子粗。",
   [("小圆领露肤度低。", "A small round neck shows little skin.", "neckline（领口）"),
    ("又热又显得脖子粗。", "It feels hot and makes the neck look thick.", "look thick（显得粗）")]),
  ("正肩大领型", "Structured Shoulders, Open Neck", "00:10", "正肩大圆领、正肩大V领、正肩方领，露肤度高、凉快又显瘦。",
   [("正肩配大领型更透气。", "Structured shoulders with an open neckline breathe better.", "structured shoulders（正肩）"),
    ("露肤度高、凉快又显瘦。", "More skin, cooler and slimmer.", "slimming（显瘦的）")]),
  ("纱向不同的隐患", "Mismatched Grain", "00:18", "现在看着是平的，多次水洗之后就会形成鼓包或跑出来，因为上下纱向不同、缩率方向不同。",
   [("多次水洗后会出现鼓包。", "Puckering appears after many washes.", "puckering（起皱鼓包）"),
    ("纱向不同缩率就不同。", "Different grain directions shrink differently.", "grain direction（纱向）")]),
  ("选纱向一致的", "Pick a Consistent Grain", "00:27", "去选择纱向一样的，后期就不容易出现这些问题。",
   [("选纱向一致的布料。", "Choose fabric with a consistent grain.", "consistent（一致的）"),
    ("后期就不容易出问题。", "Fewer problems later on.", "later on（后期）")]),
  ("速干酷感", "The Quick-Dry Look", "00:29", "速干裤尤其适合夏天，选择透气面料穿着更舒适。",
   [("速干裤是夏天的好选择。", "Quick-dry pants are a summer pick.", "quick-dry pants（速干裤）"),
    ("透气面料更舒适。", "Breathable fabric feels more comfortable.", "comfortable（舒适的）")]),
  ("薄如纸的面料", "Paper-Thin Fabric", "00:38", "这种面料薄如纸，摸上去有沙沙的声音，穿着时声音明显。",
   [("面料薄得像纸一样。", "The fabric is as thin as paper.", "as thin as paper（薄如纸）"),
    ("摸上去有沙沙的声响。", "It rustles when you touch it.", "rustle（沙沙声）")]),
  ("出汗后的尴尬", "Sweat Shows Through", "00:45", "这种轻薄面料一出汗透色度就会升高，尴尬程度看图自行感受。",
   [("一出汗透色度就升高。", "Once you sweat, it becomes see-through.", "see-through（透色的）"),
    ("看图自行感受。", "Look at the picture and see for yourself.", "for yourself（亲身体会）")]),
 ],
),
(
 "linen-ramie-hemp-diff", "亚麻苎麻汉麻什么区别？怎么选？怎么养护？", "Linen, Ramie, and Hemp: How to Choose and Care", "2分01秒", "面料 · 麻类科普", "http://xhslink.cn/o/FvqOzXKWy7",
 [
  ("开场：三种麻", "Opening: Three Kinds of Hemp", "00:00", "亚麻、苎麻、汉麻什么区别？怎么选？以及该怎么养护？",
   [("亚麻苎麻汉麻有什么区别。", "What's the difference between linen, ramie, and hemp?", "linen / ramie / hemp（亚麻 / 苎麻 / 汉麻）"),
    ("怎么选以及怎么养护。", "How to choose and how to care for them.", "care for（养护）")]),
  ("亚麻的产地与价格", "Linen's Origin and Price", "00:04", "亚麻85%产自法国比利时荷兰等，主要依赖进口，所以价格偏高。",
   [("亚麻主要依赖进口。", "Linen is mostly imported.", "imported（进口的）"),
    ("所以价格偏高。", "That's why it costs more.", "pricy（偏贵的）")]),
  ("亚麻的竹节纹理", "Linen's Slub Texture", "00:10", "亚麻纤维有明显竹节纹理，第一次穿稍硬挺，敏感肌可能有点扎，但越洗越柔软。",
   [("亚麻有明显的竹节纹理。", "Linen has a distinct slub texture.", "slub（竹节纱）"),
    ("它会越洗越柔软。", "It gets softer with every wash.", "softer（更柔软）")]),
  ("亚麻的缩水率", "Linen's Shrinkage", "00:23", "亚麻缩水率是所有麻类里最高的，买亚麻衣服买大不买小，或买做过洗水工艺处理的。",
   [("亚麻缩水率最高。", "Linen shrinks the most of all hemp fabrics.", "shrink（缩水）"),
    ("买大不买小。", "Size up rather than down.", "size up（买大一码）")]),
  ("苎麻的性价比", "Ramie's Value", "00:38", "苎麻主要产自中国，产量大加工容易，是所有麻类里最便宜的；纤维最细最长，吸湿散热最好、缩水率最低。",
   [("苎麻是所有麻里最便宜的。", "Ramie is the cheapest of the three.", "cheapest（最便宜的）"),
    ("纤维最细，吸湿散热最好。", "Its fibers are finest, with the best breathability.", "breathability（透气性）")]),
  ("苎麻的扎刺感", "Ramie's Stiffness", "01:01", "纤维又细又长反而更硬挺，是所有麻里上身穿扎感最强的。",
   [("纤维细长反而更硬挺。", "Fine long fibers are actually stiffer.", "stiff（硬挺的）"),
    ("上身穿扎感最强。", "It feels the prickliest against the skin.", "prickly（扎人的）")]),
  ("汉麻的舒适度", "Hemp's Comfort", "01:13", "汉麻80%产自中国黑龙江，产量少加工难所以最贵；单纤维短且头部钝圆，上身舒适度和抗皱性最好。",
   [("汉麻是所有麻里最贵的。", "Hemp is the priciest of all.", "priciest（最贵的）"),
    ("上身舒适度最高。", "It's the most comfortable to wear.", "comfortable（舒适的）")]),
  ("选购与养护建议", "How to Choose and Care", "01:33", "第一次尝试选亚麻（性价比最高）；重视舒适度选汉麻；重视透气防晒选苎麻。洗护就简单过下水、通风晾干、卷起来存放。",
   [("第一次尝试就选亚麻。", "Start with linen for the best value.", "value（性价比）"),
    ("通风晾干，卷起来存放。", "Air dry and store it rolled up.", "air dry（晾干）")]),
 ],
),
(
 "clothes-quality-simple", "衣服好坏分辨真的很简单", "How to Judge Clothing Quality, Simply", "58秒", "穿搭 · 版型判断", "http://xhslink.cn/o/7cTVM9SEVsx",
 [
  ("开场：看臀围放量", "Opening: Check the Hip Ease", "00:00", "半裙想知道版型好不好，侧面看臀围这块是不是向外凸出的。",
   [("半裙的版型看臀围。", "Judge a skirt by its hip area.", "hip area（臀围部位）"),
    ("侧面看是否外凸。", "Look from the side for any bulge.", "bulge（外凸）")]),
  ("下摆不外翘", "A Hem That Hangs Straight", "00:11", "好版型下摆久穿也不会往外翘，侧面看基本上是直直下来的。",
   [("下摆久穿也不外翘。", "The hem never flares out even after wear.", "flares out（外翘）"),
    ("侧面看直直地垂下来。", "From the side it hangs perfectly straight.", "hang straight（笔直垂坠）")]),
  ("臀位放量不足", "No Ease for the Hip", "00:14", "没给臀围什么放量的，就算臀再翘也能给你压平了，显得紧绷。",
   [("没给臀围留放量。", "There's no ease built in for the hip.", "ease（放量）"),
    ("臀部再翘也被压平。", "Even a curvy hip gets flattened.", "flatten（压平）")]),
  ("好版型靠省道", "Darts Make the Fit", "00:22", "人体表面凹凸不平，通过做胸省腰省，让该凸的凸该收的收，放大优点掩盖缺点才是好版型。",
   [("好版型靠胸省腰省。", "Good fit comes from bust and waist darts.", "dart（省道）"),
    ("放大优点掩盖缺点。", "Highlight strengths and hide flaws.", "highlight（突出）")]),
  ("前后平的差版型", "Flat-Front Misfit", "00:33", "前后都是平的、跟张纸似的，穿身上能舒适能好看吗？",
   [("前后平得像一张纸。", "It's flat as a sheet of paper.", "flat（平板的）"),
    ("穿身上能好看吗。", "How can it look good on a body?", "look good（好看）")]),
  ("最差的半裙", "The Worst Skirt", "00:38", "最差的半裙前后跟一片似的，腰头松紧带一收，这不叫半裙，叫腰围放大器。",
   [("腰头松紧带一收。", "An elastic waistband that cinches everything.", "elastic waistband（松紧腰头）"),
    ("这简直是个腰围放大器。", "It's basically a waist magnifier.", "magnifier（放大器）")]),
  ("多片结构的半裙", "Multi-Panel Skirts", "00:42", "半裙选多片结构的，通过结构做出大小对比，腰部平整不鼓囊，显得腰细。",
   [("选多片结构的半裙。", "Choose a multi-panel skirt.", "multi-panel（多片）"),
    ("腰部平整显得腰细。", "A flat waistband makes the waist look small.", "waist（腰部）")]),
  ("细节与总结", "Details and Summary", "00:50", "好衣服的细节靠做工与结构，面料颜色与缝线呼应，整体才会显高级。",
   [("缝线颜色与面料呼应。", "Thread color matches the fabric.", "matching（呼应）"),
    ("细节决定高级感。", "Details make the difference.", "details（细节）")]),
 ],
),
(
 "bust-size-outfit-tips", "胸大胸小别乱穿，这样选合适又有气质", "Pick the Right Fit Whether Your Bust Is Big or Small", "47秒", "穿搭 · 胸部版型", "http://xhslink.cn/o/CwgOltrw56",
 [
  ("开场：胸型与衣服", "Opening: Bust Size and Fit", "00:00", "有的衣服只能小胸穿，有的只能大胸穿，有的大小胸都可以穿。选对版型才显气质。",
   [("有些衣服只能小胸穿。", "Some tops only work for a small bust.", "small bust（小胸）"),
    ("选对版型才显气质。", "The right fit brings out your style.", "fit（版型）")]),
  ("带胸背的包容性小", "Tight Chest Panels", "00:04", "这种带胸背的包容性比较小，手一掐左右只有一公分对折量。",
   [("带胸背的包容性很小。", "This chest panel leaves little room.", "chest panel（胸背）"),
    ("左右只有一公分的对折量。", "There's only a centimeter of ease on each side.", "centimeter（厘米）")]),
  ("对折量与罩杯", "Ease and Cup Size", "00:12", "对折量小就只能是A杯或小B杯穿，再丰满点就穿不了；左右捏不出量的只能A杯穿。",
   [("这种量只能A杯或小B杯穿。", "That ease only fits an A or small B cup.", "cup size（罩杯）"),
    ("再丰满一点就穿不进去。", "Anything fuller won't fit.", "fuller（更丰满的）")]),
  ("大胸选对折量充足的", "Big Busts Need Room", "00:20", "胸大的，比如B以上去选这种，侧面看凸出来很多、左右对折量很充足。",
   [("B罩杯以上选这种。", "B cups and up should pick this style.", "B cups（B罩杯）"),
    ("左右对折量很充足。", "There's plenty of ease on both sides.", "plenty of ease（充足放量）")]),
  ("小胸穿大胸款", "Small Bust, Big Top", "00:31", "这种大胸款就不适合小胸穿，小胸穿它这一块都是空的。",
   [("小胸穿这一块是空的。", "A small bust leaves this area empty.", "empty（空荡的）"),
    ("大胸款不适合小胸。", "Big-bust styles don't suit a small bust.", "suit（适合）")]),
  ("碎折设计", "Gathered Darts", "00:34", "这种大小胸穿都可以，因为胸上围捏了小碎折、胸下围也是，中间背折的量足够多。",
   [("胸上围捏了小碎折。", "The top gathers into small pleats.", "gathers（碎褶）"),
    ("中间背折的量足够多。", "There's plenty of ease across the chest.", "ease（余量）")]),
  ("小胸显大", "Adds Shape for Small Busts", "00:40", "小胸穿这一块整体小气折，小胸显大；大胸中间这个折量就全部顶开，也美观舒适。",
   [("小胸穿上会显大一些。", "It adds shape to a smaller bust.", "add shape（显轮廓）"),
    ("大胸穿也能顶开不紧绷。", "A bigger bust opens the folds without strain.", "without strain（不紧绷）")]),
  ("大小胸都能穿得舒适", "Comfort for Every Bust", "00:43", "大胸中间这个折量全部顶开，既美观又舒适；选对版型，大小胸都能穿出气质。",
   [("大胸的折量全部顶开。", "A larger bust opens up all the gathers.", "gathers（碎褶）"),
    ("既美观又舒适。", "It looks good and feels comfortable.", "comfortable（舒适的）")]),
 ],
),
(
 "clothing-luxury-details", "「显贵」一定不能错过的细节", "Details That Make Clothes Look Expensive", "51秒", "穿搭 · 高级细节", "http://xhslink.cn/o/YnHl9IM0Zc",
 [
  ("开场：凤尾针", "Opening: The Feather Stitch", "00:00", "只要看到这种针脚，那衣服的价格肯定不便宜，这种叫凤尾针。",
   [("看到这种针脚价格就不便宜。", "This kind of stitching signals a high price.", "stitching（针脚）"),
    ("这种叫凤尾针。", "It's called a feather stitch.", "feather stitch（凤尾针）")]),
  ("手工缝制", "Hand Stitching", "00:04", "凤尾针原来多用在旗袍上起固定作用，只能手工缝制，现在多用在这种左右拼接上。",
   [("凤尾针只能手工缝制。", "Feather stitching can only be done by hand.", "by hand（手工）"),
    ("现在用于左右拼接。", "Now it's used for side seams.", "side seam（侧缝）")]),
  ("浮雕大提花", "The Embossed Brocade", "00:16", "表面花纹非常立体、像浮雕式的就叫浮雕大提花，这种工艺相对复杂，价格不会太便宜。",
   [("花纹立体像浮雕。", "The pattern is raised like a relief.", "raised pattern（浮雕花纹）"),
    ("工艺复杂价格不便宜。", "Complex craftsmanship costs more.", "craftsmanship（工艺）")]),
  ("抗皱性好", "Great Wrinkle Resistance", "00:25", "这种面料除了立体感，最大的优点就是抗皱性非常好。",
   [("立体感强是它的优点。", "Great dimension is one of its strengths.", "dimension（立体感）"),
    ("抗皱性非常好。", "It has excellent wrinkle resistance.", "wrinkle-resistant（抗皱的）")]),
  ("长裙选斜裁面料", "Bias-Cut Gowns", "00:29", "长裙一定要选斜裁面料，瘦点胖点都可以穿，没有紧绷感、包容性更好、垂坠感更好。",
   [("长裙要选斜裁面料。", "Choose bias-cut fabric for long gowns.", "bias-cut（斜裁的）"),
    ("包容性好垂坠感也好。", "More forgiving, with a better drape.", "drape（垂坠感）")]),
  ("流苏工艺", "The Fringe Detail", "00:38", "这种叫流苏工艺，是先将面料做出流苏，再在上面加上固定的线，做出流动感。",
   [("这种叫流苏工艺。", "This is called a fringe technique.", "fringe（流苏）"),
    ("为了增加立体度与层次感。", "It adds dimension and layers of depth.", "layers of depth（层次感）")]),
  ("让裙子不单调", "Beating the Bland", "00:45", "流苏让白裙子没有那么单调，买这种裙子为的是设计感。",
   [("让白裙子不单调。", "It keeps a white dress from looking plain.", "plain（单调的）"),
    ("买裙子就是为设计买单。", "You're paying for the design.", "design（设计）")]),
  ("细节决定「显贵」", "Details That Read Expensive", "00:49", "凤尾针、浮雕提花、斜裁、流苏，这些细节叠加起来，衣服自然显得贵气。",
   [("细节叠起来显得贵气。", "Layered details read as expensive.", "read as（看起来像）"),
    ("工艺复杂度决定价格。", "Craft complexity drives the price.", "complexity（复杂度）")]),
 ],
),
(
 "clothing-quality-myths", "分享一些大家买衣服最容易误解的高品质", "Quality Myths People Misread in Clothing", "1分14秒", "穿搭 · 质量误区", "http://xhslink.cn/o/ALq9cllbvUB",
 [
  ("开场：后开衩放量", "Opening: Back-Slit Ease", "00:00", "后开衩上面这一块堆叠的量不是没做好，是故意留的活动量，方便穿脱和抬手臂。",
   [("堆叠的量是故意留的。", "That fold is deliberately added.", "deliberately（故意地）"),
    ("是穿脱抬手臂的活动量。", "It's ease for dressing and raising your arms.", "ease（活动量）")]),
  ("牛角扣的纹理", "The Horn-Button Grain", "00:12", "裤子上白色一小长条不是残品，这是牛角扣的纹理，真正的牛角扣找不到完全一样的两粒。",
   [("这不是残次品。", "It's not a defective item.", "defective（有瑕疵的）"),
    ("真正的牛角扣纹理都不同。", "Real horn buttons each have a unique grain.", "unique grain（独特纹理）")]),
  ("麻结是什么", "What Are Slubs", "00:26", "亚麻衣服上的小结是麻结，相当于天然纤维亚麻的身份证，因为亚麻纤维短粗，纺纱难以完全均匀。",
   [("麻结是亚麻的身份证。", "Slubs are linen's identity card.", "slub（麻结）"),
    ("纤维短粗难以完全均匀。", "Short coarse fibers can't spin evenly.", "coarse（粗的）")]),
  ("不要剪麻结", "Don't Cut the Slubs", "00:38", "麻结千万千万不要剪，剪了容易导致纤维断裂破洞。",
   [("千万不要去剪麻结。", "Never cut the slubs off.", "never（千万别）"),
    ("剪了容易纤维断裂破洞。", "Cutting them causes breaks and holes.", "tear（破损）")]),
  ("格子对齐的例外", "The Plaid Exception", "00:42", "格子衣服必须对齐，但合体的省道处不对齐才是合理正常的，因为剪开缝进去就会歪斜。",
   [("格子必须对齐。", "Plaid must be matched.", "matched（对齐）"),
    ("省道处不对齐反而正常。", "Misalignment at darts is actually correct.", "dart（省道）")]),
  ("男装合体格子", "Tailored Plaid for Men", "00:54", "男装合体的格子衣服也是一样，所有正肩的衣服要看里布的结构。",
   [("男装合体格子也同理。", "The same applies to tailored men's plaid.", "tailored（合体的）"),
    ("要留意里布的结构。", "Pay attention to the inner structure.", "inner structure（里布结构）")]),
  ("里布的隐藏放量", "Hidden Ease in the Lining", "00:57", "后中这一块有隐藏放量，包括下摆也是必须有的，这不是里布没烫好。",
   [("后中有隐藏放量。", "The center back has hidden ease.", "hidden ease（隐藏放量）"),
    ("这是必须的工艺。", "It's a necessary construction.", "necessary（必需的）")]),
  ("放量的作用", "Why the Ease Matters", "01:06", "如果没有这个放量，伸胳膊抬手臂都会受到阻碍。",
   [("没有放量会受阻碍。", "Without ease, movement is restricted.", "restricted（受限的）"),
    ("伸胳膊抬手臂都要顺畅。", "You need full range when reaching and lifting.", "range of motion（活动范围）")]),
 ],
),
(
 "big-face-bazi-bangs", "大脸女生 八字刘海", "Face-Framing Curtain Bangs for Round Faces", "6分49秒", "美发 · 八字刘海", "http://xhslink.cn/o/1mwmdILHKgY",
 [
  ("开场：找露白处", "Opening: Find the Thin Spot", "00:00", "先从找到露白（发量少透头皮）的地方开始，往这边抠一点出来，确定修剪的起点。",
   [("先找到露白的地方。", "First find the thin spot.", "thin spot（露白处）"),
    ("从这里抠一点头发出来。", "Pull a little hair out from here.", "pull out（抠出）")]),
  ("盖住露白", "Cover the Thin Spot", "00:09", "把前面抠下来的头发再往前梳，就能盖住露白的地方，露出度立刻改善。",
   [("把头发往前梳盖住。", "Comb it forward to cover the spot.", "comb forward（往前梳）"),
    ("露白立刻就看不到了。", "The thin spot disappears right away.", "disappear（消失）")]),
  ("修剪延长线", "Trim Along the Hairline", "00:30", "把露白处的延长线修下来，再往上一点、再抠一点，控制层次与过渡。",
   [("顺着延长线修剪。", "Trim along the extension of the hairline.", "hairline（发际线）"),
    ("再往上一点调整层次。", "Go a bit higher to adjust the layers.", "layers（层次）")]),
  ("刀立起来刮发", "Scissor Technique", "00:59", "刮的时候刀不要压头皮，让刀刃立起来往前划，这样才不会损伤发根。",
   [("刀刃立起来往前划。", "Keep the blade upright and glide forward.", "blade（刀刃）"),
    ("不要把刀压着头皮。", "Don't press the scissors against the scalp.", "scalp（头皮）")]),
  ("额角消失", "Soften the Temples", "01:07", "刮完之后这一块多余的肉感就消失了，额角变柔和，脸型立刻有变化。",
   [("多余的肉感消失了。", "The heaviness disappears.", "heaviness（厚重感）"),
    ("额角变得柔和。", "The temple area looks softer.", "temple（额角）")]),
  ("定位鼻子的那一束", "Frame the Nose", "01:23", "把这一束头发拉到鼻子那里定位长度，八字刘海的发束要在鼻翼附近最修饰脸型。",
   [("把发束拉到鼻子定位。", "Pull the section down to the nose to set length.", "set the length（定长度）"),
    ("这一束在鼻翼附近最好看。", "This piece frames best around the nose.", "frame（修饰）")]),
  ("中分与分区", "Part and Section", "01:51", "把后面都散开，中分后翻一个三角往前梳，分出左右两侧的修饰发束。",
   [("中分后分出三角区。", "Part in the middle and section a triangle.", "part（分缝）"),
    ("把发束往前梳走。", "Sweep the sections forward.", "sweep（拂动）")]),
  ("完成与效果", "The Finished Look", "03:03", "低点头、微微往后扳一点，把脸颊两侧的发量收进来，大脸立刻显小。",
   [("微微低头更显脸小。", "A slight tilt makes the face look smaller.", "tilt（倾斜）"),
    ("发量收进脸颊两侧。", "Sweep the hair toward the cheeks.", "cheeks（脸颊）")]),
 ],
),
(
 "clothes-quality-details", "衣服好坏分辨真的要细心！", "Judging Clothing Quality Takes a Keen Eye", "50秒", "穿搭 · 做工细节", "http://xhslink.cn/o/7kvQ1v53PPJ",
 [
  ("开场：插肩袖", "Opening: The Set-in Sleeve", "00:00", "差的好的对比，插肩袖一看版型就有问题，因为正常的肩和手臂是两个方向。",
   [("插肩袖最能看出版型。", "Set-in sleeves reveal the pattern quality.", "set-in sleeve（插肩袖）"),
    ("肩和手臂是两个方向。", "The shoulder and arm go in different directions.", "directions（方向）")]),
  ("斜向单方向的问题", "The Diagonal-Only Problem", "00:05", "这种只有斜向一个方向，但手臂多数情况是放下来的，肩部就亮（松弛）太多了，又丑又不舒服。",
   [("只有斜向一个方向。", "It only supports one diagonal direction.", "diagonal（斜向的）"),
    ("肩部松垮又丑又不舒服。", "The shoulder gapes—ugly and uncomfortable.", "gape（松垮张开）")]),
  ("好版型的省位", "The Dart Placement", "00:18", "同样是插肩袖，好版型只在肩的位置捏了个省，上身以后省位正好在肩和手臂的转折点上。",
   [("好版型在肩位捏省。", "Good patterns dart at the shoulder.", "dart（省道）"),
    ("省位正好在转折点上。", "The dart sits right at the shoulder pivot.", "pivot（转折点）")]),
  ("腋下无余量", "Clean Underarm", "00:30", "关键是腋下没有太多的量，整体更贴合肩部和手臂，更舒适美观。",
   [("腋下没有多余的量。", "No excess fabric under the arm.", "excess fabric（多余面料）"),
    ("整体贴合肩和手臂。", "It hugs the shoulder and arm nicely.", "hug（贴合）")]),
  ("无袖T恤认内里贴衬", "Lined Sleeveless Tees", "00:34", "无袖T恤认准这种内里有贴衬的，洗衣机里随便洗，穿到破洞都不会变形。",
   [("认准内里有贴衬的。", "Look for a lined inner finish.", "lined（有内衬的）"),
    ("洗到破洞也不变形。", "It won't lose shape even after heavy washing.", "lose shape（变形）")]),
  ("折回锁边要避开", "Avoid the Folded-Hem", "00:41", "如果看到面料折回锁边压线的直接屏蔽，这种工艺洗几次就容易出问题。",
   [("看到折回锁边直接避开。", "Skip anything with a folded, lockstitched hem.", "lockstitch（锁边）"),
    ("这种工艺经不起折腾。", "That finish won't survive much wear.", "finish（工艺处理）")]),
  ("手撑就变形", "Warps at a Touch", "00:45", "这种衣服你用手撑几下可能就变形没法看了，赶紧走，小心被碰瓷。",
   [("用手撑几下就变形。", "A couple of tugs and it's ruined.", "ruined（毁坏）"),
    ("赶紧走，小心被碰瓷。", "Walk away before you get burned.", "walk away（走开）")]),
  ("细心分辨", "A Keen Eye for Quality", "00:48", "衣服好坏分辨真的要细心：看版型、看内衬、看锁边，一眼就能避开雷区。",
   [("分辨衣服好坏要细心。", "Judging quality takes a keen eye.", "keen eye（敏锐的眼力）"),
    ("看版型、内衬和锁边。", "Check the cut, the lining, and the hem.", "hem（锁边）")]),
 ],
),
]

def paraphrase_for(sentences):
    """从句子生成 paraphrase：[[意图 -> 换说法, chunk · chunk], ...]"""
    out = []
    for zh, en, note in sentences:
        word = note.split("（")[0].strip()
        alt = en
        out.append([f"用{word}换一种说法", en])
    return out

def main():
    for slug, title, title_en, duration, topic, url, scenes in V:
        data = {
            "meta": {
                "slug": slug,
                "title": title,
                "title_en": title_en,
                "duration": duration,
                "scenes": len(scenes),
                "sentences": sum(len(s[4]) for s in scenes),
                "date": DATE,
                "platform": PLATFORM,
                "source_url": url,
                "topic": topic,
            },
            "scene_imgs": [f"shot-{i+1:02d}" for i in range(len(scenes))],
            "scenes": [],
        }
        for i, (tc, te, t, ctx, sents) in enumerate(scenes, 1):
            data["scenes"].append({
                "id": f"s{i}",
                "title_cn": tc,
                "title_en": te,
                "time": t,
                "context": ctx,
                "sentences": [list(s) for s in sents],
                "paraphrase": paraphrase_for(sents),
                "speak": " ".join(en for _, en, _ in sents),
            })
        # 占位字段，由 fix 脚本补全
        data["practice"] = []
        data["pitfalls"] = []
        data["shifts"] = []
        data["difficult_words"] = []
        data["footer_notes"] = f"来源：{title}（小红书，时长{duration}）"
        p = OUT / f"{slug}.json"
        p.write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"✓ {slug} {len(scenes)} scenes")

if __name__ == "__main__":
    main()
