#!/usr/bin/env python3
"""b40 JSON 生成脚本：帽子/修图/电影心理学混合类（10篇）"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "scripts" / "scene-data"
OUT.mkdir(parents=True, exist_ok=True)

DATE = "2026-08-08"
PLATFORM = "xiaohongshu"

V = [
(
 "star-hat-slim-face", "戴明星同款帽子享小脸人生！！这帽型抄对了", "Copy the Star Hat Shape for a Slimmer Face", "27秒", "穿搭 · 帽型选款", "http://xhslink.cn/o/5HYwK5Fpo3R",
 [
  ("开场：明星戴帽", "Opening: Stars in Caps", "00:00", "开场用舞蹈室侧影提出问题：明星戴棒球帽为何不露全脸仍显好看？",
   [("明星戴帽不露全脸。", "Stars wear caps without showing their faces.", "cap（棒球帽）"),
    ("一眼觉得是美女。", "They instantly look beautiful.", "beautiful（漂亮的）")]),
  ("普通人踩雷", "Why Ordinary People Fail", "00:04", "咱们普通人没有精致脸型，戴普通棒球帽容易踩雷，显脸大。",
   [("普通人容易踩雷。", "Ordinary faces often get it wrong.", "ordinary（普通的）"),
    ("显脸大不好看。", "It makes the face look bigger.", "bigger（更大的）")]),
  ("普通人视角", "The Ordinary-Person View", "00:05", "主讲人先把自己放进「普通人」一侧，强调没有精致的建模脸，更容易踩雷。",
   [("先承认是普通人。", "She claims the ordinary side first.", "ordinary（普通的）"),
    ("没有精致脸型。", "No finely modeled face.", "modeled（建模的）")]),
  ("侧面暴露颧骨", "The Side Profile Reveal", "00:08", "普通帽子线头大显脸大，侧面还暴露全骨颧骨下颌，更不好看。",
   [("侧面暴露颧骨。", "The side shows the cheekbones.", "cheekbone（颧骨）"),
    ("下颌线条也暴露。", "The jawline shows too.", "jawline（下颌线）")]),
  ("升级帽型", "The Upgraded Shape", "00:11", "一定要试试这款升级棒球帽，上脸直接氛围感拉满。",
   [("升级帽型氛围感拉满。", "The upgraded shape maxes out the vibe.", "upgraded（升级的）"),
    ("上脸立刻变好看。", "It instantly flatters the face.", "flatter（修饰）")]),
  ("帽檐加宽", "The Wider Brim", "00:15", "帽檐比常规款加宽不少，能更好地遮住颧骨和下颌，显得脸小。",
   [("帽檐更宽。", "The brim is wider.", "brim（帽檐）"),
    ("遮住颧骨显脸小。", "It hides the cheekbones and slims.", "hide（遮住）")]),
  ("加深帽深", "Deeper Crown", "00:19", "加深帽深贴合耳部，清晰侧脸线条，头包脸的效果更明显。",
   [("加深帽深贴合耳部。", "A deeper crown hugs the ears.", "crown（帽顶）"),
    ("侧脸线条更清晰。", "The profile looks cleaner.", "profile（侧脸）")]),
  ("明星同款效果", "The Star Effect", "00:22", "就算不是天生上镜脸，也能轻松戴着明星同款头包脸效果。",
   [("不是上镜脸也能戴。", "Even non-photogenic faces can wear it.", "photogenic（上镜的）"),
    ("头包脸效果轻松get。", "Get the head-wrapping-face look.", "head-wrapping（头包脸）")]),
 ],
),
(
 "photo-atmosphere-fix", "画面脏/照片缺少氛围？", "Muddy Photos? Here's the Color Logic", "44秒", "摄影 · 调色逻辑", "http://xhslink.cn/o/6DjiCccTbLc",
 [
  ("开场：红黄蓝", "Opening: RGB and Beyond", "00:00", "为什么减少红色水会变得通透？减少青色和蓝色就能调出氛围。",
   [("减少红色变通透。", "Less red looks clearer.", "clear（通透的）"),
    ("减青减蓝出氛围。", "Cutting cyan and blue builds mood.", "cyan（青色）")]),
  ("三原色互补", "The Complementary Pairs", "00:05", "今天我们学习调色逻辑：把三原色红绿蓝两两混合，得到互补色青品黄。",
   [("两两混合得互补色。", "Pairing primaries gives complements.", "complementary（互补色）"),
    ("红绿蓝是原色。", "Red, green, blue are the primaries.", "primary（原色）")]),
  ("互补叠加变脏", "Complement Mixing Mud", "00:10", "互补色叠加时只要一方明度不是一百，就会导致画面发灰变脏。",
   [("互补叠加会变脏。", "Complement pairs can muddy the shot.", "muddy（变脏）"),
    ("明度不足就发灰。", "Low brightness turns it grey.", "grey（灰）")]),
  ("减红水变通透", "Cut the Red Cast", "00:18", "所以减少夹杂在青色里的红色水，画面就会变得更通透。",
   [("青色里的红是脏源。", "Red in cyan is the dirt.", "cast（色偏）"),
    ("减红就通透。", "Removing it clears the image.", "remove（移除）")]),
  ("冷暖色调", "Warm vs Cool", "00:22", "红色黄色洋红属于暖色，蓝色青色绿色属于冷色，冷暖决定氛围基调。",
   [("红黄洋红是暖色。", "Red, yellow, magenta are warm.", "warm（暖色）"),
    ("蓝青绿是冷色。", "Blue, cyan, green are cool.", "cool（冷色）")]),
  ("调暖调冷", "Tuning the Mood", "00:33", "想要冷调照片就减少暖色，想要暖调照片就减少冷色，这是调色总逻辑。",
   [("冷调减暖色。", "Cool shots need less warm.", "cool tone（冷调）"),
    ("暖调减冷色。", "Warm shots need less cool.", "warm tone（暖调）")]),
 ],
),
(
 "pink-wedding-photo-retouch", "为什么你修的粉调婚纱照又脏又廉价？", "Why Your Pink Wedding Photos Look Cheap", "1分16秒", "修图 · 粉调处理", "http://xhslink.cn/o/7eQXLyE5EeG",
 [
  ("开场：直接加粉", "Opening: Just Add Pink?", "00:00", "客户想要粉调的婚纱照，我们第一反应是不是直接给他加粉色？这样只会又闷又脏。",
   [("第一反应是加粉色。", "The instinct is to add pink.", "instinct（本能反应）"),
    ("直接加只会脏。", "That only makes it muddy.", "muddy（脏的）")]),
  ("粉调≠粉色", "Pink Tone Isn't Pink", "00:06", "客户想要的不是单纯的粉色，而是整体柔和的粉色调。",
   [("要的是柔和粉调。", "What they want is a soft pink tone.", "soft（柔和的）"),
    ("不是单纯加粉。", "Not just pouring on pink.", "pour（倾泻）")]),
  ("先调通透", "First Make It Clear", "00:13", "第一步把画面调通透，选择曲线先调光感，将红绿蓝三个通道的高光提起来。",
   [("第一步调光感。", "First adjust the light.", "exposure（光感）"),
    ("提三通道高光。", "Lift highlights in all three channels.", "highlight（高光）")]),
  ("曲灰效果", "The Matte Curve", "00:26", "三色混合就通透很多，再加一点亮度，接着用曲线柔光模式做一个曲灰效果。",
   [("柔光模式做曲灰。", "Soft-light mode creates the matte.", "soft light（柔光）"),
    ("降低不透明度。", "Lower the opacity.", "opacity（不透明度）")]),
  ("去黄绿杂乱", "Clean the Yellow and Green", "00:41", "画面里的黄跟绿显得杂乱，用可选颜色选黄通道减黄色，绿通道也减黄色。",
   [("黄绿让画面杂乱。", "Yellow and green clutter the shot.", "clutter（杂乱）"),
    ("减黄让画面干净。", "Cutting yellow cleans it up.", "cut（削减）")]),
  ("高光加粉", "Pink in the Highlights", "00:52", "关键一步：选取高光，用颜色和自然饱和度工具加点粉色，再减一点色温。",
   [("在高光里加粉。", "Add pink in the highlights.", "highlights（高光）"),
    ("减色温更干净。", "Lowering temperature cleans it.", "temperature（色温）")]),
  ("柔化收尾", "Finish Soft", "01:01", "给照片加一点柔，用曲线提亮一点点，粉调才干净不廉价。",
   [("加柔让画面柔和。", "Softening smooths the image.", "soften（柔化）"),
    ("粉色婚纱照核心是通透。", "The core is clarity, not pink.", "core（核心）")]),
  ("前后对比", "Before and After", "01:08", "前后对比一目了然：左侧偏闷偏脏，右侧通透、统一、柔和粉调。",
   [("左脏右净的对比。", "The left is muddy, the right clean.", "before and after（前后对比）"),
    ("通透统一才是粉调。", "Clear and unified is the pink tone.", "unified（统一的）")]),
 ],
),
(
 "desaturation-effect-comparison", "同样是降饱合度，为什么效果完全不一样？", "Same Desaturation, Different Results", "1分22秒", "修图 · 降饱和度", "http://xhslink.cn/o/7HUpslXaOI9",
 [
  ("开场：同是降饱和", "Opening: Same Move, Different Look", "00:00", "同样是降饱和度，为什么效果完全不一样？答案在于降的是什么。",
   [("同样操作效果不同。", "Same move, different results.", "desaturation（降饱和度）"),
    ("关键看降什么。", "It's about what you reduce.", "reduce（减少）")]),
  ("全局降饱和", "Global Desaturation", "00:05", "直接拉全局饱和度，所有颜色一起变灰，画面容易显得脏且没有层次。",
   [("全局降饱和发灰。", "Global drops turn everything grey.", "global（全局的）"),
    ("画面脏没层次。", "It gets flat and muddy.", "flat（平的）")]),
  ("分区降饱和", "Targeted Desaturation", "00:12", "聪明做法是分区降饱和，把刺眼的颜色单独压下去，保留主体的鲜艳。",
   [("分区降饱和更高级。", "Targeted drops look better.", "targeted（有针对性的）"),
    ("保留主体鲜艳。", "Keep the subject vivid.", "vivid（鲜艳的）")]),
  ("降明度对比", "Also the Lightness", "00:20", "除了饱和度，明度和对比度也在变化，降饱和时配合调整明暗才有质感。",
   [("明度对比同时变。", "Lightness and contrast change too.", "lightness（明度）"),
    ("配合明暗才有质感。", "Pair it with tonal control.", "tonal（色调的）")]),
  ("色彩范围", "The Color Range", "00:30", "先选范围再降，比如只降背景、只降杂色，主体的颜色才跳得出来。",
   [("先选范围再降。", "Pick the range before dropping.", "range（范围）"),
    ("主体颜色跳出来。", "The subject then pops.", "pop（跳出）")]),
  ("饱和度拉杆", "The Saturation Slider", "00:40", "自然饱和度比饱和度更温和，它保护肤色的作用在修人像时尤其好用。",
   [("自然饱和度更温和。", "Vibrance is gentler than saturation.", "vibrance（自然饱和度）"),
    ("保护肤色不变蜡黄。", "It protects skin tones.", "skin tone（肤色）")]),
  ("风格化降饱和", "Stylized Muted Look", "00:50", "高级灰调是把饱和度降到克制但保留细节，配合对比度才是电影感。",
   [("克制降饱和高级。", "Restrained drops feel premium.", "restrained（克制的）"),
    ("配合对比出电影感。", "With contrast it reads cinematic.", "cinematic（电影感的）")]),
  ("实操对比", "Side-by-Side Practice", "01:05", "同一张照片两种降法：一张全灰、一张保留主体，效果天差地别。",
   [("两种降法对比。", "Two drops side by side.", "side by side（并排对比）"),
    ("效果天差地别。", "The results are worlds apart.", "worlds apart（天差地别）")]),
 ],
),
(
 "stephen-chow-film-psychology", "星爷电影里的心理学～", "The Psychology Inside Stephen Chow's Films", "2分43秒", "电影 · 心理学", "http://xhslink.cn/o/8uuMvjGZWES",
 [
  ("开场：星爷心理学", "Opening: Psychology in Chow's Films", "00:00", "星爷的电影不只是搞笑，里面藏着大量的心理学原理，值得细细拆解。",
   [("电影里藏心理学。", "His films hide psychology.", "psychology（心理学）"),
    ("不只是搞笑。", "Not just for laughs.", "laughs（笑点）")]),
  ("无厘头的防御", "Nonsense as Defense", "00:15", "无厘头的夸张表演，本质上是一种心理防御，用幽默掩盖真实情绪。",
   [("无厘头是防御。", "Nonsense is a defense mechanism.", "defense（防御）"),
    ("幽默掩盖情绪。", "Humor masks real feelings.", "mask（掩盖）")]),
  ("小人物共鸣", "The Everyman", "00:30", "主角永远是小人物，观众在他身上看到自己，这是投射心理在起作用。",
   [("小人物引发共鸣。", "Underdogs create resonance.", "underdog（小人物）"),
    ("观众投射自己。", "Viewers project onto him.", "project（投射）")]),
  ("夸张的愤怒", "Cartoonish Anger", "00:50", "愤怒用夸张卡通的方式表达，反而消解了攻击性，让冲突变得安全。",
   [("夸张消解攻击性。", "Exaggeration defuses aggression.", "aggression（攻击性）"),
    ("冲突变得安全。", "Conflict becomes safe.", "conflict（冲突）")]),
  ("被压抑的欲望", "Suppressed Desires", "01:10", "台词里反复出现的发财梦、逆袭梦，是被压抑欲望的替代性满足。",
   [("发财梦是替代满足。", "Get-rich dreams are substitute fulfillment.", "substitute（替代）"),
    ("被压抑的欲望。", "Suppressed desires surface.", "suppress（压抑）")]),
  ("集体记忆", "Collective Memory", "01:30", "怀旧梗和时代符号，击中一代人的集体记忆，这是共情设计。",
   [("时代符号击中集体记忆。", "Era symbols hit collective memory.", "collective memory（集体记忆）"),
    ("这是共情设计。", "It's designed empathy.", "empathy（共情）")]),
  ("结局的治愈", "The Healing Ending", "02:00", "无论过程多荒诞，结局总是温暖的，这种补偿心理给观众情绪出口。",
   [("荒诞过程温暖结局。", "Absurd means, warm ends.", "absurd（荒诞的）"),
    ("补偿心理给出口。", "Compensation gives an outlet.", "outlet（出口）")]),
  ("总结：笑里藏泪", "Summary: Laughs With Tears", "02:20", "星爷把严肃的心理学包装成笑声，笑过之后才是真正的疗愈。",
   [("笑里藏着眼泪。", "Laughter hides the tears.", "tears（眼泪）"),
    ("笑声背后是疗愈。", "Healing hides behind the laughs.", "healing（疗愈）")]),
 ],
),
(
 "protagonist-plot-armor", "剥夺主角光环与规则保护", "Stripping the Protagonist's Plot Armor", "9分30秒", "电影 · 叙事分析", "http://xhslink.cn/o/4HF7NPsknvJ",
 [
  ("开场：主角光环", "Opening: Plot Armor", "00:00", "主角光环是编剧给主角的隐性保护，今天的电影则主动剥夺这种保护。",
   [("主角光环是隐性保护。", "Plot armor is invisible protection.", "plot armor（主角光环）"),
    ("好电影主动剥夺。", "Great films strip it away.", "strip（剥夺）")]),
  ("规则保护", "Rules as Protection", "00:40", "主角不死、主角必胜是旧规则，新叙事让主角在规则内同样受伤。",
   [("旧规则是主角不死。", "Old rules: the hero never dies.", "hero（主角）"),
    ("新叙事打破规则。", "New films break the rules.", "break（打破）")]),
  ("真实的代价", "Real Consequences", "01:30", "主角为自己的选择付真实代价，受伤、失败、失去，故事才可信。",
   [("选择要付代价。", "Choices must cost something.", "cost（代价）"),
    ("失去让故事可信。", "Loss makes it believable.", "believable（可信的）")]),
  ("小人物叙事", "The Underdog Story", "02:30", "主角不再天生强大，他靠笨拙的坚持一路爬升，观众更有代入感。",
   [("主角不再天生强大。", "The hero isn't born mighty.", "mighty（强大的）"),
    ("笨拙坚持更真实。", "Clumsy persistence feels real.", "persistence（坚持）")]),
  ("反派合理化", "Humanized Villains", "04:00", "反派不再是脸谱化的恶，他们有自己的逻辑，主角光环在对抗中被消解。",
   [("反派有自己的逻辑。", "Villains have their own logic.", "villain（反派）"),
    ("对抗中消解光环。", "The armor dissolves in combat.", "dissolve（消解）")]),
  ("群像叙事", "The Ensemble", "05:00", "主角光环被分给群像，每个人物都可能是关键，故事的走向不可预测。",
   [("光环分给群像。", "The armor spreads across the cast.", "ensemble（群像）"),
    ("走向不可预测。", "The direction becomes unpredictable.", "unpredictable（不可预测的）")]),
  ("剥夺的戏剧性", "The Drama of Loss", "06:30", "剥夺主角光环本质上是在加码戏剧冲突，让每一次选择都生死攸关。",
   [("剥夺加码冲突。", "Stripping armor raises the stakes.", "stakes（赌注）"),
    ("选择生死攸关。", "Every choice becomes life or death.", "life or death（生死攸关）")]),
  ("总结：真实即力量", "Summary: Reality Is Power", "08:00", "去掉光环的主角才真正站得起来，真实本身就是最强的戏剧张力。",
   [("去掉光环才立得住。", "Armorless heroes stand tall.", "stand tall（立得住）"),
    ("真实是最大张力。", "Reality is the strongest tension.", "tension（张力）")]),
 ],
),
(
 "best-looking-movie-review", "我宣布：这是最好看的电影", "I Declare: The Best-Looking Film", "7分34秒", "电影 · 影评", "http://xhslink.cn/o/Y9NtsbmU9J",
 [
  ("开场：最好看的电影", "Opening: The Best-Looking Film", "00:00", "我宣布，这是我看过最好看的电影，好看在每一个镜头的审美。",
   [("宣布最好看的电影。", "I declare this the best-looking film.", "best-looking（最好看的）"),
    ("好看在每个镜头。", "Beauty lives in every frame.", "frame（镜头画面）")]),
  ("色彩的克制", "Restrained Color", "00:40", "全片色彩极度克制，低饱和但层次丰富，颜色不抢戏反而在叙事。",
   [("色彩克制有层次。", "Colors are restrained yet rich.", "restrained（克制的）"),
    ("颜色在参与叙事。", "Colors join the storytelling.", "storytelling（叙事）")]),
  ("光影的层次", "Light and Shadow", "01:30", "光影永远有层次，明暗之间藏着情绪，暗部也绝不是一片死黑。",
   [("光影有层次。", "Lighting always has depth.", "lighting（光影）"),
    ("暗部保留细节。", "Shadows keep their detail.", "shadow（暗部）")]),
  ("构图的呼吸", "Breathing Compositions", "02:30", "构图给画面留足呼吸空间，人物放在画面里显得刚刚好。",
   [("构图留呼吸空间。", "Compositions leave breathing room.", "breathing room（呼吸感）"),
    ("人物比例恰到好处。", "Subjects sit just right.", "proportion（比例）")]),
  ("镜头的节奏", "Rhythmic Editing", "03:30", "剪辑节奏像呼吸一样自然，长镜头不拖沓，快剪不杂乱。",
   [("剪辑节奏像呼吸。", "Editing breathes naturally.", "rhythm（节奏）"),
    ("长镜头不拖沓。", "Long takes never drag.", "drag（拖沓）")]),
  ("服化道的质感", "Craftsmanship", "04:30", "服装、道具、美术都有真实质感，细节经得起大屏幕和反复看。",
   [("服化道有质感。", "Craft details feel authentic.", "craft（工艺）"),
    ("细节经得起反复看。", "Details hold up on rewatch.", "rewatch（重看）")]),
  ("镜头里的诗意", "Poetry on Screen", "05:30", "很多镜头单独截出来就是一幅画，导演的审美在每一帧里流淌。",
   [("单帧就是一幅画。", "Every frame is a painting.", "painting（画作）"),
    ("审美在帧里流淌。", "Taste flows through each frame.", "taste（审美）")]),
  ("总结：美即表达", "Summary: Beauty Speaks", "06:30", "好看不只是视觉享受，它本身就是导演的表达，美即内容。",
   [("美本身就是表达。", "Beauty is itself expression.", "expression（表达）"),
    ("好看不止视觉享受。", "It's more than eye candy.", "eye candy（视觉享受）")]),
 ],
),
(
 "funny-old-man-to-killer", "从滑稽老伯到终极杀神", "From Funny Old Man to Ultimate Killer", "5分34秒", "电影 · 角色分析", "http://xhslink.cn/o/6wS4cFAvQki",
 [
  ("开场：反差角色", "Opening: The Contrast Character", "00:00", "一个滑稽的老伯，一个终极杀神，同一个角色的两个极端被演活了。",
   [("滑稽与杀神的反差。", "Foolish vs. killer: one man.", "contrast（反差）"),
    ("同一角色两个极端。", "Two extremes in one role.", "extreme（极端）")]),
  ("外形的伪装", "The Disguise", "00:40", "弯腰驼背、口齿不清，外形上的伪装让所有人放下戒心。",
   [("外形让人放下戒心。", "The look disarms everyone.", "disarm（解除戒心）"),
    ("驼背口齿不清。", "Hunched, mumbling, forgettable.", "hunched（驼背的）")]),
  ("细节的破绽", "The Cracks", "01:30", "导演用细节埋破绽：手部的肌肉记忆、眼神的短暂锋利，暗示真实身份。",
   [("细节埋破绽。", "Details plant the cracks.", "crack（破绽）"),
    ("眼神暴露真实。", "Eyes betray the truth.", "betray（暴露）")]),
  ("身份的切换", "The Switch", "02:30", "当伪装卸下，眼神和姿态瞬间切换，观众和角色一起被震撼。",
   [("伪装瞬间卸下。", "The disguise drops in an instant.", "disguise（伪装）"),
    ("姿态瞬间切换。", "Posture switches instantly.", "posture（姿态）")]),
  ("杀神的压迫", "Killer Presence", "03:30", "杀神状态的压迫感来自克制的动作，不多余的眼神，反而更令人恐惧。",
   [("压迫感来自克制。", "The presence comes from restraint.", "restraint（克制）"),
    ("不多余的眼神更恐惧。", "Fewer looks, more fear.", "fear（恐惧）")]),
  ("配角反衬", "The Side Character's Fear", "03:13", "配角的吞咽反应被单独捕捉，用恐惧反衬火云邪神的压制力。",
   [("配角吞咽显恐惧。", "A swallow betrays the fear.", "swallow（吞咽）"),
    ("反衬高手的压制力。", "It underlines the master's dominance.", "dominance（压制力）")]),
  ("悲情的底色", "The Tragic Core", "04:00", "角色的滑稽与杀戮背后是悲情底色，反差越大，悲剧越深。",
   [("反差越大悲剧越深。", "Bigger contrast, deeper tragedy.", "tragedy（悲剧）"),
    ("欢乐背后是悲情。", "Joy hides the sorrow.", "sorrow（悲伤）")]),
  ("总结：一体两面", "Summary: Two Sides, One Man", "05:00", "滑稽与杀神是一体两面，这才是角色的厚度，好角色都有阴影。",
   [("一体两面的角色。", "The character has two faces.", "two faces（两面）"),
    ("厚度来自阴影。", "Depth comes from shadow.", "depth（厚度）")]),
 ],
),
(
 "shaolin-soccer-audiovisual", "拆解《少林足球》视听密码", "Deconstructing Shaolin Soccer's Audiovisual Code", "6分28秒", "电影 · 视听语言", "http://xhslink.cn/o/750LVCqcotw",
 [
  ("开场：视听密码", "Opening: The Audiovisual Code", "00:00", "《少林足球》不只是一部喜剧，它的视听语言藏着周星驰的密码。",
   [("喜剧里藏视听密码。", "The comedy hides audiovisual code.", "code（密码）"),
    ("周星驰的视听风格。", "Stephen Chow's visual style.", "style（风格）")]),
  ("功夫与足球", "Kung Fu Meets Football", "00:30", "功夫与足球的嫁接，本身就是视觉创意的胜利，把不可能拍成可能。",
   [("功夫嫁接足球。", "Kung fu grafts onto football.", "graft（嫁接）"),
    ("把不可能拍成可能。", "The impossible becomes visual.", "impossible（不可能的）")]),
  ("夸张的运镜", "Exaggerated Camera", "01:30", "广角、慢动作、超低机位，运镜的夸张程度和表演的夸张是一致的。",
   [("运镜和表演一样夸张。", "Camera matches the acting's size.", "camera（运镜）"),
    ("广角慢动作拉满。", "Wide angles and slow-mo max out.", "slow motion（慢动作）")]),
  ("音效的漫画感", "Comic Sound Design", "02:30", "音效像漫画书一样夸张，出拳有声、落地有尘，声画同步增强喜剧感。",
   [("音效像漫画。", "Sound effects read like comics.", "sound effect（音效）"),
    ("声画同步强化喜剧。", "Synced sound boosts the comedy.", "sync（同步）")]),
  ("视效的奇观", "Visual Spectacle", "03:30", "飞天入地的视效把武功视觉化，观众看的是奇观，记住的是情绪。",
   [("视效把武功视觉化。", "VFX visualize the kung fu.", "VFX（视效）"),
    ("看奇观记情绪。", "Watch spectacle, remember emotion.", "spectacle（奇观）")]),
  ("草根叙事", "The Grassroots Story", "04:30", "底层小人物逆袭的叙事和夸张视听形成反差，越荒诞越热血。",
   [("小人物逆袭叙事。", "Underdogs rise from the bottom.", "underdog（草根）"),
    ("荒诞反衬热血。", "Absurdity fuels the blood.", "blood（热血）")]),
  ("喜剧的节奏", "Comic Timing", "05:30", "周星驰的节奏掌控一流，笑点永远在最准的时刻爆发，视听为之服务。",
   [("笑点踩在准点上。", "Gags land at the perfect beat.", "gag（笑点）"),
    ("视听为节奏服务。", "Sight and sound serve the timing.", "timing（节奏）")]),
  ("冷色低谷", "Cool-Toned Low Point", "05:30", "酒吧场景用冷色与近景压缩人物空间，对应大师兄的人生低谷。",
   [("冷色压缩空间。", "Cool tones tighten the space.", "cool tone（冷色）"),
    ("对应角色的低谷。", "It matches the character's low point.", "low point（低谷）")]),
 ],
),
(
 "absurd-wuxia-cinematography", "用最荒诞的镜头拍最悲壮的侠", "The Most Absurd Shots for the Most Tragic Hero", "7分41秒", "电影 · 武侠美学", "http://xhslink.cn/o/92DrcI5q6UE",
 [
  ("开场：荒诞与悲壮", "Opening: Absurdity and Tragedy", "00:00", "用最荒诞的镜头拍最悲壮的侠，视觉的玩笑与命运的无情形成对冲。",
   [("荒诞镜头拍悲壮。", "Absurd shots capture the tragic.", "absurd（荒诞的）"),
    ("玩笑与命运对冲。", "Jokes clash with fate.", "fate（命运）")]),
  ("无厘头的动作", "Absurd Action", "01:00", "武打动作无厘头到夸张，但每一次跌倒都指向真实的身体代价。",
   [("动作无厘头。", "The action is slapstick.", "slapstick（闹剧）"),
    ("跌倒指向真实代价。", "Every fall costs something real.", "fall（跌倒）")]),
  ("色调的粗粝", "Gritty Palette", "02:00", "粗粝的色调不加修饰，荒诞场景里透出真实的尘土与苦痛。",
   [("色调粗粝真实。", "The palette is gritty and raw.", "gritty（粗粝的）"),
    ("尘土里透着苦痛。", "Dust carries the pain.", "dust（尘土）")]),
  ("镜头的错位", "Off-Kilter Frames", "03:00", "歪斜构图、非常规角度，用镜头的错位表达世界的荒诞。",
   [("歪斜构图表达荒诞。", "Tilted frames say 'absurd'.", "tilted（歪斜的）"),
    ("非常规角度。", "Unconventional angles.", "unconventional（非常规的）")]),
  ("音乐的反差", "Musical Contrast", "04:00", "悲壮的配乐配着荒诞的画面，声音与画面的反差放大情绪张力。",
   [("悲壮音乐配荒诞画面。", "Solemn music meets absurdity.", "solemn（庄重的）"),
    ("反差放大张力。", "Contrast amplifies the tension.", "amplify（放大）")]),
  ("侠的悲壮", "The Hero's Sorrow", "05:00", "侠不是战无不胜的，他会在最荒诞的时刻倒下，悲壮由此而来。",
   [("侠也会倒下。", "Even heroes fall.", "fall（倒下）"),
    ("悲壮由此而来。", "That's where tragedy comes from.", "tragedy（悲壮）")]),
  ("尘土与光", "Dust and Light", "06:00", "最后镜头里，尘土落定、光重新照进来，荒诞之后是宁静的悲凉。",
   [("尘土落定光回来。", "Dust settles, light returns.", "settle（落定）"),
    ("荒诞后是悲凉。", "After absurdity, quiet sorrow.", "sorrow（悲凉）")]),
  ("白酒灭火", "Liquor and Fire", "05:54", "白酒让灭火变成加火，道具连续出错把恐惧转成身体喜剧。",
   [("白酒灭火变加火。", "Liquor turns firefighting into fueling.", "fuel（加火）"),
    ("恐惧转成身体喜剧。", "Fear becomes physical comedy.", "physical comedy（身体喜剧）")]),
 ],
),
]

def paraphrase_for(sentences):
    out = []
    for zh, en, note in sentences:
        word = note.split("（")[0].strip()
        out.append([f"用{word}换一种说法", en])
    return out

def main():
    for slug, title, title_en, duration, topic, url, scenes in V:
        data = {
            "meta": {
                "slug": slug, "title": title, "title_en": title_en,
                "duration": duration, "scenes": len(scenes),
                "sentences": sum(len(s[4]) for s in scenes),
                "date": DATE, "platform": PLATFORM, "source_url": url, "topic": topic,
            },
            "scene_imgs": [f"shot-{i+1:02d}" for i in range(len(scenes))],
            "scenes": [],
        }
        for i, (tc, te, t, ctx, sents) in enumerate(scenes, 1):
            data["scenes"].append({
                "id": f"s{i}", "title_cn": tc, "title_en": te, "time": t,
                "context": ctx,
                "sentences": [list(s) for s in sents],
                "paraphrase": paraphrase_for(sents),
                "speak": " ".join(en for _, en, _ in sents),
            })
        data["practice"] = []
        data["pitfalls"] = []
        data["shifts"] = []
        data["difficult_words"] = []
        data["footer_notes"] = f"来源：{title}（小红书，时长{duration}）"
        p = OUT / f"{slug}.json"
        p.write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"✓ {slug} {len(scenes)} scenes")

if __name__ == "__main__":
    main()
