#!/usr/bin/env python3
"""b36 JSON 生成脚本：摄影/色彩/妆容/电影拉片混合类（10篇）"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "scripts" / "scene-data"
OUT.mkdir(parents=True, exist_ok=True)

DATE = "2026-08-08"
PLATFORM = "xiaohongshu"

V = [
(
 "facial-stereo-beauty", "面部设计 五官分析 颜值", "Facial Design: What Actually Makes a Face Attractive", "14秒", "审美 · 面部立体", "http://xhslink.cn/o/5kDz6BtkuMg",
 [
  ("开场否定：双眼皮", "Opening Negation: Double Eyelids", "00:01", "开场先把「双眼皮=好看」这条常见标准拆掉，否定最容易误导人的归因。",
   [("先否定常见的标准。", "First dismantle the common standard.", "dismantle（拆掉）"),
    ("双眼皮不等于好看。", "Double eyelids don't equal pretty.", "double eyelids（双眼皮）")]),
  ("对应肯定：眼眶骨", "Matching Affirmation: The Orbital Bone", "00:02", "对应肯定：黄字标出「眼眶骨」，把重点放到眶缘体积上。",
   [("重点放到眶缘体积。", "Shift focus to the rim's volume.", "orbital rim（眶缘）"),
    ("黄字标出关键词。", "Yellow text marks the key word.", "highlight（标出）")]),
  ("侧脸否定：鼻梁", "Profile Negation: The Nose", "00:04", "侧脸否定：鼻梁高度不是本片认定的核心。",
   [("鼻梁高度不是核心。", "Nose-bridge height isn't the core.", "nose bridge（鼻梁）"),
    ("否定另一个常见归因。", "Reject another common attribution.", "attribution（归因）")]),
  ("侧脸肯定：上颌骨", "Profile Affirmation: The Maxilla", "00:05", "侧脸肯定：黄字「上颌骨」，指向中面部饱满度。",
   [("上颌骨指向中面部。", "The maxilla points to the mid-face.", "maxilla（上颌骨）"),
    ("饱满度决定立体感。", "Fullness decides the dimensionality.", "fullness（饱满度）")]),
  ("唇部否定：嘟嘟唇", "Lip Negation: Pouty Lips", "00:07", "唇部否定：不把「嘟嘟唇」当成独立答案。",
   [("嘟嘟唇不是答案。", "Pouty lips alone aren't the answer.", "pouty lips（嘟嘟唇）"),
    ("否定只看局部的思路。", "Reject the local-only mindset.", "local（局部的）")]),
  ("唇部肯定：口周", "Lip Affirmation: The Perioral Area", "00:09", "唇部肯定：黄字「口周」，强调口周区域的整体饱满。",
   [("口周整体饱满才好看。", "Perioral fullness is what reads as pretty.", "perioral（口周的）"),
    ("从局部回到整体。", "Go from the part back to the whole.", "whole（整体）")]),
  ("脸型否定：窄脸", "Face-Shape Negation: Narrow Face", "00:11", "脸型否定：窄脸不是本片的终点标准。",
   [("窄脸不是终点标准。", "A narrow face isn't the end standard.", "narrow face（窄脸）"),
    ("别把单一指标当目标。", "Don't chase a single metric.", "metric（指标）")]),
  ("收束肯定：脸型转折", "Closing Affirmation: The Face Turn", "00:13", "收束肯定：前脸/后脸转折清楚，立体感被推到前台。",
   [("前后脸转折要清楚。", "A clean front-to-side face turn.", "face turn（脸型转折）"),
    ("立体感被推到前台。", "Dimensionality is pushed to the fore.", "dimensionality（立体感）")]),
 ],
),
(
 "color-explained-clearly", "终于有人把色彩讲清楚了！", "Color, Explained Clearly at Last", "19分22秒", "摄影 · 色彩科学", "http://xhslink.cn/o/6kSSQtcOgAl",
 [
  ("开场：色彩认知史", "Opening: How We Learned Color", "00:00", "人类对色彩的描述长期停留在主观定性的层面，系统定量化描述到1920-30年代才真正开始。",
   [("色彩描述曾长期主观。", "Color description was subjective for ages.", "subjective（主观的）"),
    ("定量描述始于20世纪30年代。", "Quantification began around the 1930s.", "quantify（量化）")]),
  ("三个维度", "Three Dimensions", "01:00", "描述颜色大致是三个维度：色调——是红黄还是绿；亮度——暗到黑亮到白；饱和度——颜色有多纯。",
   [("色调决定是什么颜色。", "Hue decides what color it is.", "hue（色调）"),
    ("亮度和饱和度描述颜色。", "Lightness and saturation complete the picture.", "saturation（饱和度）")]),
  ("减色法与加色法", "Subtractive and Additive", "01:56", "绘画涂料的混合是减色法，颜色多涂在一起就偏黑；光的混合是加色法，所有光混在一起就是白。",
   [("涂料混合是减色法。", "Paint mixing is subtractive.", "subtractive（减色法）"),
    ("光混合是加色法。", "Mixing light is additive.", "additive（加色法）")]),
  ("颜色是感觉", "Color Is a Sensation", "02:53", "颜色不是物体的固有物理属性，而是人眼看到物体的光谱处理后的一种感觉。",
   [("颜色不是物体固有属性。", "Color isn't a fixed physical property.", "physical property（物理属性）"),
    ("它是人眼处理光谱的结果。", "It's the eye processing the spectrum.", "spectrum（光谱）")]),
  ("光谱功率分布", "Spectral Power Distribution", "03:10", "所谓光谱就是光谱功率分布，简称SPD，描述每个波长上的能量多少。",
   [("光谱功率分布缩写SPD。", "SPD stands for spectral power distribution.", "spectral power（光谱功率）"),
    ("它描述各波长的能量。", "It describes energy at each wavelength.", "wavelength（波长）")]),
  ("人眼的三刺激", "Tristimulus Vision", "04:00", "人眼只有三种感光锥细胞，颜色是三种信号按比例混合出的感觉，这就是三刺激理论。",
   [("人眼有三种锥细胞。", "The human eye has three types of cones.", "cones（视锥细胞）"),
    ("三刺激理论解释配色。", "Tristimulus theory explains color matching.", "tristimulus（三刺激）")]),
  ("从画家到科学家", "From Painters to Scientists", "05:30", "画家凭经验调色，科学家用数字精确描述，两者最终汇合在同一套色彩体系上。",
   [("画家靠经验调色。", "Painters mixed color by experience.", "experience（经验）"),
    ("科学家用数字描述。", "Scientists described it in numbers.", "in numbers（用数字）")]),
  ("总结：认知路径", "Summary: The Path of Discovery", "17:00", "从主观描述到定量体系，人类一步步把「颜色」这个感觉变成了可测量、可复制的科学。",
   [("颜色从感觉变成科学。", "Color went from feeling to science.", "science（科学）"),
    ("测量让色彩可复制。", "Measurement makes color reproducible.", "reproducible（可复制的）")]),
 ],
),
(
 "shot-thinking-from-zero", "建议收藏！从零养成镜头拍摄思维", "Build a Shot-Framing Mindset from Zero", "2分49秒", "摄影 · 分镜思维", "http://xhslink.cn/o/607rJmuUveQ",
 [
  ("开场：文字转镜头", "Opening: Words to Shots", "00:00", "要拍出有电影感的短片分几步？其实一步：把文字语言转化成镜头语言，靠分镜头脚本辅助完成。",
   [("拍电影感短片就一步。", "Cinematic short films need one step.", "cinematic（电影感的）"),
    ("把文字转化为镜头语言。", "Turn words into camera language.", "camera language（镜头语言）")]),
  ("分镜头思维", "Storyboard Thinking", "00:17", "不是要你去画分镜头脚本，而是要形成分镜头拍摄思维，在脑子里快速完成分镜规划。",
   [("不一定要画分镜脚本。", "You don't need to draw a storyboard.", "storyboard（分镜脚本）"),
    ("在脑子里完成分镜规划。", "Plan shots in your head.", "plan shots（规划镜头）")]),
  ("放大与还原", "The Zoom-and-Match Principle", "00:40", "使用放大和百分之百还原这两个技巧，可以极大降低思考时间成本，提高拍摄效率。",
   [("用放大还原两个技巧。", "Use the zoom and match-back tricks.", "match（还原）"),
    ("降低思考时间成本。", "Cut your thinking time.", "thinking time（思考时间）")]),
  ("先远后近", "Wide Then Close", "00:50", "确定人物在某个场景做什么：先稍微远一点看他在干嘛，再凑近一点看他具体在干嘛。",
   [("先远一点看整体。", "First shoot wide to see the scene.", "wide shot（全景）"),
    ("再凑近看细节。", "Then move closer for the detail.", "closer（更近）")]),
  ("例：开心上学", "Example: Happy to School", "01:01", "「女生开心去上学」用镜头语言表达就是两个画面：先蹲拍全身远景关门转身，再中近景跟拍同样的动作。",
   [("一句话拆成两个画面。", "One sentence becomes two shots.", "sentence（句子）"),
    ("中近景重做同样动作。", "Repeat the action in a medium shot.", "medium shot（中景）")]),
  ("动作延续性", "Continuity of Action", "01:22", "门其实没打开，只让演员假装关门走掉，通过动作的延续性让观众自行脑补。",
   [("让观众自行脑补。", "Let the audience fill in the gaps.", "fill in the gaps（脑补）"),
    ("用动作延续制造真实。", "Continuity of action sells the scene.", "continuity（连续性）")]),
  ("例：晾衣服", "Example: Hanging Clothes", "01:34", "先拍拿衣服摊开挂上的中近景全程，焦点从人转到衣服，再远一点景别拍一次同样的动作。",
   [("先拍动作的全过程。", "Shoot the full action first.", "full action（完整动作）"),
    ("焦点从人转到衣服。", "Shift focus from person to clothes.", "shift focus（转移焦点）")]),
  ("艺术化处理", "Artistic Touches", "02:12", "除了基础交代动作，可以加艺术化处理：拍衣服随风飘动的镜头、把挂衣服的动作虚化在背景里。",
   [("加入艺术化的处理。", "Add artistic touches.", "artistic（艺术化的）"),
    ("虚化背景突出主体。", "Blur the background to highlight the subject.", "blur（虚化）")]),
 ],
),
(
 "on-camera-fat-lens", "摄影常识｜上镜胖十斤，从来不是镜头问题！", "Camera Adds Ten Pounds? It's Not the Lens", "1分13秒", "摄影 · 透视原理", "http://xhslink.cn/o/7eCwEVzHpEn",
 [
  ("开场：显胖的真相", "Opening: The Truth About Looking Fat", "00:00", "上镜显胖不是因为你本来就胖，更不是因为所谓的镜头畸变和长焦镜头，真正决定胖瘦的是你和镜头之间的物理距离。",
   [("显胖不是镜头的错。", "Looking fat isn't the lens's fault.", "lens（镜头）"),
    ("物理距离决定胖瘦。", "Physical distance decides the look.", "physical distance（物理距离）")]),
  ("透视重塑比例", "Perspective Reshapes Proportions", "00:09", "距离的变化产生近大远小的透视关系，会直接重塑鼻子和面部的比例。",
   [("近大远小是透视关系。", "Bigger-near-smaller-far is perspective.", "perspective（透视）"),
    ("距离重塑面部比例。", "Distance reshapes facial proportions.", "proportion（比例）")]),
  ("实验：焦段不变", "Experiment: Focal Length Doesn't Matter", "00:15", "保持人和镜头距离不变，分别用35mm和135mm画面拍摄放大，背景的压缩程度根本没变。",
   [("距离不变焦段随便换。", "Same distance, different focal lengths.", "focal length（焦距）"),
    ("背景压缩程度不变。", "The background compression stays the same.", "compression（压缩）")]),
  ("压缩属于距离", "Compression Belongs to Distance", "00:25", "压缩从来不属于任何焦段的镜头，它只属于远距离而产生的弱透视，让画面变平。",
   [("压缩不属于焦段。", "Compression belongs to no lens.", "belong to（属于）"),
    ("它来自远距离弱透视。", "It comes from weak perspective at distance.", "weak perspective（弱透视）")]),
  ("光学放大 vs 数码裁切", "Optical Zoom vs Digital Crop", "00:36", "长焦镜头的光学放大无损保留画质，而后期数码裁切会放大噪点损失画质，这就是长焦的本质差异。",
   [("光学放大无损画质。", "Optical zoom keeps the quality lossless.", "optical zoom（光学变焦）"),
    ("数码裁切会放大噪点。", "Digital cropping amplifies noise.", "digital crop（数码裁切）")]),
  ("长焦的本质", "What a Telephoto Really Is", "00:34", "长焦镜头的本质是无损的光学放大镜，推到20米外，人脸上五官的深度也悄然消失。",
   [("长焦是无损放大镜。", "A telephoto is a lossless magnifier.", "magnifier（放大镜）"),
    ("距离抹平五官深度。", "Distance flattens facial depth.", "flatten（压平）")]),
  ("答案：拍侧脸", "The Answer: Shoot in Profile", "00:46", "极远的物理距离会抹平正面的纵深，但它抹不掉侧面的轮廓线，所以答案只有三个字：拍侧脸。",
   [("距离抹不掉侧脸轮廓。", "Distance can't erase the profile line.", "profile line（轮廓线）"),
    ("用侧脸重新切出立体感。", "Re-carve depth with the profile.", "re-carve（重新切出）")]),
  ("成熟摄影", "Mature Photography", "01:05", "真正成熟的摄影不是被参数绑架，而是合理利用距离和角度，去驯化光学的性格。",
   [("别被参数绑架。", "Don't be held hostage by settings.", "settings（参数）"),
    ("用距离和角度驯化光学。", "Tame optics with distance and angle.", "tame（驯化）")]),
 ],
),
(
 "sony-a6700-four-features", "索尼A6700封神的4个功能🔥90%的人没解锁", "Sony A6700: 4 Hidden Power Features", "2分15秒", "摄影 · 相机技巧", "http://xhslink.cn/o/68JyP8XWror",
 [
  ("开场：进阶玩法", "Opening: Advanced Features", "00:00", "很多人拿到索尼A6700只用基础拍照录像功能，不知道这台半画幅旗舰机藏着多个进阶玩法。",
   [("很多人只用基础功能。", "Most people only use the basics.", "basics（基础功能）"),
    ("藏着提升效率的进阶玩法。", "It hides powerful advanced features.", "advanced（进阶的）")]),
  ("功能一：对焦包围", "Feature 1: Focus Bracketing", "00:12", "对焦包围拍摄可以自动拍多张不同焦点的照片，后期导入PS一键堆叠，拍微距风光全清晰。",
   [("自动拍多张不同焦点。", "It shoots multiple focus distances automatically.", "focus bracketing（对焦包围）"),
    ("后期堆叠全部清晰。", "Stack them later for full sharpness.", "stack（堆叠）")]),
  ("功能一设置", "Setting Up Bracketing", "00:26", "菜单里进入拍摄页找到拍摄模式选对焦包围，增量到4，拍摄张数从9张开始练手。",
   [("菜单里选择对焦包围。", "Pick focus bracketing in the menu.", "menu（菜单）"),
    ("增量4、张数9起步。", "Step 4, starting with 9 shots.", "increment（增量）")]),
  ("功能二：快捷键", "Feature 2: Custom Keys", "00:37", "把常用功能分配到快捷键，三套MR参数一键切换，拍照片视频不耽误。",
   [("把常用功能分配到快捷键。", "Assign frequent features to custom keys.", "custom keys（自定义键）"),
    ("三套参数一键切换。", "Switch among three setups instantly.", "setup（参数组）")]),
  ("功能二设置", "Mapping the Keys", "00:45", "在操作自定义中把C1设为对焦模式切换、C2设为对焦区域切换，再存储三套场景参数。",
   [("C1切换对焦模式。", "C1 toggles focus mode.", "toggle（切换）"),
    ("存储三套常用参数。", "Store three common setups.", "store（存储）")]),
  ("功能三：峰值对焦", "Feature 3: Focus Peaking", "01:15", "峰值对焦让手动对焦也能精准到睫毛，大光圈拍摄不跑焦，对焦越清晰的地方红色越多。",
   [("峰值让手动对焦精准。", "Peaking makes manual focus precise.", "focus peaking（峰值对焦）"),
    ("清晰处显示红色。", "In-focus edges light up red.", "in focus（合焦）")]),
  ("功能三设置", "Enabling Peaking", "01:22", "菜单对焦页打开峰值显示，峰值水平设为高、色彩设为红色，手动对焦再也不发愁。",
   [("峰值水平设为高。", "Set peaking level to high.", "level（水平）"),
    ("峰值色彩设为红色。", "Set the peaking color to red.", "color（颜色）")]),
  ("功能四：创意外观", "Feature 4: Creative Look", "01:37", "创意外观加S3 Tone，不用后期调色直出电影感画面，照片选FL、视频选PP11（S3Tone）。",
   [("创意外观直出电影感。", "Creative Looks give film-like straight-out-of-camera color.", "creative look（创意外观）"),
    ("视频用PP11 S3Tone。", "Use PP11 S3Tone for video.", "S3Tone（S3色调）")]),
 ],
),
(
 "fangyuan-makeup-frame", "方圆脸化妆开智，妆容框架‼️总结篇", "Round-Face Makeup Framework: A Master Summary", "3分31秒", "美妆 · 方圆脸妆容", "http://xhslink.cn/o/4kKItBTRO4u",
 [
  ("开场：后置看清脸", "Opening: See Your True Face", "00:00", "方圆脸化妆开智是在你能面对后置镜头的时候，因为在这个视角下才能真正看清你的脸。",
   [("后置镜头看清真实的脸。", "The rear camera shows your true face.", "rear camera（后置镜头）"),
    ("看清才能领悟化妆框架。", "Seeing clearly unlocks the makeup framework.", "framework（框架）")]),
  ("眉毛画在外轮廓", "Brows on the Outer Contour", "00:06", "领悟到眉毛不够长，需要画在外轮廓的中间，并且带一些微微的弧度才能修饰脸型。",
   [("眉毛要画到外轮廓。", "Extend the brow to the outer contour.", "contour（轮廓）"),
    ("微微弧度修饰脸型。", "A gentle arch flatters the face.", "arch（弧度）")]),
  ("收缩式腮红", "Contour Blush", "00:15", "腮红不应该打在中间，而应该选收缩式腮红去修饰外边缘轮廓，才是真正修饰方圆脸的打法。",
   [("用收缩式腮红。", "Use a contouring blush.", "contouring blush（收缩腮红）"),
    ("修饰外边缘轮廓。", "Sculpt the outer edge.", "sculpt（塑形）")]),
  ("唇妆模糊边界", "Lip Blurring", "00:25", "唇妆颜色重要但模糊边界更重要，深刻的唇线边缘会把视觉重心移到下半张脸、显得脸更宽。",
   [("模糊唇线边界更重要。", "Blurring the lip line matters more.", "blur（模糊）"),
    ("深唇线显脸宽。", "Harsh lines widen the face.", "harsh（生硬的）")]),
  ("眼妆靠修容", "Eyeshadow Needs Contour", "00:38", "眼妆重点不是眼线画多长眼影画多深，而是学会利用修容塑造眼眶骨的骨相感，让眼从2D变3D。",
   [("用修容塑造眼眶骨。", "Use contour to shape the orbital bone.", "contour（修容）"),
    ("让眼从2D变3D。", "Take the eye from 2D to 3D.", "three-dimensional（立体的）")]),
  ("眼眶骨修容位置", "Where the Orbital Contour Goes", "01:03", "眼眶骨应该在眉毛到眼角的范围，用高状修容画出小鱼号，眉尾最长的位置到眼角。",
   [("眼眶骨在眉到眼角的范围。", "It spans from brow to eye corner.", "eye corner（眼角）"),
    ("画出一个小鱼号。", "Draw a small fish-hook shape.", "fish-hook（鱼钩形）")]),
  ("卧蚕的画法", "The Under-Eye Bag", "01:37", "卧蚕要画成一个眼影面才立体不生硬，新手选带点粗度的平头刷，先画下至找到卧蚕大小和区域。",
   [("卧蚕画成面才立体。", "Blend the under-eye into a soft shape.", "under-eye（卧蚕）"),
    ("新手用平头刷。", "Beginners should use a flat brush.", "flat brush（平头刷）")]),
  ("卧蚕提亮", "Highlighting the Under-Eye", "02:34", "卧蚕画完用高光修容笔提亮最中间的位置，不要贴到眼下根部，用手指轻轻拍两下晕开。",
   [("用高光笔提亮中间。", "Highlight the center with a brightening pen.", "highlight（提亮）"),
    ("别贴眼下根部。", "Don't go right under the eye.", "lash line（眼根）")]),
 ],
),
(
 "round-face-angle-tips", "方圆脸出片秘诀！靠的是角度！", "Round Faces Photograph Well: It's All Angles", "3分56秒", "审美 · 拍照角度", "http://xhslink.cn/o/7RAY78P2oMC",
 [
  ("开场：角度决定一切", "Opening: Angles Decide", "00:00", "方圆脸拍照没你想的那么难，一直需要找到好看的角度，今天毫无保留把技巧全告诉你。",
   [("方圆脸拍照不难。", "Round faces aren't hard to photograph.", "round face（方圆脸）"),
    ("找到角度就成功。", "Find the right angle and win.", "angle（角度）")]),
  ("工具：自拍杆", "Gear: The Selfie Stick", "00:13", "用的就是16 Pro Max和自拍杆，可以伸展到1米7，按钮和蓝牙打开连接。",
   [("用自拍杆找角度。", "A selfie stick helps find angles.", "selfie stick（自拍杆）"),
    ("蓝牙连接遥控快门。", "Bluetooth pairs the remote shutter.", "bluetooth（蓝牙）")]),
  ("后置显宽前置显小", "Rear Widens, Front Slims", "00:24", "后置脸这一块会显得极其宽大，换成前置脸就小了很多，所以出片秘诀是自拍。",
   [("后置把脸拍宽。", "The rear camera widens your face.", "widen（变宽）"),
    ("前置让脸显小。", "The front camera slims it.", "slim（显瘦）")]),
  ("2/3侧脸", "The Two-Thirds Profile", "00:47", "脸显平就拍三分之二侧脸，稍微侧一点点，这边留三分之一、那边留三分之二，脸一下子就有骨相显瘦了。",
   [("脸平就拍2/3侧脸。", "A flat face looks better at the 2/3 angle.", "two-thirds profile（三分之二侧脸）"),
    ("侧脸立显骨相。", "The profile instantly adds structure.", "structure（骨相）")]),
  ("头发遮挡", "Hair as a Frame", "01:27", "不好看的这一边脸可以用发型进行一部分遮挡，让脸型线条流畅，脸型一下就变小。",
   [("用发型遮挡另一边。", "Use hair to cover the other side.", "cover（遮挡）"),
    ("遮挡让脸型流畅。", "Coverage smooths the face line.", "smooth（流畅）")]),
  ("镜头放低抬头", "Low Camera, Face Up", "01:52", "进阶玩法：镜头放低再把镜头抬起来，用舌头抵住上颚，双下巴就不容易露出来。",
   [("镜头放低再抬起。", "Lower the camera, then angle it up.", "angle up（仰拍）"),
    ("舌头抵住上颚。", "Press your tongue to the roof of the mouth.", "roof of the mouth（上颚）")]),
  ("不常规视角", "Unconventional Views", "02:11", "越不常规的视角往往让照片越来越特别，不要看镜头，把脸往上面看。",
   [("越不常规越特别。", "Unusual views make photos special.", "unusual（不寻常的）"),
    ("不看镜头往上看。", "Look up instead of at the lens.", "look up（往上看）")]),
  ("表情管理", "Expression Control", "02:23", "所有方圆脸拍照几乎都伴随身复合问题，拍照时不要把牙关咬紧，无论张嘴闭嘴牙齿都不可以咬紧。",
   [("牙关不要咬紧。", "Don't clench your jaw.", "clench（咬紧）"),
    ("放松下半张脸。", "Relax the lower face.", "relax（放松）")]),
 ],
),
(
 "square-face-hair-frame", "方圆脸快来变美，复制明星同款头包脸。", "Round Faces: Copy the Celebrity Head-Wrap Look", "4分13秒", "美发 · 头包脸", "http://xhslink.cn/o/7wYzTmmHlhQ",
 [
  ("开场：头包脸 vs 脸包头", "Opening: Hair-Wrap vs Face-Wrap", "00:00", "方圆脸姐妹都有这样的困扰，今天复刻明星同款头包脸，三分钟从这样变成这样，主打披发扎发都好看。",
   [("复刻明星同款头包脸。", "Copy the celebrity hair-wrapped head look.", "hair-wrapped（头包脸的）"),
    ("披发扎发都好看。", "Looks great up or down.", "looks great（好看）")]),
  ("两者的差距", "The Difference Explained", "00:20", "脸包头就是颅顶低、贴头皮、捏去扁、整个头发没有厚度，看起来脸的面积比头发多。",
   [("脸包头颅顶低贴头皮。", "A face-wrap has a flat, low crown.", "crown（头顶）"),
    ("头发没有厚度。", "The hair lacks volume.", "volume（蓬松度）")]),
  ("头包脸的标准", "What Hair-Wrap Looks Like", "00:33", "头包脸就是不管正面还是侧面，整个轮廓都是圆润饱满的，头发包住脸。",
   [("头包脸轮廓圆润。", "A hair-wrap gives a round, full outline.", "outline（轮廓）"),
    ("正面侧面都饱满。", "Full from every angle.", "full（饱满的）")]),
  ("烫发工具与分区", "The Tool and Sections", "00:38", "烫发工具像马赛克一样，选窄板不选特别宽的；给头发分区，摸过来有两个骨头的地方绝对不能烫。",
   [("选窄板的烫发工具。", "Pick a narrow straightener plate.", "straightener（直发夹板）"),
    ("两个骨头处不能烫。", "Don't curl where the skull bones sit.", "skull bones（头骨）")]),
  ("分区：顶点与枕骨", "Sections: Crown and Occiput", "01:03", "从前面把线找出来到顶点，顶点是耳尖往上的中间位置也就是天灵盖；后面整骨最扁的手掌大区域不要烫。",
   [("顶点在耳尖往上。", "The crown sits above the ear tip.", "ear tip（耳尖）"),
    ("枕骨最扁处不烫。", "Skip the flattest occiput area.", "occiput（枕骨）")]),
  ("正确烫法", "The Correct Technique", "01:44", "分区对了但烫的角度很重要，把发片拿起来垂直于头皮，夹板完全贴到发根，停留五到十秒钟。",
   [("发片垂直头皮。", "Hold the section perpendicular to the scalp.", "perpendicular（垂直的）"),
    ("夹板贴到发根。", "Press the plate to the roots.", "roots（发根）")]),
  ("耳后扩容", "Volume Behind the Ears", "02:15", "耳后括弧这个地方很多姐妹想让头发厚起来，会显得脸小，可以多停留一下，冷却完才能定型。",
   [("耳后烫厚显脸小。", "Volume behind the ears slims the face.", "volume（蓬松）"),
    ("冷却后才能定型。", "Let it cool to set the curl.", "set（定型）")]),
  ("颅顶烫法", "The Crown Curl", "03:00", "颅顶不能全部烫，两指宽只烫这么多，分成两次烫，先烫最外面的这一片，提拉角度很重要。",
   [("颅顶只烫两指宽。", "Curl only two fingers wide at the crown.", "two fingers（两指宽）"),
    ("提拉角度很重要。", "The lift angle is key.", "lift angle（提拉角度）")]),
 ],
),
(
 "joker-film-pull-part1", "《小丑》拉片完整版-上集", "Joker: A Full Scene-by-Scene Breakdown, Part 1", "25分37秒", "电影 · 视听语言", "http://xhslink.cn/o/4wNnQ9k0FNJ",
 [
  ("开场：导演的责任", "Opening: The Director's Job", "00:00", "导演是电影最终质量的第一责任人，除了喊Action和卡，在内容层面还要做好很多工作。",
   [("导演是质量第一责任人。", "The director owns the film's quality.", "accountable（负责任的）"),
    ("内容层面要做好很多工作。", "There's much content work beyond calling action.", "content（内容）")]),
  ("小丑的荣誉", "Joker's Honors", "00:24", "《小丑》2019年拿到威尼斯电影节金狮奖，是第一部也是唯一一部获得金狮奖的漫改电影。",
   [("2019年获金狮奖。", "It won the Golden Lion in 2019.", "Golden Lion（金狮奖）"),
    ("唯一获金狮奖的漫改电影。", "The only comic-book film to do so.", "comic-book film（漫改电影）")]),
  ("主角出场", "Introducing the Protagonist", "00:49", "如何让主角一出场就给观众留下印象：先给远景背影看不到脸，再特写化妆的手，胃口渐渐被吊起来。",
   [("先远景背影不见脸。", "Start with a back view, no face.", "back view（背影）"),
    ("用特写吊起胃口。", "Close-ups build the suspense.", "suspense（悬念）")]),
  ("渐进亮相", "The Gradual Reveal", "01:38", "侧面大特写还是看不到全貌，切到镜子里的近景由虚到实，最后正面脸部大特写终于看清。",
   [("由虚到实慢慢呈现。", "Go from blurry to sharp.", "blurry（模糊的）"),
    ("最后正面特写亮相。", "End with the full face close-up.", "close-up（特写）")]),
  ("不见其人先闻其声", "Hear Them Before You See Them", "02:03", "介绍关键人物时不见其人先闻其身或先见其行，以引起观众注意，是最基本的描述手法。",
   [("未见其人先闻其声。", "Hear the person before seeing them.", "hear before seeing（先声夺人）"),
    ("这是基本描述手法。", "It's a fundamental storytelling device.", "device（手法）")]),
  ("视听语言细节", "Visual Language Details", "06:00", "电影里通过镜头运动、光线和构图来表达情绪，每个画面都有它的视听语言功能。",
   [("镜头运动表达情绪。", "Camera moves express emotion.", "camera move（镜头运动）"),
    ("光线构图都有功能。", "Light and composition serve the story.", "composition（构图）")]),
  ("烂片的问题", "Why Bad Films Fail", "10:00", "一部烂片被骂，往往是最基础的镜头语言和叙事逻辑出了问题，连「让人记住主角」都没做到。",
   [("烂片输在基础。", "Bad films fail at the basics.", "basics（基本功）"),
    ("连主角都没让人记住。", "They don't even make the lead memorable.", "memorable（难忘的）")]),
  ("总结：拉片的意义", "Summary: Why We Analyze", "20:00", "通过拉片拆解优秀电影的技术细节，才能找到「好电影为什么好」的答案。",
   [("拉片拆解技术细节。", "Break the film down shot by shot.", "shot by shot（逐镜）"),
    ("找到好电影的秘密。", "Find why great films work.", "why（原因）")]),
 ],
),
(
 "native-camera-slim-tips", "原相机直出显瘦技巧✨告别上镜胖一圈👋", "Look Slimmer in the Native Camera: 4 Poses", "49秒", "审美 · 拍照姿势", "http://xhslink.cn/o/26iIFYPIxJj",
 [
  ("开场：四个姿势", "Opening: Four Poses", "00:00", "人可以胖但上镜显瘦，不想拍得虎背熊腰，这四个姿势带这么拍。",
   [("四个姿势告别显胖。", "Four poses to stop looking wide.", "pose（姿势）"),
    ("上镜也能显瘦。", "You can still look slim on camera.", "slim（显瘦的）")]),
  ("姿势一：靠着拍", "Pose 1: Lean and Extend", "00:04", "靠着拍照不要缩着靠，侧面把手伸出去，另一只手手肘内扣藏在身后就好。",
   [("靠着拍别缩着。", "Lean, don't hunch.", "hunch（缩肩）"),
    ("伸出一只手显修长。", "Extend one arm for length.", "extend（伸展）")]),
  ("姿势二反例：搭胳膊", "Pose 2 Counter: Crossed Arms", "00:17", "回身却搭胳膊，前臂横在身前，轮廓立刻变厚，这是最典型的错误示范。",
   [("前臂横在身前显厚。", "The forearm across the front thickens you.", "forearm（前臂）"),
    ("回身别搭胳膊。", "Don't cross the arms when turning.", "cross the arms（抱臂）")]),
  ("姿势二：回眸拍", "Pose 2: The Turn", "00:15", "回眸拍照不要打格格，向后打开成个三角形，再把尴尬的笑容挡一挡就好。",
   [("向后打开成三角形。", "Open back into a triangle.", "triangle（三角形）"),
    ("用手挡一下笑容。", "Cover the smile with your hand.", "cover（遮挡）")]),
  ("姿势三：剪刀手", "Pose 3: Peace Sign", "00:24", "剪刀手拍照不要贴着脸，把手往前伸，再往对角线里塞一塞就好。",
   [("剪刀手别贴脸。", "Don't press the peace sign to your face.", "peace sign（剪刀手）"),
    ("手往前伸到对角线。", "Reach forward into the diagonal.", "diagonal（对角线）")]),
  ("姿势三修正：往前伸", "Pose 3 Key Fix: Reach Forward", "00:29", "修正的关键是手往镜头前伸，而不是贴在脸颊旁，这样会拉长比例、挡住脸侧。",
   [("手往镜头前伸。", "Reach the hand toward the lens.", "reach（伸出）"),
    ("别贴在脸颊旁。", "Don't press it against the cheek.", "cheek（脸颊）")]),
  ("姿势四：撩头发", "Pose 4: Hair Flip", "00:33", "撩头发拍照不要抱成团，胳膊打开撑在腰上，再挑补肩，另一只手抬起来些就好。",
   [("胳膊打开撑在腰上。", "Open the arms and rest on the waist.", "rest on the waist（撑腰）"),
    ("另一只手抬起来。", "Lift the other hand slightly.", "lift（抬起）")]),
  ("结尾提醒", "Closing Reminder", "00:44", "听说你又踩坑了，下次可别踩了，记住这四招上镜显瘦。",
   [("记住这四招。", "Remember these four tricks.", "trick（技巧）"),
    ("下次别再踩坑。", "Don't fall into the trap next time.", "trap（坑）")]),
 ],
),
]

def paraphrase_for(sentences):
    out = []
    for zh, en, note in sentences:
        word = note.split("（")[0].strip()
        out.append([f"用{word}换一种说法", en])
    return out

def main():
    for slug, title, title_en, duration, topic, url, scenes in V:
        data = {
            "meta": {
                "slug": slug, "title": title, "title_en": title_en,
                "duration": duration, "scenes": len(scenes),
                "sentences": sum(len(s[4]) for s in scenes),
                "date": DATE, "platform": PLATFORM, "source_url": url, "topic": topic,
            },
            "scene_imgs": [f"shot-{i+1:02d}" for i in range(len(scenes))],
            "scenes": [],
        }
        for i, (tc, te, t, ctx, sents) in enumerate(scenes, 1):
            data["scenes"].append({
                "id": f"s{i}", "title_cn": tc, "title_en": te, "time": t,
                "context": ctx,
                "sentences": [list(s) for s in sents],
                "paraphrase": paraphrase_for(sents),
                "speak": " ".join(en for _, en, _ in sents),
            })
        data["practice"] = []
        data["pitfalls"] = []
        data["shifts"] = []
        data["difficult_words"] = []
        data["footer_notes"] = f"来源：{title}（小红书，时长{duration}）"
        p = OUT / f"{slug}.json"
        p.write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"✓ {slug} {len(scenes)} scenes")

if __name__ == "__main__":
    main()
