#!/usr/bin/env python3
"""b38 JSON 生成脚本：服装选购类（10篇）"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "scripts" / "scene-data"
OUT.mkdir(parents=True, exist_ok=True)

DATE = "2026-08-08"
PLATFORM = "xiaohongshu"

V = [
(
 "clothes-wearable-check", "买衣服不要只看好看，要考虑能不能穿出去", "Buy Clothes You'll Actually Wear", "1分08秒", "服装 · 实穿性", "http://xhslink.cn/o/9v1QDNQVQkf",
 [
  ("开场：设计给谁穿", "Opening: Who Is This For?", "00:00", "这都不知道是设计给谁穿的，那么慢，美人鱼吗？设计感单品要回到实穿性来判断。",
   [("这衣服是设计给谁穿的。", "Who on earth is this for?", "design（设计）"),
    ("设计感单品要讲实穿。", "Design pieces must stay wearable.", "wearable（实穿的）")]),
  ("真丝易变形", "Silk Deforms Easily", "00:04", "真丝本身弹性很大就容易变形，这鞋才后期更保证它百分百的变形了。",
   [("真丝弹性大易变形。", "Silk is stretchy and deforms.", "deform（变形）"),
    ("后期百分百变形。", "It will definitely warp later.", "warp（变形）")]),
  ("BM风短裙", "The Too-Short Skirt", "00:11", "这两年 BM 风很火，这短裙设计得短的离谱，前怕走光后怕走光，穿着压力太大。",
   [("短裙短的离谱。", "The skirt is absurdly short.", "absurd（离谱的）"),
    ("前怕走光后怕走光。", "You'd worry about flashing all day.", "flash（走光）")]),
  ("好看但别买", "Pretty, But Don't Buy It", "00:24", "这件衣服看着好看但绝对不要买：收腰显瘦加流行元素是好看，但款式和面料不配套。",
   [("好看不一定能穿。", "Pretty doesn't mean wearable.", "wearable（可穿的）"),
    ("款式面料不配套。", "The style and fabric clash.", "clash（不搭）")]),
  ("无弹力面料", "No-Stretch Fabric", "00:36", "收腰款基本贴身穿，活动量本来就小，纯亚麻一点弹力都没有，连坐下都容易开线。",
   [("收腰款活动量小。", "Fitted tops have little give.", "fitted（贴身的）"),
    ("纯亚麻没弹力易开线。", "Pure linen splits at the seams.", "split（开线）")]),
  ("设计点过多", "Too Many Design Details", "00:46", "这件衣服设计点比较多，风格线、捏褶、侧边蕾丝加上亚麻爱出褶，坐一下起来就乱得像破烂。",
   [("设计点太多显杂乱。", "Too many details look messy.", "messy（杂乱的）"),
    ("亚麻坐下就皱。", "Linen wrinkles as soon as you sit.", "wrinkle（起皱）")]),
  ("结论：实穿优先", "Conclusion: Wearability First", "00:59", "所以大家不要只看好看，一定要考虑到实穿性，好看但穿不出去等于白买。",
   [("别只看好看。", "Don't only look at looks.", "looks（外表）"),
    ("实穿性必须考虑。", "Wearability is a must.", "must（必须）")]),
  ("结尾：真丝短裤", "Ending: Silk Shorts", "01:02", "这真丝短裤到底是谁在穿的？又厚又热又显胖，你们日常会穿吗？",
   [("真丝短裤又厚又热。", "Silk shorts are hot and bulky.", "bulky（显胖的）"),
    ("日常根本不会穿。", "You'd never wear them daily.", "daily（日常）")]),
 ],
),
(
 "clothes-thinking-not-rote", "挑衣服学思路，千万别死记硬背", "Learn the Method, Not the Rules", "1分25秒", "服装 · 选购思路", "http://xhslink.cn/o/A0j0SrH50lp",
 [
  ("开场：看了不会用", "Opening: Learned but Frozen", "00:00", "很多人看了很多期挑衣服视频，感觉好像会了，但真正自己挑衣服的时候脑子一片空白。",
   [("看视频觉得会了。", "You feel you've learned it all.", "learn（学会）"),
    ("真买时脑子空白。", "Then you blank out in the store.", "blank out（一片空白）")]),
  ("点题：学思路", "Theme: Learn the Logic", "00:15", "核心提醒：千万千万别死记硬背，要学思路，让脑子形成一个深刻的印象。",
   [("千万别死记硬背。", "Never memorize by rote.", "rote（死记硬背）"),
    ("要学的是思路。", "Learn the logic instead.", "logic（思路）")]),
  ("学思路不背口诀", "Learn Ideas, Skip Rote", "00:10", "挑衣服一定要学思路，千万别死记硬背，要让脑子形成一个深刻的印象。",
   [("挑衣服要学思路。", "Learn the logic behind choosing.", "logic（思路）"),
    ("千万别死记硬背。", "Don't memorize by rote.", "rote（死记硬背）")]),
  ("外套两类", "Two Kinds of Coats", "00:24", "秋天买外套，外套无非挂里布和不挂里布两种，不管哪一种，记住一个点一眼辨好坏。",
   [("外套分挂里不挂里。", "Coats are lined or unlined.", "lined（带里布的）"),
    ("记住一点一眼辨好坏。", "One point judges quality at a glance.", "at a glance（一眼）")]),
  ("不挂里布看侧缝", "Unlined: Check the Side Seam", "00:35", "不挂里布的外套直接看侧缝这条线：直接锁边的最基础最差，包边处理好一些，最好的是握手缝和来去缝。",
   [("锁边是最基础的。", "Overlocked edges are the basics.", "overlock（锁边）"),
    ("握手缝来去缝最好。", "Felled and French seams are best.", "felled seam（握手缝）")]),
  ("挂里布看成分", "Lined: Check the Lining", "00:51", "挂里布的外套直接看里布成分：百分百聚酯纤维最差，容易起静电；百分百棉或棉混纺属于基础。",
   [("聚酯里布最差。", "Polyester lining is the worst.", "polyester（聚酯）"),
    ("纯棉里布吸湿透气。", "Cotton lining breathes.", "cotton（纯棉）")]),
  ("顶级里布", "Top-Tier Linings", "01:15", "里布用百分百桑蚕丝或铜氨丝，那这件衣服不管板型还是工艺肯定都是最好的。",
   [("桑蚕丝是顶级里布。", "Silk is the premium lining.", "silk（桑蚕丝）"),
    ("板型工艺都最好。", "Fit and craft are top-notch.", "top-notch（顶级）")]),
  ("顶档判断", "The Top-Tier Call", "01:18", "顶档样：里料百分百桑蚕丝，也提到铜氨丝，被判版型与工艺最好。",
   [("里料桑蚕丝是顶档。", "A silk lining is top-tier.", "top-tier（顶档）"),
    ("铜氨丝同样高级。", "Cupro ranks just as high.", "cupro（铜氨丝）")]),
 ],
),
(
 "clothes-look-cheap-details", "衣服显“穷”细节，能提醒一个是一个", "Small Details That Make Clothes Look Cheap", "51秒", "服装 · 品质细节", "http://xhslink.cn/o/5EjfyNRtyPO",
 [
  ("开场：挂耳", "Opening: The Hanger Loop", "00:00", "很多衣服这一块有条小绳，或者风衣这边有条扁平绳子，这个就叫挂耳，用于悬挂衣服防止滑落变形。",
   [("衣领后的小绳叫挂耳。", "The little loop is a hanger loop.", "hanger loop（挂耳）"),
    ("它防止衣服滑落变形。", "It stops the garment slipping.", "slip（滑落）")]),
  ("细节决定品质", "Details Define Quality", "00:13", "比较注重细节的衣服上才会出现挂耳，你们真的不看这些吗？细节决定品质。",
   [("注重细节才有挂耳。", "Detail-oriented brands add them.", "detail（细节）"),
    ("细节决定品质。", "Details define quality.", "quality（品质）")]),
  ("左右对齐显贵", "Symmetry Looks Expensive", "00:18", "再看这种左右对齐的，是不是舒服很酷？自然就会显贵，一件衣服精不精致都是细节决定的。",
   [("左右对齐看着舒服。", "Symmetric lines look neat.", "symmetric（对称的）"),
    ("对齐自然显贵。", "Alignment reads as expensive.", "expensive（显贵的）")]),
  ("反例：条纹错位", "Counter: Misaligned Stripes", "00:16", "反例：横条在接缝处错位明显，一眼就看得出粗糙，这就是显穷的细节。",
   [("条纹接缝错位。", "Stripes misalign at the seams.", "misalign（错位）"),
    ("错位一眼显粗糙。", "Misalignment reads as cheap.", "cheap（廉价的）")]),
  ("领贴露尖", "The Spilling Collar Stay", "00:27", "你看这领贴圆角度还带尖呢，但能好看吗？像这种衣领漏尖位移，选的时候一定要反过来看。",
   [("领贴带尖不好看。", "A pointy collar stay looks off.", "collar stay（领贴）"),
    ("选的时候翻过来看。", "Turn it inside out to check.", "inside out（翻过来）")]),
  ("一字露肩卫衣", "The Off-Shoulder Sweater", "00:34", "一字露肩卫衣转入领贴检查，领贴有没有固定线是判断品质的关键一步。",
   [("露肩卫衣查领贴。", "Check the facing on off-shoulder tops.", "facing（领贴）"),
    ("固定线是品质关键。", "The stay-stitch is key.", "stay-stitch（固定线）")]),
  ("领贴固定线", "The Stay-Stitch", "00:34", "看它领贴有没有固定线，像这一件就是没有的，很容易穿的时候领贴就向外翻出来。",
   [("领贴要有固定线。", "The stay needs a fixing stitch.", "fixing stitch（固定线）"),
    ("没固定线就外翻。", "Without it, the stay flips out.", "flip out（外翻）")]),
  ("结尾：手工缝两下", "Ending: Two Hand Stitches", "00:47", "590 这么贵的价格，你手工在这块缝两下不行吗？细节决定值不值这个价。",
   [("贵价衣服更该看细节。", "Expensive pieces should nail details.", "price（价格）"),
    ("缝两下就能解决。", "Two stitches would fix it.", "stitch（缝）")]),
 ],
),
(
 "uniqlo-wireless-bra-fit", "无钢圈内衣怎么避免空杯跑杯不贴合", "Wireless Bras: Stop the Gapping", "2分31秒", "服装 · 内衣选购", "http://xhslink.cn/o/5uLsuxeapBM",
 [
  ("开场：支撑性设计", "Opening: Support Design", "00:00", "选无钢圈内衣一定要注意看它的支撑性设计够不够，一旦支撑性跟不上就容易空杯、跑杯、不贴合。",
   [("看支撑性设计够不够。", "Check the support structure.", "support（支撑）"),
    ("支撑不足就空杯跑杯。", "Weak support causes gapping.", "gap（空杯）")]),
  ("位置一：杯侧影裂网", "Spot One: The Side Mesh", "00:18", "穿内衣总是空杯不贴合，主要是和杯侧这块影裂网的设计有关，小方形网格穿上后使胸部向内收拢。",
   [("空杯与杯侧网有关。", "Gapping ties to the side mesh.", "mesh（网）"),
    ("网格收拢胸部。", "The grid gently cups the bust.", "gather（收拢）")]),
  ("贴合杯垫", "Hug the Cup", "00:34", "网格顺着胸部的曲线贴腹势力，让胸部牢牢抓住杯垫，这样既不会空杯跑杯也不会偏移。",
   [("顺着曲线贴合杯垫。", "It follows the curve and holds.", "follow the curve（贴合曲线）"),
    ("杯垫不跑不移位。", "The pad stays put.", "stay put（不移动）")]),
  ("位置二：侧比张力网", "Spot Two: Side-Panel Tension Mesh", "00:43", "无钢圈内衣如果这块张力网支撑力不够，副乳容易跑出来还显得臃肿，它的作用是牢牢收住副乳。",
   [("张力网收住副乳。", "The tension mesh tucks the side bust.", "side bust（副乳）"),
    ("从侧边托住胸部。", "It lifts from the sides.", "lift（托住）")]),
  ("位置三：背部轻力网", "Spot Three: The Back Mesh", "01:00", "背部轻力网面料轻薄，穿上紧身衣服也很难透出痕迹，还做了压胶设计，抬手弯腰不卷边。",
   [("背网轻薄不透痕。", "The back mesh stays invisible.", "invisible（看不见的）"),
    ("压胶设计不卷边。", "Taped edges never roll.", "taped（压胶的）")]),
  ("弧形托片杯垫", "The Curved Support Pad", "01:16", "杯垫专为嘟嘟杯设计，边缘加了一块弧形托片，高回弹杯垫灵活适配各种胸形，承托率好。",
   [("杯垫边缘加托片。", "A curved tab supports the edge.", "support tab（托片）"),
    ("高回弹适配胸形。", "High-rebound foam fits any shape.", "high-rebound（高回弹）")]),
  ("W型弹力纱", "The W-Shape Sling", "01:40", "胸杯底部这块 W 型弹力纱，不仅支撑性好还自带高回弹，能稳稳承托住整个胸部往下的重量。",
   [("W型纱承托胸部。", "The W-sling holds the bust.", "sling（托带）"),
    ("高回弹稳稳托住。", "Its rebound supports all day.", "rebound（回弹）")]),
  ("面料与固定", "Fabric and Fixing", "01:51", "整体高弹面料软乎乎糯叽叽，透气性在线；杯垫上下都做固定，日常穿不容易移位。",
   [("高弹面料软糯透气。", "The high-stretch fabric is soft and airy.", "airy（透气的）"),
    ("杯垫上下固定防移位。", "Pads are locked top and bottom.", "lock（固定）")]),
 ],
),
(
 "wool-real-fake-check", "服装内行人教你一招辨别羊毛真假", "One Trick to Spot Real Wool Coats", "1分12秒", "服装 · 羊毛鉴别", "http://xhslink.cn/o/8nFYqnUoaAF",
 [
  ("开场：都是假的", "Opening: They're All Fake", "00:00", "假的假的都是假的，教大家一招轻松辨别羊毛大衣真假，就看吊牌和水洗标。",
   [("教一招辨别真假。", "One trick to tell real from fake.", "real from fake（真假）"),
    ("就看吊牌和水洗标。", "Check the tag and care label.", "care label（水洗标）")]),
  ("开场挂架全景", "The Rack Overview", "00:04", "开场挂架全景点题「轻松辨别羊毛大衣真假」，接下来分别看成分、执行标准和安全类别。",
   [("挂架全景点题。", "The rack wide shot sets the theme.", "theme（主题）"),
    ("三看辨真伪。", "Three checks tell the truth.", "check（检查）")]),
  ("看水洗标", "Read the Care Label", "00:05", "真正的羊毛大衣面料一定写的是绵羊毛或羊毛，但凡加了产地或支数的都不靠谱。",
   [("正品写绵羊毛或羊毛。", "Real ones say sheep's wool.", "wool（羊毛）"),
    ("加产地支数的都不靠谱。", "Adding origin or count is a red flag.", "red flag（危险信号）")]),
  ("花哨命名一律假", "Fancy Names Are Fake", "00:16", "像澳洲超细羊毛、高支羊毛等等都不规范，一律按假看待，宁可错杀不可被骗。",
   [("花哨命名不规范。", "Fancy names break the rules.", "fancy（花哨的）"),
    ("宁可错杀不可被骗。", "Better safe than sorry.", "better safe than sorry（宁可错杀）")]),
  ("看吊牌两项", "Two Tag Checks", "00:23", "吊牌要重点关注两项：执行标准和安全类别。女装羊毛大衣执行标准只认 FZT81007-2017。",
   [("吊牌看执行标准。", "Check the standard number.", "standard（标准）"),
    ("女装只认一个标准号。", "Women's coats use one standard.", "specification（规格）")]),
  ("标准号辨真伪", "Standard Numbers Tell All", "00:32", "其他的数字像 2022、2010 等直接壁垒，碰到 2009 不是很多年前的尾货，就是假货。",
   [("其他数字都别信。", "Other numbers are unreliable.", "unreliable（不可靠的）"),
    ("2009 就是假货。", "2009 means it's fake.", "fake（假货）")]),
  ("男装标准", "The Men's Standard", "00:47", "男装羊毛大衣也要警惕，执行标准只认 FZT81008-2017，其他的都要小心。",
   [("男装也有专门标准。", "Men's coats have their own.", "men's（男装的）"),
    ("只认官方标准号。", "Trust only the official number.", "official（官方的）")]),
  ("安全类别", "The Safety Category", "00:54", "安全类别一定要有这一项，而且一定要认准 GB18401-2010，没有明确标注的不是次品就是假货。",
   [("安全类别必须有。", "The safety class is a must.", "safety（安全）"),
    ("没标注就是次品假货。", "Missing it means substandard goods.", "substandard（次品）")]),
 ],
),
(
 "clothes-one-detail-quality", "挑衣服真的有那么难吗？一个细节辨好坏。", "One Detail Tells Quality", "1分13秒", "服装 · 工艺辨识", "http://xhslink.cn/o/2XWcTllJ4b2",
 [
  ("开场：袖口斜度", "Opening: Sleeve Angle", "00:00", "这种显瘦，这种显胖。去选这种袖口斜度小的，越接近水平线越容易藏肉。",
   [("袖口斜度影响显瘦。", "Sleeve angle affects slimming.", "sleeve angle（袖口斜度）"),
    ("斜度小接近水平线。", "Smaller angle means closer to level.", "level（水平）")]),
  ("斜度大显壮", "Steep Angles Look Broad", "00:09", "短袖千万别选袖口斜度大的，斜度越大手臂最粗的地方暴露得越多，越显胖显壮。",
   [("斜度大暴露手臂。", "Steep angles expose the arm.", "expose（暴露）"),
    ("越显胖显壮。", "It reads broader and heavier.", "broad（显壮）")]),
  ("对比高下立显", "The Side-by-Side", "00:21", "更直观的对比一下，是不是高下立显？差的、好的，一眼分辨。",
   [("一对比高下立显。", "The comparison says it all.", "comparison（对比）"),
    ("一眼就能分辨。", "You can tell at a glance.", "at a glance（一眼）")]),
  ("双省带看缝", "Double-Welt: Check the Seam", "00:25", "一眼分辨双省带好坏，就看中间的这条缝：张着嘴漏着缝合不拢的就是差的。",
   [("双省带看中间缝。", "Check the center seam.", "welt（省带）"),
    ("张着嘴就是不拢。", "A gaping seam is defective.", "gaping（张开的）")]),
  ("做工好的闭合", "A Good Seam Closes", "00:34", "真正做工好的双省带，中间这条线应该是上下紧紧闭合的。",
   [("好做工线紧闭合。", "Good work closes the line.", "close（闭合）"),
    ("该打回去重新做。", "That one needs redoing.", "redo（返工）")]),
  ("洗水工艺拉头", "The Washed Zipper Pull", "00:39", "看到发白发旧做过洗水工艺的衣服都要长心眼，一定要去看拉头，像这种脏脏旧旧的就是洗坏的。",
   [("洗水衣服看拉头。", "Check the pull on washed clothes.", "zipper pull（拉头）"),
    ("脏旧拉头是洗坏的。", "Tarnished pulls mean a bad wash.", "tarnish（失去光泽）")]),
  ("洗水原理", "What Washing Does", "00:51", "洗水工艺不是简单用水洗，而是加洗涤剂、双氧水、生物酶把面料去浆变软定型，金属拉头没包好就会褪色。",
   [("洗水用化学助剂。", "Washing uses chemical agents.", "agent（助剂）"),
    ("拉头没包好会褪色。", "Unprotected metal pulls fade.", "fade（褪色）")]),
  ("包好才不伤", "Protected Pulls Survive", "01:08", "如果说包好了，出来就会像原来一样保持它本来的颜色。",
   [("包好的拉头不变色。", "Protected pulls keep their color.", "protect（保护）"),
    ("保持原本颜色。", "The original color stays.", "original（原本的）")]),
 ],
),
(
 "cheap-luxury-knitwear", "如何快速锁定便宜显贵针织衫", "Find Cheap Knitwear That Looks Expensive", "2分10秒", "服装 · 针织衫选购", "http://xhslink.cn/o/klXnNncUli",
 [
  ("开场：四个点", "Opening: Four Points", "00:00", "教大家用四个点锁定便宜还显贵的针织衫，老规矩先说面料。",
   [("用四点锁定针织衫。", "Four points lock in a good knit.", "knitwear（针织衫）"),
    ("老规矩先说面料。", "Fabric first, as always.", "fabric（面料）")]),
  ("混纺优先", "Blends First", "00:06", "春夏针织衫全棉或棉混纺最常见，建议首选混纺类：全棉排汗性能差且容易缩水褪色。",
   [("首选棉混纺。", "Blends are the first pick.", "blend（混纺）"),
    ("纯棉排汗差易缩水。", "Pure cotton sweats and shrinks.", "shrink（缩水）")]),
  ("莫代尔的优点", "The Modal Advantage", "00:17", "加了莫代尔纤维的混纺，吸湿排汗性能非常好，中高端睡衣特别喜欢用。",
   [("莫代尔吸湿排汗好。", "Modal wicks moisture well.", "wicks（吸湿排汗）"),
    ("中高端睡衣爱用。", "Premium sleepwear loves it.", "sleepwear（睡衣）")]),
  ("互补才出效果", "Complement, Don't Replace", "00:29", "纯莫代尔做针织衫板型太垂太软没形，跟棉混纺综合一下正好互补：保留棉的舒适又有莫代尔排汗。",
   [("纯莫代尔太软没形。", "Pure modal drapes shapelessly.", "shapeless（没形的）"),
    ("混纺互补出效果。", "Blending covers both weak spots.", "complement（互补）")]),
  ("密织工艺", "The Compaction Finish", "00:53", "防止变形所有边缘位置要检查，尤其袖口和下摆，选做过密织工艺的，保证回弹性避免变形。",
   [("边缘要做密织。", "Edges need compaction.", "compaction（密织）"),
    ("密织保证回弹性。", "It keeps the stretch and shape.", "elasticity（回弹性）")]),
  ("领脚收针", "The Collar Decrease", "01:09", "中高端针织衫的领脚这一块都是用的收针减针工艺，达到丝滑过渡提升整体精致度。",
   [("领脚用收针工艺。", "Collars use a gradual decrease.", "decrease（减针）"),
    ("丝滑过渡显精致。", "Smooth transitions look refined.", "refined（精致的）")]),
  ("收花针工艺", "Stitch-Shaping Craft", "01:29", "领口、前后袖笼、肩线多关注收花针工艺，这些工艺是为了更好地贴合人体曲线。",
   [("收花针贴合曲线。", "Shaping stitches hug the body.", "fit the body（贴合身体）"),
    ("工艺决定穿感。", "Craft decides how it wears.", "craft（工艺）")]),
  ("价格与质感", "Price and Value", "01:55", "优衣库这款 149，面料做工整体挺可以，颜色也丰富可以搭配不同风格，大家觉得值吗？",
   [("149块性价比不错。", "At 149 yuan it's solid value.", "value（性价比）"),
    ("颜色丰富好搭配。", "Rich colors match many styles.", "match（搭配）")]),
 ],
),
(
 "clothes-price-quality", "只谈做工不谈价格的都是在“耍流氓”", "Quality Without Price Is Nonsense", "52秒", "服装 · 性价比", "http://xhslink.cn/o/8RBIhcVMeYc",
 [
  ("开场：不值", "Opening: Not Worth It", "00:00", "109 不值，129 不值，299 更不值。谈衣服要结合价格看做工，只说做工不说价格就是耍流氓。",
   [("只谈做工不谈价是耍流氓。", "Talking craft without price is silly.", "craft（做工）"),
    ("价格做工要一起看。", "Price and craft go together.", "price（价格）")]),
  ("价签特写", "The Price Tag Close-Up", "00:01", "价签特写 RMB 129，先判 109 不值，再切到叠穿抽褶款配 299 更不值。",
   [("129的价签判不值。", "At 129, the tag fails the value test.", "value test（价值测试）"),
    ("299更不值。", "299 is even worse value.", "worse（更差）")]),
  ("领口翘起", "The Upward Collar", "00:03", "T 恤的领口挂在衣架上这种翘起来的，而不是像这种趴在衣架上的，这种不要选。",
   [("领口翘起不要选。", "Skip collars that pop up.", "pop up（翘起）"),
    ("趴在衣架上才好。", "Flat collars lie nicely.", "flat（平整的）")]),
  ("上身也翘", "It Stays Popped", "00:11", "这种你穿到身上多半也是这样翘起来的，领口上全是这种抽褶的，夏天千万别买。",
   [("上身照样翘。", "It stays popped when worn.", "worn（穿着）"),
    ("抽褶领口显乱。", "Puckered collars look messy.", "pucker（抽褶）")]),
  ("视觉胖20斤", "Instantly Plus Twenty", "00:17", "这种款式能让你原地视觉上胖 20 斤不止，一点都不夸张，还要 299 呢，39 都别卖。",
   [("款式让你视觉胖。", "The cut adds visual pounds.", "visual（视觉的）"),
    ("39都不值。", "Not even worth 39.", "worth（值得）")]),
  ("螺纹回弹性", "Rib Rebound", "00:24", "明明买的时候气息也端正，为什么后期气息会变形？就出在这个螺纹上，螺纹好坏买前一定要撑两下。",
   [("变形出在螺纹上。", "The ribbing causes the warp.", "ribbing（螺纹）"),
    ("买前要撑两下试回弹。", "Stretch it to test the rebound.", "rebound（回弹）")]),
  ("回弹差必变形", "Weak Rebound Warps", "00:35", "轻轻撑两下它都变形的，后期洗 3 到 5 次肯定会变形，因为它的回弹性比较差。",
   [("撑一下就变形。", "One stretch and it warps.", "stretch（拉伸）"),
    ("洗几次必变形。", "A few washes finish it.", "wash（清洗）")]),
  ("秒回弹才值得", "Snap-Back Is Worth It", "00:46", "109 这个不值，还不如地摊上 39 块钱的呢，去选这种秒回弹的，你撑多少次都是秒回弹的。",
   [("不如地摊39块的。", "A 39-yuan street find beats it.", "street find（地摊货）"),
    ("选秒回弹的。", "Choose instant snap-back.", "snap back（回弹）")]),
 ],
),
(
 "zara-efficient-shopping", "ZARA就该这么逛，快准省。", "How to Shop ZARA Fast and Smart", "47秒", "服装 · 品牌选购", "http://xhslink.cn/o/2U0sT2imj3g",
 [
  ("开场：四个档位", "Opening: Four Tiers", "00:00", "入门款、基础款、质感款、高端款，ZARA 就该这么逛，直接看吊牌。",
   [("ZARA分四个档位。", "ZARA has four tiers.", "tier（档位）"),
    ("直接看吊牌。", "Just read the tag.", "tag（吊牌）")]),
  ("方法落地", "The Method in Action", "00:05", "翻开领标，左上角标注三角标 TRF 系列，底部字幕强调直接看领标。",
   [("翻开领标看系列。", "Flip the label and check the line.", "label（领标）"),
    ("三角标是TRF系列。", "The triangle marks the TRF line.", "line（系列）")]),
  ("三角标入门", "Triangle: Entry", "00:04", "后面如果是三角形代表入门款，质量一般属于基础系列，款式偏年轻潮流，尺码偏小。",
   [("三角形是入门款。", "A triangle marks entry tier.", "triangle（三角形）"),
    ("质量一般尺码偏小。", "Basic quality, smaller sizing.", "basic（基础的）")]),
  ("方形标基础", "Square: Standard", "00:14", "正方形代表基础款或标准款，比三角标质量高一些，偏日常也是店里的主流款，款式更多。",
   [("正方形是基础款。", "A square means standard.", "square（正方形）"),
    ("比入门款质量高。", "Better than the entry tier.", "better（更好的）")]),
  ("圆圈标质感", "Circle: Quality", "00:25", "圆圈代表偏质感款，版型面料做工都还不错，这一类更多是区域为职场人设计的，偏成熟线合身款居多。",
   [("圆圈是质感款。", "A circle marks quality pieces.", "circle（圆圈）"),
    ("为职场人设计。", "Made for professionals.", "professional（职场人）")]),
  ("丝绒标高端", "The Premium Mark", "00:35", "后面如果是这种似模不似料的，代表高端线高端款，面料版型做工全在线，对标设计师线。",
   [("丝绒标是高端款。", "The premium mark is high-end.", "premium（高端的）"),
    ("对标设计师线。", "It rivals designer lines.", "designer（设计师）")]),
  ("STUDIO 字母标", "The STUDIO Label", "00:36", "字母标 STUDIO 系列是高端线的标志，领标中央印着 STUDIO 字样，面料版型做工全在线。",
   [("STUDIO是高端线标志。", "STUDIO marks the high-end line.", "high-end（高端）"),
    ("做工全在线。", "Craft is fully on point.", "on point（在线）")]),
  ("收完不补", "Limited Runs", "00:43", "这一类一般每个季度出的比较少，而且基本上收完不补，看到就下手。",
   [("高端款量少。", "High-end runs are small.", "limited（限量）"),
    ("收完基本不补。", "Once gone, rarely restocked.", "restock（补货）")]),
 ],
),
(
 "weipang-pants-selection", "微胖女生选裤子 一篇搞定！", "Curvy Girls: The One Pants Guide", "2分08秒", "服装 · 微胖选购", "http://xhslink.cn/o/34VkUWoIjCc",
 [
  ("开场：作弊小技巧", "Opening: A Cheat Trick", "00:00", "微胖女生买裤子有个作弊小技巧：将一条裤腿放到另一条裤腿里，然后从侧面看裆部。",
   [("裤腿塞裤腿侧面看。", "Fold one leg into the other, view the side.", "fold（折叠）"),
    ("裆部形状暴露品质。", "The crotch shape tells all.", "crotch（裆部）")]),
  ("微型裆 vs 大优型裆", "V-Crotch vs U-Crotch", "00:05", "如果裆部是这种微型裆，差的别选；如果是圆润的大优型裆，好的首选。",
   [("微型裆是差的。", "A V-crotch is a bad sign.", "V-crotch（V型裆）"),
    ("大优型裆是好的。", "A rounded U-crotch is best.", "U-crotch（U型裆）")]),
  ("微型裆卡裆", "V-Crotch Rides", "00:08", "微型裆穿上必然卡裆，而且走路时这块容易磨大腿根部，因为人都是有一定厚度的。",
   [("微型裆必然卡裆。", "V-crotches always ride up.", "ride up（卡裆）"),
    ("磨大腿根部。", "It chafes the inner thigh.", "chafe（摩擦）")]),
  ("照顾微胖体型", "Room for Real Bodies", "00:25", "微胖女生前面有小肚子后面有翘臀，大腿根部还粗，圆润的大优型裆空间更足，完全照顾到体型。",
   [("大U裆空间更足。", "A U-crotch leaves room.", "room（空间）"),
    ("舒适不勒不卡。", "Comfortable, no squeeze.", "comfortable（舒适的）")]),
  ("面料三字诀", "Fabric: Soft, Drape, Stretch", "00:38", "第二挑面料记住三个字：软、垂、弹。面料选软不选硬，牛仔这种硬挺面料就别选。",
   [("面料选软不选硬。", "Choose soft over stiff.", "stiff（硬挺的）"),
    ("硬面料显厚重。", "Stiff fabric adds bulk.", "bulk（厚重）")]),
  ("侧裁片显瘦", "The Side Panel Slims", "00:57", "这种裤身比别人多踩的一个裁片出来，相当于把裤侧空间转移，能巧妙视觉上收窄胯宽。",
   [("多一个裁片收胯宽。", "An extra panel narrows the hips.", "panel（裁片）"),
    ("视觉上收窄。", "It visually slims the hip line.", "slim（显瘦）")]),
  ("垂弹面料", "Drape and Stretch", "01:11", "面料光是软不行还得垂，垂的面料顺着身体往下走不贴肉；还要高弹，横向竖向都有弹力。",
   [("垂的面料不贴肉。", "Drapey fabric floats off the body.", "drape（垂坠）"),
    ("高弹不勒肉。", "High stretch never pinches.", "stretch（弹力）")]),
  ("高腰显瘦", "High-Rise Slims", "01:42", "想显瘦避入高腰款，微胖女生横向宽更应该加长纵向长度，抬高腰线优化身材比例。",
   [("高腰款显瘦。", "High-rise waists slim.", "high-rise（高腰）"),
    ("腰线拉长比例。", "A raised waist lengthens the line.", "proportion（比例）")]),
 ],
),
]

def paraphrase_for(sentences):
    out = []
    for zh, en, note in sentences:
        word = note.split("（")[0].strip()
        out.append([f"用{word}换一种说法", en])
    return out

def main():
    for slug, title, title_en, duration, topic, url, scenes in V:
        data = {
            "meta": {
                "slug": slug, "title": title, "title_en": title_en,
                "duration": duration, "scenes": len(scenes),
                "sentences": sum(len(s[4]) for s in scenes),
                "date": DATE, "platform": PLATFORM, "source_url": url, "topic": topic,
            },
            "scene_imgs": [f"shot-{i+1:02d}" for i in range(len(scenes))],
            "scenes": [],
        }
        for i, (tc, te, t, ctx, sents) in enumerate(scenes, 1):
            data["scenes"].append({
                "id": f"s{i}", "title_cn": tc, "title_en": te, "time": t,
                "context": ctx,
                "sentences": [list(s) for s in sents],
                "paraphrase": paraphrase_for(sents),
                "speak": " ".join(en for _, en, _ in sents),
            })
        data["practice"] = []
        data["pitfalls"] = []
        data["shifts"] = []
        data["difficult_words"] = []
        data["footer_notes"] = f"来源：{title}（小红书，时长{duration}）"
        p = OUT / f"{slug}.json"
        p.write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"✓ {slug} {len(scenes)} scenes")

if __name__ == "__main__":
    main()
