#!/usr/bin/env python3
"""b37 JSON 生成脚本：剪辑/摄影/电影/面料选购混合类（10篇）"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "scripts" / "scene-data"
OUT.mkdir(parents=True, exist_ok=True)

DATE = "2026-08-08"
PLATFORM = "xiaohongshu"

V = [
(
 "beauty-voiceover-editing", "美妆口播怎么剪？把握本质才好出效果", "How to Edit Beauty Voiceovers: Master the Essence", "3分58秒", "剪辑 · 口播拉片", "http://xhslink.cn/o/6KGBPbpcO9I",
 [
  ("开场：拉片学剪辑", "Opening: Learn Editing by Breaking Down", "00:00", "拉片是提升剪辑水平最快的方式之一，今天带大家拆解一个美妆口播博主的前30秒钩子设计。",
   [("拉片是提升剪辑最快的方式。", "Breaking down edits is the fastest way to improve.", "break down（拆解）"),
    ("今天拆解美妆口播的前30秒。", "Today we break down the first 30 seconds.", "voiceover（口播）")]),
  ("钩子留住粉丝", "The Hook That Holds Viewers", "00:10", "开篇是一句简单明了的钩子，直接把对话题感兴趣的粉丝留住，这是口播的第一道关卡。",
   [("开场要设计钩子。", "Open with a clear hook.", "hook（钩子）"),
    ("把感兴趣的粉丝留住。", "Hold the viewers who care about the topic.", "hold（留住）")]),
  ("文案即剪辑蓝图", "The Script Is the Edit Blueprint", "00:21", "博主写文案时就已构思好剪辑内容，想好字幕入场动画，花字从左右滑进搭配叮的音效。",
   [("写文案时就构思剪辑。", "The script pre-plans the edit.", "blueprint（蓝图）"),
    ("花字配入场动画和音效。", "Animated captions come with a ding.", "caption（花字）")]),
  ("账号背书两作用", "The Two Roles of an Account Endorsement", "00:49", "账号背书有两个作用：一是给新观众做自我介绍让人知道你是干嘛的，二是帮老粉丝快速找到往期视频。",
   [("背书一是自我介绍。", "Endorsement one: introduce yourself.", "endorsement（背书）"),
    ("背书二是召唤老粉丝。", "Endorsement two: call back old fans.", "call back（召唤）")]),
  ("封面抠像动画", "Cutout Cover Animation", "01:22", "旧视频封面用关键帧动画从右往左，把人像抠出来放在前面，配合弹幕评论增加互动感。",
   [("封面用关键帧动画。", "Animate the cover with keyframes.", "keyframe（关键帧）"),
    ("把弹幕直接放在画面上。", "Layer the danmaku right on the frame.", "danmaku（弹幕）")]),
  ("双层抠像描边", "Two-Layer Cutout with Outline", "01:42", "把视频分两层：上层抠出人像加口型描边，下层关键帧动画缩小，做出有网感的效果。",
   [("上层抠像加描边。", "Cut out the top layer and outline it.", "outline（描边）"),
    ("下层用关键帧缩小。", "Shrink the bottom layer with keyframes.", "shrink（缩小）")]),
  ("博主本人背书", "The Creator's Own Endorsement", "02:15", "博主本人背书要告诉观众我为什么能站在这里讲，因为我去过90%以上的热门店亲身测过。",
   [("用经历建立信任。", "Use experience to build trust.", "trust（信任）"),
    ("我亲身测过才有资格讲。", "I tested it myself, so I can speak.", "credibility（可信度）")]),
  ("总结：把握本质", "Summary: Hold the Essence", "03:36", "花字、效果、音效都可以换，只要把握住本质，意思到了，效果自然就出来了。",
   [("花字音效都可以换。", "Captions and sounds are replaceable.", "replaceable（可替换的）"),
    ("把握本质效果自来。", "Hold the essence and effects follow.", "essence（本质）")]),
 ],
),
(
 "travel-telephoto-diff", "出门旅行，会不会用长焦的区别原来这么大", "Travel Photography: Telephoto Makes All the Difference", "57秒", "摄影 · 长焦旅拍", "http://xhslink.cn/o/3R83GkhjXuy",
 [
  ("开场：背景拍大", "Opening: Make the Background Big", "00:00", "跟纪念碑合影想连背景一起拍大，别急着往前站，先请摄影师一直往后退。",
   [("想把背景拍大一些。", "You want the background bigger.", "background（背景）"),
    ("先请摄影师往后退。", "First have the photographer step back.", "step back（后退）")]),
  ("退到十米开外", "Back Up Ten Meters", "00:18", "一直退退退到十米开外，放心大胆地退，退得越多背景越大。",
   [("退到十米开外。", "Back up past ten meters.", "ten meters（十米）"),
    ("退得越多背景越大。", "The farther back, the bigger the background.", "the farther（越远）")]),
  ("切长焦焦段", "Switch to the Telephoto Lens", "00:26", "退好之后再切到手机或相机的长焦焦段，比如六倍变焦，人物大小不变但背景被拉近放大。",
   [("再切到长焦焦段。", "Now switch to the telephoto setting.", "telephoto（长焦）"),
    ("六倍变焦拉近背景。", "Six-times zoom pulls the background in.", "zoom（变焦）")]),
  ("平行运镜", "Slow Pan Along the Line", "00:30", "切完长焦后沿着平行方向缓慢运镜，让画面有一种航拍一样的推进感。",
   [("沿平行方向缓慢运镜。", "Pan slowly along the parallel line.", "pan（运镜）"),
    ("运镜增加画面动感。", "Movement adds life to the frame.", "motion（动感）")]),
  ("双屏对照", "Split-Screen Comparison", "00:44", "同场景双屏对照：长焦压缩背景，广角拉开空间，湖面占比明显放大。",
   [("长焦压缩背景。", "Telephoto compresses the background.", "compress（压缩）"),
    ("广角拉开空间。", "Wide angle expands the space.", "expand（拉开）")]),
  ("原理：长焦压缩", "Why It Works: Compression", "00:39", "远距离加长焦让背景看起来更近更大，人和背景的比例一下拉开，照片更有层次。",
   [("长焦让背景更近。", "Telephoto brings the background closer.", "compression（压缩）"),
    ("比例拉开层次更丰富。", "The ratio shift adds depth.", "depth（层次）")]),
  ("设备端收束", "Gear-Side Wrap-Up", "00:54", "切长焦后背景更大、更壮观，这就是出门旅行用长焦的区别。",
   [("切长焦后背景更壮观。", "Telephoto makes the backdrop spectacular.", "spectacular（壮观的）"),
    ("这就是长焦的区别。", "That's the telephoto difference.", "difference（区别）")]),
  ("结语：学会了吗", "Closing: Did You Learn It?", "00:53", "这个旅拍小技巧你学会了吗？下次出去旅行拍照就试试。",
   [("这个技巧你学会了吗。", "Did you pick up this trick?", "pick up（学会）"),
    ("下次旅行就试试。", "Try it on your next trip.", "try it（试试）")]),
 ],
),
(
 "joker-film-pull-mid", "《小丑》拉片完整版-中集", "Joker: A Full Scene-by-Scene Breakdown, Part 2", "13分27秒", "电影 · 视听语言", "http://xhslink.cn/o/3QMhwfYtxPQ",
 [
  ("开场：操控情绪", "Opening: Controlling Emotion Through Frame", "00:00", "好的电影导演如何通过画面操控观众的观影情绪？继续用小丑来分析导演的工作。",
   [("导演用画面操控情绪。", "Directors steer emotion through images.", "steer（操控）"),
    ("继续拆解小丑。", "We keep breaking down Joker.", "break down（拆解）")]),
  ("综合艺术", "Film Is a Synthetic Art", "00:24", "电影是综合艺术，摄影音效音乐美术服装化妆缺一不可，而最直接影响观众的是摄影画面和音乐音效。",
   [("电影是综合艺术。", "Film is a synthetic art.", "synthetic art（综合艺术）"),
    ("画面和声音最直接。", "Image and sound hit viewers first.", "direct（直接的）")]),
  ("音画结合", "Sound-Meets-Picture Technique", "00:39", "音效不只是给画面配音，把听和视并列是因为听不只是视的附属，音效可以独立制造情绪。",
   [("音效不只是配音。", "Sound is more than dubbing.", "dub（配音）"),
    ("听与视并列。", "Sound sits beside image.", "sight and sound（视听）")]),
  ("声效提前手法", "The Sound-Ahead Technique", "01:39", "导演把下一场戏踹垃圾箱的音效提前到老板训话的画面里，让观众感到亚瑟心里的怒火已经烧起来。",
   [("把下一场音效提前。", "Play the next scene's sound early.", "sound ahead（声音前置）"),
    ("声音预告内心怒火。", "The sound previews the rage inside.", "preview（预告）")]),
  ("心跳音效与推进", "Heartbeat and the Push-In", "01:51", "镜头朝亚瑟缓缓推进，老板声音压低，一个心跳音效渐渐引入，随镜头越推越响。",
   [("镜头缓缓推进。", "The camera pushes in slowly.", "push in（推进）"),
    ("心跳音效渐入。", "A heartbeat sound fades in.", "fade in（淡入）")]),
  ("越轴手法", "Crossing the Axis", "02:58", "这场戏大多遵守轴线规则，但最后一个镜头摄影机忽然越到轴线对面，用故意越轴制造人物立场。",
   [("多数镜头遵守轴线。", "Most shots respect the axis.", "axis（轴线）"),
    ("故意越轴制造立场。", "Crossing it on purpose builds tension.", "cross the axis（越轴）")]),
  ("为什么需要轴线", "Why the Axis Exists", "03:20", "同一场景镜头不停切换，观众需要轴线来记住人物的相对位置，不越轴才不会产生混乱。",
   [("轴线帮观众记住位置。", "The axis helps viewers track positions.", "track（追踪）"),
    ("不越轴就不混乱。", "Staying on-axis keeps the space clear.", "on-axis（轴上）")]),
  ("情绪低净的感染力", "The Power of the Emotional Climb", "06:30", "从隐忍到不耐烦再到怒火，情绪递进通过画面和声音被精准传递，这就是视听语言的魅力。",
   [("情绪一步步递进。", "Emotion climbs step by step.", "climb（递进）"),
    ("视听语言传递情绪。", "Sight and sound carry the mood.", "carry（传递）")]),
 ],
),
(
 "focal-length-photo-story", "焦段怎么选，一组照片才好看", "Pick Focal Lengths So a Photo Set Tells a Story", "2分17秒", "摄影 · 焦段叙事", "http://xhslink.cn/o/88ZiDwshXqD",
 [
  ("开场：单张都好看", "Opening: Pretty Singles, Flat Set", "00:00", "单看每张都很好看，但放一起感觉都差不多——因为拍摄时就没挪过地方，焦段一直没换。",
   [("单张好看组照平淡。", "Each photo is fine, but the set feels flat.", "flat（平淡）"),
    ("因为焦段一直没换。", "The focal length never changed.", "focal length（焦段）")]),
  ("视角单一", "One Viewpoint, Repeats", "00:07", "视角单一，拍再多也都一样，每张照片都在重复同一件事。",
   [("视角单一拍多少都一样。", "One viewpoint repeats itself.", "viewpoint（视角）"),
    ("照片重复同一件事。", "Every shot repeats the same thing.", "repeat（重复）")]),
  ("第一张：环境", "Shot One: Wide Environment", "00:23", "站远一点拍第一张，把咖啡馆或书店的环境带进去，别人一眼就知道你今天在哪。",
   [("第一张拍环境。", "First, capture the environment.", "environment（环境）"),
    ("别人一眼知道你在哪。", "People instantly see where you are.", "instantly（立刻）")]),
  ("第二张：人物", "Shot Two: The Person", "00:29", "走近一点换焦段拍人，人和环境都能看清，这种照片最适合发朋友圈。",
   [("走近一点拍人物。", "Move closer and shoot the person.", "move closer（走近）"),
    ("人和环境都能看清。", "Both person and place are visible.", "visible（可见的）")]),
  ("第三张：表情", "Shot Three: The Expression", "00:40", "再近一点拍表情，背景少了大家第一眼就看到你的表情，想拍人的状态这组特别合适。",
   [("再近一点拍表情。", "Closer still, shoot the expression.", "expression（表情）"),
    ("背景少则表情突出。", "Less background, more face.", "stand out（突出）")]),
  ("最后：细节", "Last: The Details", "00:55", "不用拍脸，拍茶、拍手、拍书、拍窗边，这些不起眼的细节反而最容易让你回想今天。",
   [("拍茶拍手拍书。", "Shoot the tea, the hands, the book.", "detail（细节）"),
    ("细节最能勾起回忆。", "Details bring back memories best.", "memories（回忆）")]),
  ("四步万能公式", "The Four-Step Formula", "01:24", "不用带很多镜头，记住四步：远拍环境、近拍人物、再近拍表情、最后拍细节。",
   [("四步记住就够。", "Four steps are all you need.", "formula（公式）"),
    ("远中近加细节。", "Wide, close, closer, detail.", "sequence（顺序）")]),
  ("故事照片的本质", "The Essence of Story Photos", "01:46", "有故事的照片不是每一张都精彩，而是每一张都在告诉别人一点新的东西，合起来才是完整的故事。",
   [("每张都在补充新内容。", "Each shot adds something new.", "add（补充）"),
    ("合起来才是完整故事。", "Together they tell the whole story.", "whole story（完整故事）")]),
 ],
),
(
 "cinematic-font-free", "不开会员也能做电影感字体？0成本提升审美", "Cinematic Fonts Without a Membership", "1分34秒", "剪辑 · 字体设计", "http://xhslink.cn/o/6ufvFAs1zOn",
 [
  ("开场：字体神器", "Opening: Font Tools", "00:00", "很多人问 vlog 开头的字体设计怎么做，今天分享三个私藏的字体神器，让 vlog 开头提升质感。",
   [("vlog开头靠字体提质感。", "Fonts lift your vlog opening.", "quality（质感）"),
    ("分享三个字体神器。", "Here are three font secrets.", "font（字体）")]),
  ("工具一：动态字体网站", "Tool One: Dynamic Font Site", "00:08", "第一个是网站，里面有很多不同效果，输入文字就生成有设计感的动态字体。",
   [("输入文字生成动态字体。", "Type text, get animated fonts.", "animated（动态的）"),
    ("选你喜欢的直接使用。", "Pick the one you like.", "pick（挑选）")]),
  ("导出与抠图", "Export and Keying", "00:18", "静态可以直接保存，动态用导出功能下载；因为不是透明底，就设纯黑或纯白导出，再到剪映里色度抠图。",
   [("静态直接保存。", "Save static ones directly.", "save（保存）"),
    ("用色度抠图去掉底色。", "Key out the background color.", "chroma key（色度抠图）")]),
  ("工具二：灵感网站", "Tool Two: The Inspiration Site", "00:40", "第二个不是工具而是方法，字体灵感从何而来？平时没灵感就上网站刷一刷看一看。",
   [("字体灵感需要积累。", "Font inspiration needs accumulation.", "inspiration（灵感）"),
    ("没灵感就去刷网站。", "Browse the site when you're stuck.", "browse（浏览）")]),
  ("技巧一：混搭字体", "Tip One: Mix Fonts", "00:56", "我不会只用一个字体，开头和后面的字体分别用两个不同字体拼在一起，大小高低都可以调。",
   [("别只用一个字体。", "Don't settle on one font.", "mix（混搭）"),
    ("两个字体拼出独特性。", "Two fonts create uniqueness.", "uniqueness（独特性）")]),
  ("技巧二：复合片段加滤镜", "Tip Two: Compound Clip and Filter", "01:10", "字体设计排版好后新建复合片段，加上颗粒感或复古滤镜，让字体融入视频基调。",
   [("把字体合成复合片段。", "Nest the font into a compound clip.", "compound clip（复合片段）"),
    ("加颗粒滤镜融入基调。", "Add grain to blend the tone.", "grain（颗粒感）")]),
  ("技巧三：取色自画面", "Tip Three: Pick Colors From the Frame", "01:20", "字体颜色不要乱选，直接取画面里的主色调，或用画面的反差互补色，标题一眼突出。",
   [("字体颜色取自主色调。", "Pick the frame's dominant hue.", "dominant hue（主色调）"),
    ("互补色增加层次感。", "Complementary colors add depth.", "complementary（互补的）")]),
  ("结尾：点赞收藏", "Closing: Like and Save", "01:30", "今天的分享就到这里，如果对你有帮助记得点赞收藏，我们下期再见。",
   [("有帮助就点赞收藏。", "Like and save if it helps.", "save（收藏）"),
    ("我们下期再见。", "See you next time.", "see you（再见）")]),
 ],
),
(
 "winter-fabric-quality", "秋冬常见面料好坏分享", "Winter Fabrics: How to Tell Good from Bad", "1分42秒", "面料 · 选购知识", "http://xhslink.cn/o/MJyAAXCfxT",
 [
  ("开场：绒的区别", "Opening: Fleece Differences", "00:00", "德绒、抓绒、摇粒绒、珊瑚绒、羊羔绒这么多绒都有什么区别？哪个更保暖、哪个更具性价比？",
   [("绒的种类那么多。", "There are so many fleece types.", "fleece（绒）"),
    ("哪个更保暖更划算。", "Which is warmer and better value?", "value（性价比）")]),
  ("德绒的真相", "The Truth About Decron", "00:07", "德绒保暖性堪比羊绒，因为纤维之间能储存空气；但真正的德绒早已停产，市面上的都是沿用概念。",
   [("德绒靠空气保暖。", "Decron traps air for warmth.", "trap air（锁住空气）"),
    ("真德绒早已停产。", "Real Decron stopped production long ago.", "discontinued（停产）")]),
  ("停产判断", "The Discontinued Call", "00:20", "停产截图配样片特写，主讲人判定市面上的德绒只是概念复用，国内多用精润代替。",
   [("停产截图是证据。", "The notice screenshot is the proof.", "proof（证据）"),
    ("概念复用不是真德绒。", "Concept recycling isn't real Decron.", "recycle（复用）")]),
  ("三种绒是同一物", "Three Fleeces, One Fabric", "00:29", "抓绒、摇粒绒、珊瑚绒其实就是一样的东西，只是表面绒毛长短不同，像饮料的小杯中杯大杯。",
   [("三种绒本质相同。", "The three fleeces are the same thing.", "identical（相同的）"),
    ("只是绒毛长短不同。", "Only the pile length differs.", "pile（绒毛）")]),
  ("抓绒与摇粒绒", "Sherpa and Fleece Details", "00:42", "抓绒毛短多用于内衣，摇粒绒是长抓绒面料放进机器摇出颗粒感，多用于外套或内胆。",
   [("抓绒毛短做内衣。", "Short-pile sherpa lines underwear.", "underwear（内衣）"),
    ("摇粒绒摇出颗粒感。", "Fleece gets its pebbly feel from tumbling.", "pebbly（颗粒感的）")]),
  ("珊瑚绒与羊羔绒", "Coral and Lambswool Fleece", "00:59", "珊瑚绒毛细长特别柔软做睡衣；羊羔绒全名仿羊羔绒，是环保平绒毛衣常用的替代品。",
   [("珊瑚绒柔软做睡衣。", "Coral fleece is soft for pajamas.", "pajamas（睡衣）"),
    ("羊羔绒其实是仿的。", "Lambswool fleece is usually faux.", "faux（仿的）")]),
  ("静电问题", "The Static Problem", "01:13", "这些绒保暖好但都是化纤产品，极易产生静电，一定要选带导电丝或防静电处理的。",
   [("化纤绒易起静电。", "Synthetic fleece builds static easily.", "static（静电）"),
    ("选带防静电处理的。", "Choose anti-static treatments.", "anti-static（防静电）")]),
  ("品牌与平替", "Brands and Budget Alternatives", "01:23", "有个品牌在抓绒界独树一帜，因为它是抓绒鼻祖，带标的都贵；现在优衣库、迪卡侬等平替很多。",
   [("鼻祖品牌都带标。", "The pioneer brand charges a premium.", "pioneer（鼻祖）"),
    ("平替选择越来越多。", "Budget alternatives keep growing.", "alternative（平替）")]),
 ],
),
(
 "stitch-quality-clothes", "学会通过针迹轻松买到高品质显贵的衣服", "Judge Quality by the Stitches", "1分18秒", "服装 · 工艺辨识", "http://xhslink.cn/o/AqNHPsYWFpx",
 [
  ("开场：翻开袖口", "Opening: Flip the Cuff", "00:00", "衣服的袖口一定要翻开看一下里边，因为一件好品质的衣服出厂前最后一道工序是质检。",
   [("袖口翻开看里面。", "Flip the cuff and check inside.", "cuff（袖口）"),
    ("质检不允许多余线头。", "QC won't allow loose threads.", "quality control（质检）")]),
  ("质检视角", "The QC View", "00:11", "质检是不允许内侧有杂乱线迹的，内侧不干净就属于「不会被允许」的反例。",
   [("质检不允许杂乱线迹。", "QC never allows messy stitching.", "messy（杂乱的）"),
    ("内侧干净才是合格。", "A clean inside passes.", "pass（合格）")]),
  ("线头与虚线", "Threads and Loose Stitches", "00:14", "这么长的线头不说，周边还有很多虚线，虚线后期容易出现拖线的情况。",
   [("长线头是品质问题。", "Long threads signal poor quality.", "loose thread（线头）"),
    ("虚线后期会拖线。", "Loose stitches will unravel later.", "unravel（脱线）")]),
  ("一本针二本针", "Single-Stitch and Double-Stitch", "00:25", "一条明线叫一本针，是最基础最常见的；两条明线叫二本针，是品质不错的象征。",
   [("一条明线是一本针。", "One line of topstitching is single-stitch.", "topstitching（明线）"),
    ("两条明线叫二本针。", "Two lines make double-stitch.", "double-stitch（二本针）")]),
  ("针距规则", "Stitch Density Rules", "00:37", "面料越厚针距越宽，面料越薄针距越窄：风衣牛仔约三厘米十针，衬衣约三厘米十四五针。",
   [("厚面料针距宽。", "Thick fabric, wider stitch spacing.", "stitch spacing（针距）"),
    ("衬衣三厘米十四五针。", "Shirts run 14-15 stitches per 3cm.", "stitches（针数）")]),
  ("内里锁边线", "The Inner Seam Finish", "00:56", "衣服内里的锁边线迹一样，越密实越好，袖笼线走得顺滑流畅，穿身上就显品质。",
   [("内里锁边越密越好。", "Denser inner seams are better.", "seam（线迹）"),
    ("走线顺滑显品质。", "Smooth stitching reads as quality.", "smooth（顺滑）")]),
  ("走线歪歪扭扭", "Crooked Stitching Looks Cheap", "01:07", "走线歪歪扭扭的衣服穿身上就会显得很廉价，针迹是判断品质的快速入口。",
   [("走线歪显得廉价。", "Crooked lines look cheap.", "crooked（歪扭的）"),
    ("针迹是品质入口。", "Stitches are a fast quality check.", "quality check（品质检查）")]),
  ("受力处套结加固", "Bar-Tack Reinforcement", "01:12", "好品质的衣服所有受力地方都会用针线做套结加固，防止穿着时崩开。",
   [("受力处要套结加固。", "Stress points get bar-tacked.", "bar tack（套结）"),
    ("防止穿着时崩开。", "It stops the seams from bursting.", "burst（崩开）")]),
 ],
),
(
 "hoodie-buying-details", "最全卫衣购买小细节", "The Complete Hoodie Buying Guide", "3分40秒", "服装 · 选购细节", "http://xhslink.cn/o/AN6Q6X4965m",
 [
  ("开场：领口易变形", "Opening: The Collar Deforms", "00:00", "领口用 T恤或卫衣料子直接做的本布领，穿两次回去之后肯定会变形，要避开。",
   [("本布领口会变形。", "Self-fabric collars stretch out.", "self-fabric（本布）"),
    ("穿两次就变形。", "They warp after a couple of wears.", "deform（变形）")]),
  ("螺纹要秒回弹", "Ribbing Should Snap Back", "00:13", "全棉又稀松的螺纹不能选，要选弹性好、秒回弹、氨纶成分多的螺纹。",
   [("螺纹要弹性好。", "Choose stretchy ribbing.", "ribbing（螺纹）"),
    ("氨纶多回弹快。", "More spandex snaps back fast.", "spandex（氨纶）")]),
  ("双层帽更立体", "Double-Layer Hoods", "00:18", "单层帽软啪啪的缝缝都在外，双层帽更加立体挺阔，毛边都在内部，看着干净利索。",
   [("单层帽软趴趴。", "Single-layer hoods go limp.", "limp（软趴趴的）"),
    ("双层帽立体挺阔。", "Double layers stand up better.", "structured（挺阔的）")]),
  ("后领贴条", "The Back Neck Tape", "00:41", "后领的领贴条是好的卫衣T恤必不可少的，既能遮住做工，主要作用是固定领形。",
   [("领贴条必不可少。", "Neck tape is a must.", "neck tape（领贴条）"),
    ("它固定领形。", "It holds the collar's shape.", "fix the shape（固定领形）")]),
  ("通肩拉条", "Shoulder-to-Shoulder Tape", "00:53", "通肩拉条是领贴条的升级版，从领贴一直延伸到两侧肩上，固定效果最好。",
   [("通肩拉条是升级版。", "Full-width tape is the upgrade.", "upgrade（升级）"),
    ("延伸到肩上固定更好。", "Extending to the shoulders locks it down.", "extend（延伸）")]),
  ("插肩袖显瘦", "Raglan Sleeves Slim", "01:19", "特别大的插肩袖或落肩袖给人体加了一条分割线，所以会显瘦，休闲时尚感更强。",
   [("插肩袖多一条分割线。", "Raglan adds a visual seam.", "raglan（插肩）"),
    ("分割线显瘦更休闲。", "The seam slims and relaxes the look.", "slim（显瘦）")]),
  ("挂面与克重", "Facings and Fabric Weight", "01:44", "敞开穿的卫衣要选带挂面的，里面看不到作风毛缝；克重选三到四百克，不易皱有挺阔感。",
   [("带挂面才利落。", "Facings make the inside tidy.", "facing（挂面）"),
    ("三百到四百克最合适。", "300-400 grams is the sweet spot.", "fabric weight（克重）")]),
  ("扣眼与帽绳", "Eyelets and Drawstrings", "02:23", "衣字眼最基础常见，菊花眼和金属气眼都很好；帽舌选有螺丝加固的精致调节。",
   [("菊花眼金属眼更好。", "Riveted and metal eyelets are better.", "eyelet（扣眼）"),
    ("帽绳选精致调节扣。", "Choose a nice cord stopper.", "drawstring（帽绳）")]),
 ],
),
(
 "shirt-buying-details", "最全衬衣购买小细节", "The Complete Shirt Buying Guide", "2分35秒", "服装 · 选购细节", "http://xhslink.cn/o/EKwJLA15gN",
 [
  ("开场：扣眼方向", "Opening: Buttonhole Direction", "00:00", "上方的扣眼是竖开的，下方腰部最宽位置是横开的，因为这样抗拉力更强。",
   [("扣眼方向有讲究。", "Buttonholes face different ways.", "buttonhole（扣眼）"),
    ("横开抗拉力更强。", "Horizontal ones resist pulling better.", "resist（抵抗）")]),
  ("袖口开叉工艺", "Cuff Slit Craft", "00:06", "袖口开叉从中间剪开再包条的处理最差，后期容易变形；宝剑头开叉平整美观，长时间不变形。",
   [("简单包条容易变形。", "Simple bound slits deform.", "deform（变形）"),
    ("宝剑头开叉更耐穿。", "Lance-point slits last longer.", "lance point（宝剑头）")]),
  ("领子外翻", "The Collar Roll", "00:37", "衬衣领子要看一下有没有凸出口外翻，正常应该内扣，外翻会严重影响领形形成大小领。",
   [("领子应该内扣。", "Collars should roll inward.", "roll inward（内扣）"),
    ("外翻会形成大小领。", "Rolling out creates uneven collars.", "uneven（不均的）")]),
  ("贝壳扣加分", "Shell Buttons Add Points", "00:53", "差点的衬衣用塑料或树脂扣，好的衬衣才用天然贝壳扣，给基础衬衣加分。",
   [("塑料扣是入门级。", "Plastic buttons are entry-level.", "entry-level（入门级）"),
    ("贝壳扣天然加分。", "Shell buttons are a natural bonus.", "natural（天然的）")]),
  ("混纺的奥义", "The Blended Fabric Idea", "01:07", "混纺料子含量越少的纤维作用越关键，纯麻爱皱，加少量化纤抗皱又保持表面质感。",
   [("少量纤维起大作用。", "Small fibers do big work.", "blend（混纺）"),
    ("加化纤抗皱不廉价。", "A touch of synthetic resists wrinkles.", "wrinkle-resistant（抗皱）")]),
  ("护过肩双层", "Double-Layer Yoke", "01:40", "护过肩也叫护育克，双层设计搓起来立体挺阔、舒适度高又耐磨。",
   [("护过肩要双层。", "A double-layer yoke is better.", "yoke（过肩）"),
    ("双层立体又耐磨。", "Double layers are sturdy and comfy.", "durable（耐磨的）")]),
  ("细节用心", "Thoughtful Details", "01:57", "领子三厘米16针以上，胸前做隐形按扣防止活动量加大时崩开，优秀格调衣服四对齐。",
   [("胸前隐形按扣防崩开。", "Hidden snaps prevent popping.", "snap（按扣）"),
    ("四对齐是优秀格调。", "Four-way alignment marks quality.", "alignment（对齐）")]),
  ("条格四对齐", "Four-Way Alignment", "02:13", "优秀格调衣服看四对齐：左右大身对齐、口袋和大身对齐、袖子和大身对齐、前后大身对齐。",
   [("左右大身要对齐。", "Left and right panels line up.", "line up（对齐）"),
    ("口袋袖子都要对齐。", "Pockets and sleeves align too.", "pocket（口袋）")]),
 ],
),
(
 "clothes-avoid-awkward", "懂点衣服小常识，避免穿衣小尴尬。", "Clothing Know-How: Avoid Awkward Moments", "1分18秒", "服装 · 选购常识", "http://xhslink.cn/o/A8kold0bznm",
 [
  ("开场：小尴尬", "Opening: Small Awkward Moments", "00:00", "买回来的衣服是不是经常遇到这种小尴尬？其实买的时候注意几个小细节，这些都能避免。",
   [("衣服常带来小尴尬。", "Clothes bring small awkward moments.", "awkward（尴尬的）"),
    ("买时注意细节就能避免。", "Check details and avoid them.", "avoid（避免）")]),
  ("牛仔裤门襟", "Jeans Fly Length", "00:06", "牛仔裤门襟越长坐下后越容易鼓包凸起，比男生还男生，一定要选门襟短的。",
   [("门襟长坐下会鼓包。", "Long flies bunch when you sit.", "fly（门襟）"),
    ("要选门襟短的。", "Choose a short fly.", "short（短的）")]),
  ("拉链型号", "The Zipper Size", "00:19", "拉链头和拉链大小有直接关系，把拉链头翻过来看数字，45就是3号拉链，相对细软不易导致硬条。",
   [("拉链头上有型号数字。", "The zipper number is on the pull.", "zipper pull（拉链头）"),
    ("3号拉链更细软。", "Size 3 zippers are softer.", "soft（柔软的）")]),
  ("里布挂线泡", "Lined Skirts Need Loops", "00:29", "带里布的裙子要选里布和面料中间带小线泡的，能固定里布不乱跑，避免里布挂到腰上没下来。",
   [("里布中间要有线泡。", "Loops between layers hold the lining.", "lining（里布）"),
    ("固定里布不乱跑。", "They stop the lining from riding up.", "ride up（上移）")]),
  ("内衣透色", "Sheerness and Underwear", "00:40", "想避免内衣透色尴尬，选接近皮肤颜色的肉色；浅色裙子一定要看是否挂好里布。",
   [("选接近肤色的内衣。", "Choose skin-toned underwear.", "skin-toned（肤色）"),
    ("浅色裙子看透光。", "Check light skirts for sheerness.", "sheer（透光的）")]),
  ("无里布透色", "No Lining, See-Through", "00:55", "无里布的浅色面料，透到戒指颜色都能清楚看见，那穿什么颜色的内裤都会被曝光。",
   [("无里布透到看戒指。", "Without lining, you see a ring's color.", "see-through（透光的）"),
    ("穿什么内裤都曝光。", "Any underwear will show through.", "show through（透出来）")]),
  ("胸省尖尖", "The Bust Dart Peak", "00:59", "上衣带胸省的格外注意尖尖，要么做工问题要么省量太大，要选省量小、胸省是平缓弧线的。",
   [("胸省尖是做工或省量大。", "Sharp darts mean bad work or too much ease.", "dart（省道）"),
    ("选平缓弧线的胸省。", "Choose smooth, gentle curves.", "gentle curve（平缓曲线）")]),
  ("正例：平缓弧线", "Positive Example: Gentle Curve", "01:16", "正例的省道呈平缓弧线，而不是凸起的尖尖点，上身才没有尖尖的突兀感。",
   [("省道呈平缓弧线。", "Darts should curve gently.", "curve（弧线）"),
    ("上身才不突兀。", "No sharp points on the body.", "protruding（凸起的）")]),
 ],
),
]

def paraphrase_for(sentences):
    out = []
    for zh, en, note in sentences:
        word = note.split("（")[0].strip()
        out.append([f"用{word}换一种说法", en])
    return out

def main():
    for slug, title, title_en, duration, topic, url, scenes in V:
        data = {
            "meta": {
                "slug": slug, "title": title, "title_en": title_en,
                "duration": duration, "scenes": len(scenes),
                "sentences": sum(len(s[4]) for s in scenes),
                "date": DATE, "platform": PLATFORM, "source_url": url, "topic": topic,
            },
            "scene_imgs": [f"shot-{i+1:02d}" for i in range(len(scenes))],
            "scenes": [],
        }
        for i, (tc, te, t, ctx, sents) in enumerate(scenes, 1):
            data["scenes"].append({
                "id": f"s{i}", "title_cn": tc, "title_en": te, "time": t,
                "context": ctx,
                "sentences": [list(s) for s in sents],
                "paraphrase": paraphrase_for(sents),
                "speak": " ".join(en for _, en, _ in sents),
            })
        data["practice"] = []
        data["pitfalls"] = []
        data["shifts"] = []
        data["difficult_words"] = []
        data["footer_notes"] = f"来源：{title}（小红书，时长{duration}）"
        p = OUT / f"{slug}.json"
        p.write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"✓ {slug} {len(scenes)} scenes")

if __name__ == "__main__":
    main()
